### ISSUE TITLE
Colorize logger

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#100]
Currently our log messages are uncolorized which makes it a bit difficult to spot warnings and errors during runtime. There are some implementations floating around on the web which show the general gist.

**Comment by souravsingh** [comment]
I wish to do this.How do I start?

**Comment by wkerzendorf** [comment]
just color the log output. have a look online how other people do that.

**Comment by souravsingh** [comment]
@wkerzendorf I have done the fix.Sorry for asking a very naive question-In which folder should the Script go?

**Comment by souravsingh** [comment]
@wkerzendorf I have added a Pull Request for the script.I request you to have a look and see if it needs any changes-https://github.com/tardis-sn/tardis/pull/429

**Comment by souravsingh** [comment]
I have updated the PR.

**Comment by unoebauer** [comment]
@wkerzendorf, @souravsingh: status of this issue/feature request. The PR is out there and Travis seems to be happy with it...

**Comment by souravsingh** [comment]
@unoebauer We need to make changes in a lot of scripts to make Colorizing actually work.I am working on it right now.

**Comment by Pratik151** [comment]
@souravsingh  If you haven't made any progress on this I would like to give this a try.

**Comment by souravsingh** [comment]
@Pratik151 I have a script for colorizing the logs.Just not able to figure out how to hook it into the project.

**Comment by vedantrathore** [comment]
Can I work on this issue? Can someone point me on where to start with this?

**Comment by ftsamis** [comment]
@vedantrathore Given that you have installed and successfully ran the tardis_example following the directions [here](http://tardis.readthedocs.io/en/latest/installation.html), you can see how TARDIS produces log messages and try to colorize them with a different colour depending on the type of the message (info, warning, error, debug).

Feel free to ask in [gitter](https://gitter.im/tardis-sn/tardis) if having trouble with any step.

**Comment by wkerzendorf** [comment]
@unoebauer - I think this issue is of utmost importance to the project and therefore I'm resurrecting it.
