### ISSUE TITLE
HDF save config yml

### ISSUE THREAD

**Issue by marxwillia** [tardis-sn/tardis#1001]
I think the to_hdf method should save the configuration yml so that all the simulation settings are preserved in a saved HDFStore.  This should not take up much space, and I think it would prevent confusion.

**Comment by sashank27** [comment]
Hey @marxwillia, I would like to work on this. Can you point as to which `to_hdf` we have to modify?

**Comment by marxwillia** [comment]
@sashank27 the to_hdf() function is defined in the tardis/io/utils file.  Many tardis classes inherit from the HDFWriterMixin, and therefore can call to_hdf().  Many tardis classes therefore define hdf_properties that will be saved.  Play around with that and see if you can add a property to be saved.

**Comment by sashank27** [comment]
For a possible approach, we can add a `config` param to every class (`Simulation`, `MontecarloRunner`, `Radial1DModel`) that stores the configuration as an object parameter. Then we can add an attribute in `to_hdf` to ensure if the configuration is to be saved on hdf or not.

**Comment by marxwillia** [comment]
That seems more complicated than necessary.  The configuration should be read in and validated using the Configuration class.  Is it possible to add a to_hdf() function there?
