### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by achillefiore** [tardis-sn/tardis#1014]
Hi all,

I'm trying to install Tardis on a MacOS Catalina (10.15.2). I built the conda environment, activated it, then I cloned the GitHub repository with:

>git clone https://github.com/tardis-sn/tardis.git

and finally:

> cd tardis
> python setup.py install

but ant the end this is what I get:
<img width="1201" alt="Schermata 2020-01-25 alle 16 15 34" src="https://user-images.githubusercontent.com/60215789/73123300-d3d3cb00-3f8e-11ea-9263-680adeb461e0.png">

I saw there's a similar issue in the FAQ whose solution suggests to run:

> open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

but this file does not exist. Apparently this should be related to the fact that after the Catalina (or even Mojave...) update the entire command line toolkit package is placed in the directory /Library/Developer/CommandLineTools/usr/bin/, which however does not contain any *.pkg file. 
Could you help me to fix the problem? Thank you!

Achille

**Comment by wkerzendorf** [comment]
try to use the conda provided compilers by doing `conda install -c conda-forge compilers` in your environment

**Comment by achillefiore** [comment]
thank you a lot! This fixed the problem!
Cheers, Achille
