### ISSUE TITLE
collisional data missing

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#107]
This needs to be a meaningful error message when collision data is missing:

```
AttributeError: 'NLTEData' object has no attribute 'C_ul_interpolator'

```

Suggest that it should return a warning (or simply refuse to run) if asked for this and there is no data. I think its ok to just refuse to run if NLTE is asked  for and there is no collisional data (although it's also ok to continue provided that the user is thrown a big warning message)

**Comment by unoebauer** [comment]
@ssim, @wkerzendorf: PR #236 has been merged a long time ago, supposedly addressing this issue (well, a proper handling of the error...). I'd say we close this one...
