### ISSUE TITLE
Adding distance, redshift, reddening to final spectrum calculation

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#11]

**Comment by unoebauer** [comment]
@wkerzendorf, @ssim: this could be something for GSoC 16 - shouldn't be too hard to apply a simple Cardelli reddening law and the general redshift. Is it actually possible to account for the distance in the current Tardis version? I've seen multiple times now that the spectrum object has a distance attribute. I've never played with it though...

**Comment by AyushYadav** [comment]
I think I will work on this now given I have free time at hand right now....let me see if I can bring something valuable to this
~Ayush
