### ISSUE TITLE
Error installing tardis in Python 3.7

### ISSUE THREAD

**Issue by KapilBansal320** [tardis-sn/tardis#1113]
#### Code Sample, a copy-pastable example if possible
Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
warning: no previously-included files found matching '*.pyc'
warning: no previously-included files found matching '*.o'
no previously-included directories found matching 'build'
no previously-included directories found matching 'astropy_helpers\tests'
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    LONG_DESCRIPTION = f.read()
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3440: character maps to <undefined>
```python
# Your code here

```
#### Problem description
Getting this error when trying to install from setup.py
#### Expected Output

**Comment by wkerzendorf** [comment]
does not work with windows - sorry

**Comment by KapilBansal320** [comment]
Okk thanks
