### ISSUE TITLE
Add note that TARDIS only works on linux/mac

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1125]
Add this in the documentation

**Comment by Pabla007** [comment]
@wkerzendorf I have added that in my documentation already .
https://github.com/tardis-sn/tardis/pull/1061

**Comment by Phantsure** [comment]
Is there any way that we can make it work on Windows too? Maybe using linux subsystem or something like that. Because in my opinion it would be great if we are able to do that.
I can't work on this right now as I am not using Windows.

**Comment by epassaro** [comment]
Closed by #1189
