### ISSUE TITLE
Cannot import name 'montecarlo'

### ISSUE THREAD

**Issue by eparrag1** [tardis-sn/tardis#1148]
Hi,

I am installing TARDIS for the first time. I installed it using Anaconda 3.

Following the quickstart instructions, after running the below line in a jupyter notebook:
`sim = run_tardis('tardis_example.yml')`

I see the error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-3-1a68e481065f> in <module>
      1 #TARDIS now uses the data in the data repo
----> 2 sim = run_tardis('tardis_example.yml')

~/tardis/tardis/base.py in run_tardis(config, atom_data, packet_source, simulation_callbacks)
     23     from tardis.io.config_reader import Configuration
     24     from tardis.io.atom_data.base import AtomData
---> 25     from tardis.simulation import Simulation
     26 
     27     if atom_data is not None:

~/tardis/tardis/simulation/__init__.py in <module>
----> 1 from tardis.simulation.base import Simulation

~/tardis/tardis/simulation/base.py in <module>
      6 from collections import OrderedDict
      7 
----> 8 from tardis.montecarlo import MontecarloRunner
      9 from tardis.model import Radial1DModel
     10 from tardis.plasma.standard_plasmas import assemble_plasma

~/tardis/tardis/montecarlo/__init__.py in <module>
----> 1 from tardis.montecarlo.base import *

~/tardis/tardis/montecarlo/base.py in <module>
     14 from tardis.util.base import quantity_linspace
     15 from tardis.io.util import HDFWriterMixin
---> 16 from tardis.montecarlo import montecarlo, packet_source as source
     17 from tardis.montecarlo.formal_integral import FormalIntegrator
     18 

ImportError: cannot import name 'montecarlo'
```

​I believe this error was raised in issue #976 but the resolution was not explained.

Additionally, when importing tardis:

```
from tardis import run_tardis
from tardis.io.atom_data.util import download_atom_data
```

I receive the warning:

```
/Users/username/anaconda3/envs/tardis/lib/python3.6/importlib/_bootstrap.py:219: QAWarning: pyne.data is not yet QA compliant.
  return f(*args, **kwds)
```

Thanks very much, any help is much appreciated!

**Comment by jordi5** [comment]
Hi! Did you installed tardis using 
`pip install git+https://github.com/tardis-sn/tardis`

or 

`
git clone https://github.com/tardis-sn/tardis.git`
`cd tardis`
`python setup.py install
`

Also, just to check, are you inside the tardis environment?
You should run the Jupyter Notebook inside the tardis folder, and the [tardis_example.yml](https://raw.githubusercontent.com/tardis-sn/tardis/master/docs/models/examples/tardis_example.yml) should also be in the same folder.

You can ignore the QAcompliance warning, it will always pop up.

Did any of this help?

**Comment by jaladh-singhal** [comment]
> I installed it using Anaconda 3.

@eparrag1 Make sure you're using a **tardis environment** as @jordi5 mentioned. I think you're potentially missing to create a virtual environment like explained in [installation instructions](https://tardis-sn.github.io/tardis/installation.html#installing-tardis-with-anaconda) -  you need to do: `conda env create -f tardis_env3.yml` and then `conda activate tardis` before installing tardis.

**Comment by eparrag1** [comment]
Hi - thank you for your responses.

I began with 

```
conda env create -f tardis_env3.yml
conda activate tardis
```

I then followed with the below:

```
git clone https://github.com/tardis-sn/tardis.git
cd tardis
python setup.py install
```

I added the tardis_example.yml and kurucz_cd23_chianti_H_He.h5 files inside this tardis folder, then launched jupyter notebook from the terminal and created a new notebook.

**Comment by jordi5** [comment]
This is an issue with the install script.
For a quick fix run :

`run setup.py develop`

and all should work

**Comment by eparrag1** [comment]
Hi jordi5,

When I run the jupyter notebook in the parent directory, it can't find tardis when I try and import it:

`cannot import name 'run_tardis' from 'tardis' (unknown location)`

I also went back and noticed a line returned when running setup.py:

```
  File "tardis/montecarlo/setup_package.py", line 2, in <module>
    from tardis import __path__ as TARDIS_PATH
  File "/Users/eleonoraparrag/Documents/TARDIS/tardis/tardis/__init__.py", line 6, in <module>
    import pyne.data
ModuleNotFoundError: No module named 'pyne.data'
```

It looks like this could be where the problem is coming from?

Thanks

**Comment by jordi5** [comment]
the pyne problem ussually comes up when trying to run on Windows, since pyne has issues with 64-bit Windows. Could it be that you are on Windows?

**Comment by eparrag1** [comment]
Hi jordi5 - I'm running this on a mac

**Comment by jordi5** [comment]
can you run `which python` in the terminal after activating the environment?

**Comment by eparrag1** [comment]
This gives me /Users/username/anaconda3/envs/tardis/bin/python

**Comment by jordi5** [comment]
Would you mind doing all the process again? Remove the tardis folder, and the environment; clone, reinstall the env and and reinstall tardis. As an option could you try to place the tardis folder in the home directory instead of a subdirectory?
I know it's annoying but sometimes this works.

**Comment by eparrag1** [comment]
Hi jordi5, placing the tardis folder in the home directory fixed the problem, it's working now!
Thanks very much!

**Comment by parikshit14** [comment]
Simplest solution is to open the **notebook(.ipynb file)** in `tardis(main-folder)/tardis(sub-folder)/`  . It needs to be rectified in the installation guide.
