### ISSUE TITLE
Create (and enforce) a TARDIS code style guide

### ISSUE THREAD

**Issue by harpolea** [tardis-sn/tardis#1170]
There should be a section of the documentation which describes TARDIS' code style conventions. This will help the code's readability and assist new contributors. The guide could cover

- adherence to PEP 8
- function and variable names
- docstrings

To enforce this, it would be helpful to automatically run a linter (e.g. flake8) on PRs which prints out any infringements of PEP 8 it finds. (Note some of PEP 8's suggestions are not always useful, so I suggest creating a `.flake8` file to list files and style conventions we'd like it to ignore)

**Comment by harpolea** [comment]
This will address #1094

**Comment by jaladh-singhal** [comment]
@harpolea I think [autopep8](https://github.com/hhatto/autopep8) can be helpful (I came to know about when making PR on astroquery)? 

Apparently, it also provides option of configuring with `.flake8` as you mentioned!

**Comment by harpolea** [comment]
Yeah, there are several style linters around (`black` is another popular one) - I mainly suggested `flake8` as that’s the one I normally use, but they all pretty much do the same thing.

**Comment by arjunsavel** [comment]
Another thing that might be helpful is [isort](https://github.com/timothycrosley/isort) — just in the way of making things more automated.

**Comment by harpolea** [comment]
One way to do this would be to use a precommit hook: https://github.com/yt-project/yt/pull/2600

**Comment by jaladh-singhal** [comment]
Code style guide has been "create"ed in #1405 but we still need to work on "enforce"ing it by creating a pre-commit hook!

**Comment by jaladh-singhal** [comment]
> we still need to work on "enforce"ing it
It's made possible by #1398, new PRs can't be pushed unless code is formatted by black
