### ISSUE TITLE
Exit pipelines when a command fails (bash)

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/tardis#1174]
Currently a when running a `bash` task on Azure Pipelines the `succeeded` or `failed` status is determined by the exit code of the last command (See #1162 for example).

## Suggestion 
Would be nice to make steps fail if **any** command fails by setting the `SHELLOPTS=errexit` variable across the entire job.  Prepending this step to all pipelines should work:

```
      - bash:  echo "##vso[task.setvariable variable=shellopts]errexit"
        displayName: "Force exit on error (bash) "
```

See also:

- https://github.com/microsoft/azure-pipelines-agent/issues/1803
- https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

**Comment by epassaro** [comment]
Have this in mind @kaushik94.

**Comment by kaushik94** [comment]
@epassaro check https://github.com/tardis-sn/tardis/pull/1210/files. I made the change.

**Comment by epassaro** [comment]
As @kaushik94  proved, this piece of code worked! See: #1210.

Closed.
