### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#12]
Added first logging hooks. There's two seperate logging streams. The normal one logs everything outside the TARDIS montecarlo simulation. The second one is a packet logger, which needs to be switched on at compile time. It creates very large logfiles and is useful for debugging the packet propagation.

There's still quite a few functions that don't have loggers attached to. 

Close this issue once the logging has been satisfactorily implemented

**Comment by unoebauer** [comment]
@wkerzendorf: a sufficient level of satisfaction has been reached, wouldn't you agree? Also, there is currently the colourised log PR and issue going around. Consequently, I am closing this one.
