### ISSUE TITLE
Use format strings throughout TARDIS

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1205]
We mostly use the old-style version of string formatting `"hello {0}".format(world_str)` in py36 we can now switch to `f"hello {world_str}"` - we should use this throughout TARDIS

**Comment by abhaydhiman** [comment]
Can I work on this?

**Comment by shrey27tri01** [comment]
@wkerzendorf Can I take up this task?

**Comment by yashagg2001** [comment]
I changed string formatting from .format() to f-string formatting in all the files. Please check it.  #1386
