### ISSUE TITLE
Explain in documentation how to compile tardis with vpacket logging

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1215]
As mentioned in [`tardisanalysis/docu/instructions.md`](https://github.com/tardis-sn/tardisanalysis/blob/master/docu/instructions.md#tardis_kromer_plotpy), 
> Important: The virtual packet logging capability must be active in order to use this tool to generate Kromer plots from the virtual packet population. Thus, Tardis must be compiled with the flag --with-vpacket-logging.

As suggested by @marxwillia, there are other several essential features of tardis which require compiling it with vpacket logging, but it isn't documented anywhere in documentation. So it can be explained in installation documentation of tardis with a reason why it will be needed!

**Comment by andrewfullard** [comment]
This has changed with numba-montecarlo. See #1342 for reference.
