### ISSUE TITLE
"Quickstart for tardis" bug

### ISSUE THREAD

**Issue by aluttery456123** [tardis-sn/tardis#1243]
TARDIS has been successfully downloaded and runs fine so far. I used the "Quickstart for TARDIS" [https://tardis-sn.github.io/tardis/quickstart/quickstart.html](url) guide to start off, but I've gotten a few error messages. The code is being run through iPython, but I still needed to explicitly import "matplotlib.pyplot as plt" and modify the script in order for it to stop returning "name 'figure' not defined" for line 17.

After patching that bug, the system started returning an attribute error for "luminosity_density_lambda". The only way to get this to stop and actually plot the synthetic spectra was to comment out line 18, "normal packets". Does anyone know why, and how to fix that line so as not to forsake including "normal packets" data in the plot? That would be ideal. 

```ipython --pylab
# AttributeError                            Traceback (most recent call last)
sim1.py in <module>
     16
     17 plt.figure(figsize=(10,6))
---> 18 plt.plot(spectrum.wavelength, spectrum.luminosity_density_lamda, label='normal packets')
     19 plt.plot(spectrum.wavelength, spectrum_virtual.luminosity_density_lambda, label='virtual packets')     20 plt.plot(spectrum.wavelength, spectrum_integrated.luminosity_density_lambda, label='formal integral')

AttributeError: 'TARDISSpectrum' object has no attribute 'luminosity_density_lamda'

```

**Comment by epassaro** [comment]
There's a typo, you spelled `lamda` instead of `lambda`.

**Comment by aluttery456123** [comment]
Thank you, I would've never seen that!
