### ISSUE TITLE
Fix how vpacket-logging status is saved

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1246]
## Problem
Currently vpacket-logging status is saved in [`tardis/data/vpacket_config.yml`](https://github.com/tardis-sn/tardis/blob/master/tardis/data/vpacket_config.yml) which is required [to check](https://github.com/tardis-sn/tardis/blob/master/tardis/montecarlo/base.py#L43) whether to save virtual packet properties to hdf file or not.

Whenever user compiles tardis `--with-vpacket-logging`, the status updates in this `vpacket_config.yml` file but because it lives within tardis project, it gets tracked by git when developing. This becomes problem when developer has to undo this change while committing due to which virtual packet properties are no longer saved in hdf. 

This is a **user-specific** information which must not be present in tardis repo and should be created on user's machine instead.

## Possible solutions
Based on where we want it to live, there are two solution
#### 1. Let it be in `tardis/data/` as `vpacket_config.yml` and gitignore it
The current implementation [wants this file to be already present](https://github.com/tardis-sn/tardis/blob/master/tardis/montecarlo/setup_package.py#L24) in tardis project, so once we remove it - we can make sure that it gets created when file is not present. And then gitignore will take care that it won't get tracked on changes.

#### 2. Store this info as `vpacket_logging` key in `tardis_internal_config.yml`
Since `tardis_internal_config.yml` already stores user specific data (currently `data_dir`) within astropy config dir, we can also store this vpacket logging status within it by making necessary changes in [`tardis/io/config_internal.py`](https://github.com/tardis-sn/tardis/blob/master/tardis/io/config_internal.py).

---
According to me, we should go for option-2 - but before I make PR, I wanted more opinions.

**Comment by marxwillia** [comment]
Of the two options you present, I think I like option 2.  I am also a little confused because my vpacket_logging.yml file says `false` even though I have compiled tardis with vpacket logging and just recently made a kromer plot.  Also I cannot find any discussion of this file in the documentation and there probably should be something.

**Comment by jaladh-singhal** [comment]
> I am also a little confused because my vpacket_logging.yml file says false even though I have compiled tardis with vpacket logging and just recently made a kromer plot.

This is what happened to me. Simulation object always saves virtual packet properties (if you've compiled tardis with vpacket logging) irrespective of what is stored in this `vpacket_logging.yml`. This file becomes necessary when saving hdf properties, to check if vpacket-logging is enabled because there doesn't seem any direct way to determine it (at least I couldn't find it). 

And your file says `false` most likely because you unintentionally discarded changes in this file i.e. tracked by git when comitting something or switching branches.

> Also I cannot find any discussion of this file in the documentation and there probably should be something.

@marxwillia If you're interested to know, this was implemented by #967 to fix issue #800 - the whole purpose of adding this file was to determine if vpacket-logging is enabled when saving virtual packet properties to hdf.

**Comment by kaushik94** [comment]
@marxwillia @jaladh-singhal I implemented that solution. I remember there was a reason for this. Let me check and get back.

**Comment by kaushik94** [comment]
I think this does make sense as I did not know about the `virt_logging` option. I was not aware.
