### ISSUE TITLE
Add Code quality guidelines to TARDIS docs

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1253]
The main aim of these guidelines will be to explain what does good quality code in a PR expects (meaning of "maintaining code quality" section in CONTRIBUTING.md):
  - code covers edge cases, exception handling where required
  - easy to maintain and extend - OOP design pattern
  - follows PEP8 style guide (use of black)
  - more pointers can be found in [this code quality guide by real-python](https://realpython.com/python-code-quality/)

Code style guide (#1170) should probably be a section within it and this guide should be placed within "Contributing to TARDIS" section in https://github.com/tardis-sn/tardis/blob/master/docs/index.rst

> **NEED**: This is pointed in [CONTRIBUTING.md](https://github.com/jaladh-singhal/tardis/blob/contrib-guide/CONTRIBUTING.md#editing-the-documentation) as a void link (`#`), so it is necessary to add them soon.

**Comment by arjunsavel** [comment]
Similar to #1170?

**Comment by jaladh-singhal** [comment]
Can use some inspiration from astropy - https://docs.astropy.org/en/latest/development/codeguide.html
