### ISSUE TITLE
Save configuration yml with HDF

### ISSUE THREAD

**Issue by arjunsavel** [tardis-sn/tardis#1281]
#### Problem description
In the interest of reproducibility, the configuration .yml file should be saved in the `.to_hdf` call. This would ensure that all parameters of the simulation (e.g. the montecarlo parameters) can be easily inspected post-run.

**Comment by marxwillia** [comment]
Possibly we need a way to save the Configuration object that is created in `run_tardis()`

**Comment by andrewfullard** [comment]
Completed with 983213bf23af493e8b569cba12e578f641163f19
