### ISSUE TITLE
Create an option to build docs without executing notebooks

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1282]
Currently, whenever docs are build, the notebooks which are marked to be executed by nbsphinx make build time very long  - since each of them runs simulation model. This is fine for production but for development this becomes really annoying.

So there must be some option or flag while running `make html` or `python -m sphinx build` to explicitly disable notebooks' execution by nbsphinx on run-time. 

Based on my very brief search, nbsphinx doesn't provide any such option for execute control during run-time but only for conf.py and individual notebook's metadata. But I believe, there should be a way to implement this, by adding some if-else logic in conf.py for nbsphinx execute setting which listens to flag specified to build command or something like that.

**Comment by epassaro** [comment]
The default way to execute cells while rendering notebooks with `nbsphinx` is to leave all cells blank. If some cell is already executed then the notebook is **not executed**.

I understand the TARDIS documentation relies on notebook metadata to **always** execute the notebook and ignore the above method. Using this method and running once the Quickstart guide should be enough to build the documentation more quickly.

I don't know about a fancier way to do this.

**Comment by epassaro** [comment]
Closed by #1615
