### ISSUE TITLE
No module named 'pyne'

### ISSUE THREAD

**Issue by harish-infinity** [tardis-sn/tardis#1287]
#### Code Sample, a copy-pastable example if possible

```python
pip3 install git+https://github.com/tardis-sn/tardis

ModuleNotFoundError: No module named 'pyne'

```
#### Problem description

While installing Tardis via pip3; there was a pyne module error

**Comment by wkerzendorf** [comment]
Please follow these installation instructions - https://tardis-sn.github.io/tardis/installation.html

**Comment by epassaro** [comment]
We adressed this issue here https://github.com/tardis-sn/tardis/issues/1211. 

Please install TARDIS doing:

```
git clone https://github.com/tardis-sn/tardis.git
cd tardis
python setup.py install
```
