### ISSUE TITLE
Error when running Tardis

### ISSUE THREAD

**Issue by elifavaro** [tardis-sn/tardis#1292]
Hi, I have an error when I run Tardis, related to the atom data.
On a Jupyter notebook, I do:

#### Code Sample, a copy-pastable example if possible

```python
from tardis import run_tardis
from tardis.io.atom_data.util import download_atom_data

download_atom_data('kurucz_cd23_chianti_H_He')

!curl -O https://raw.githubusercontent.com/tardis-sn/tardis/master/docs/models/examples/tardis_example.yml

sim = run_tardis('tardis_example.yml')

```
#### Problem description

The files are downloaded, but it gives me error when the last line of code is executed:

[tardis.plasma.standard_plasmas][INFO   ]  Reading Atomic Data from kurucz_cd23_chianti_H_He.h5 (standard_plasmas.py:87)
[tardis.io.atom_data.util][INFO   ]  Atom Data kurucz_cd23_chianti_H_He.h5 not found in local path. Exists in TARDIS Data repo /home/elizabeth/Downloads/tardis-data/kurucz_cd23_chianti_H_He.h5 (util.py:35)
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
~/anaconda3/envs/tardis/lib/python3.7/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    654         try:
--> 655             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    656         except IOError as err:  # pragma: no cover

~/anaconda3/envs/tardis/lib/python3.7/site-packages/tables/file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 

~/anaconda3/envs/tardis/lib/python3.7/site-packages/tables/file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    777         # Now, it is time to initialize the File extension
--> 778         self._g_new(filename, mode, **params)
    779 

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1652, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 420, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file '/home/elizabeth/Downloads/tardis-data/kurucz_cd23_chianti_H_He.h5'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-4-b419133c9756> in <module>
----> 1 sim = run_tardis('tardis_example.yml')

~/anaconda3/envs/tardis/lib/python3.7/site-packages/tardis_sn-3.0.dev3501-py3.7-linux-x86_64.egg/tardis/base.py in run_tardis(config, atom_data, packet_source, simulation_callbacks)
     39 
     40     simulation = Simulation.from_config(
---> 41         tardis_config, packet_source=packet_source, atom_data=atom_data
     42     )
     43     for cb in simulation_callbacks:

~/anaconda3/envs/tardis/lib/python3.7/site-packages/tardis_sn-3.0.dev3501-py3.7-linux-x86_64.egg/tardis/simulation/base.py in from_config(cls, config, packet_source, **kwargs)
    530         else:
    531             plasma = assemble_plasma(
--> 532                 config, model, atom_data=kwargs.get("atom_data", None)
    533             )
    534         if "runner" in kwargs:

~/anaconda3/envs/tardis/lib/python3.7/site-packages/tardis_sn-3.0.dev3501-py3.7-linux-x86_64.egg/tardis/plasma/standard_plasmas.py in assemble_plasma(config, model, atom_data)
     88 
     89         try:
---> 90             atom_data = AtomData.from_hdf(atom_data_fname)
     91         except TypeError as e:
     92             print(

~/anaconda3/envs/tardis/lib/python3.7/site-packages/tardis_sn-3.0.dev3501-py3.7-linux-x86_64.egg/tardis/io/atom_data/base.py in from_hdf(cls, fname)
    157         fname = resolve_atom_data_fname(fname)
    158 
--> 159         with pd.HDFStore(fname, "r") as store:
    160             for name in cls.hdf_names:
    161                 try:

~/anaconda3/envs/tardis/lib/python3.7/site-packages/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    535         self._fletcher32 = fletcher32
    536         self._filters = None
--> 537         self.open(mode=mode, **kwargs)
    538 
    539     def __fspath__(self):

~/anaconda3/envs/tardis/lib/python3.7/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    685             # is not part of IOError, make it one
    686             if self._mode == "r" and "Unable to open/create file" in str(err):
--> 687                 raise IOError(str(err))
    688             raise
    689 

OSError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1652, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 420, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file '/home/elizabeth/Downloads/tardis-data/kurucz_cd23_chianti_H_He.h5'

**Comment by epassaro** [comment]
Hi Elizabeth,

Currently we have a problem related to the hosting of the atomic data. 

Please download the atom data manually [from here](http://opensupernova.org/~epassaro/kurucz_cd23_chianti_H_He.h5) and place it in `Downloads/tardis-data` folder in your computer. Then continue with the Quickstart guide ignoring the `download_atom_data` step.

The `download_atom_data` function should be working again after merging #1292, hopefully tomorrow.


Saludos

**Comment by elifavaro** [comment]
Hi Ezequiel,

Thank you so much, it's already working! :)

Saludos

**Comment by wkerzendorf** [comment]
Thanks @epassaro - should we close this?

**Comment by elifavaro** [comment]
Yes. Thanks!
