### ISSUE TITLE
Reading csvy model causes problems using `Configuration`

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1294]
#### Code Sample, a copy-pastable example if possible

```python
config = Configuration.from_yaml('blondin_model_compare_ddc10.yml')
run_tardis(config)
```
#### Problem description

This produces an error about `v_inner_boundary` not allowed to be defined. Just using the file directly works. 

Added by Jordi:

Using a similar procedure with a different file produces a different error:

```python
config = Configuration.from_yaml('tardis_csvy_example.yml')
run_tardis(config)
```

jsonschema.exceptions.ValidationError: Additional properties are not allowed ('config_dirname' was unexpected)

If the dictionary is being generated by TARDIS itself this shouldn't be a problem.
I'm looking into both problems

**Comment by jordi5** [comment]
I'm looking into it

**Comment by jordi5** [comment]
```    @classmethod
    def from_yaml(cls, fname, *args, **kwargs):
        try:
            yaml_dict = yaml_load_file(
                fname, loader=kwargs.pop("loader", YAMLLoader)
            )
        except IOError as e:
            logger.critical(f"No config file named: {fname}")
            raise e

        tardis_config_version = yaml_dict.get("tardis_config_version", None)
        if tardis_config_version != "v1.0":
            raise ConfigurationError(
                "Currently only tardis_config_version v1.0 supported"
            )

        kwargs["config_dirname"] = os.path.dirname(fname)

        return cls.from_config_dict(yaml_dict, *args, **kwargs)

```
@wkerzendorf  isn't the usage you propose is redundant? `from_yaml` already runs `from_config_dict`
