### ISSUE TITLE
NumFOCUS Donation Link

### ISSUE THREAD

**Issue by lisamartin72** [tardis-sn/tardis#1305]
Hi Tardis project!

Attached are the URL and code for your NF donation button. Most of our sponsored projects have a donation button on their websites. Please reach out if you have any questions, and welcome!

Best, 

Lisa Martin
finance@numfocus.org

https://numfocus.salsalabs.org/donate-to-tardis

```
<a href="https://numfocus.salsalabs.org/donate-to-tardis" target="_blank" style="background:#FFA500;padding:10px;margin:10px 0px;text-align:center;text-decoration:none;font-size:12pt;color:#222222;font-family:Arial, Helvetica, sans-serif;display:inline-block;">Donate Now!</a>
```

**Comment by wkerzendorf** [comment]
@lisamartin72 we added buttons to our `Readme.rst` if you want to have a look.
