### ISSUE TITLE
Benchmarks and Tests for Cynthons' cdef Functions

### ISSUE THREAD

**Issue by orbitfold** [tardis-sn/tardis#131]
I want to move the remaining utility functions to C.

These include:
```
line_search, macro_atom, move_packet, compute_distance2outer, compute_distance2inner, compute_distance2line, compute_distance2electron, get_r_sobolev
```
For this to work we need tests and benchmarks for them. I cannot write them because I don't know what is expected of those functions. Having tests and benchmarks will be both useful and help people understand what they do. I think tests can fail if need be (i.e. if the function does not signal an exception that it should, or in some other way does not behave like it should). Benchmarks should be added to asv/benchmarks/benchmarks.py. There is an example for binary_search there.

**Comment by unoebauer** [comment]
No longer relevant - all done in Pure C now. FYI @wkerzendorf - I am closing this. Nice figure though - something for the official docu (if not yet included)

**Comment by wkerzendorf** [comment]
@unoebauer should be in the documentation - as far as I can tell.
