### ISSUE TITLE
Error while setting up local development environment

### ISSUE THREAD

**Issue by shrey27tri01** [tardis-sn/tardis#1311]
#### Problem description
I was facing this issue while installing TARDIS for development.  
After activating the `conda` environment and following the installation instructions for development [here](https://tardis-sn.github.io/tardis/development/git_workflow.html#forking), on running `python setup.py develop`, I get the following error:  
 ```python
building 'tardis.montecarlo.montecarlo' extension     
error: unknown file type '.pyx' (from 'tardis/montecarlo/montecarlo.pyx')
```
I tried troubleshooting this error from [here](https://tardis-sn.github.io/tardis/installation.html#installation-troubles-faq), but to no avail. I also tried building the `tardis/montecarlo/montecarlo.pyx` by hand, but the error still persists.

#### Expected Output
`python setup.py develop` should install (semi-install) `tardis` on my path. But it is not working as expected.

**Comment by wkerzendorf** [comment]
is this on linux?

**Comment by shrey27tri01** [comment]
@wkerzendorf Yes, I am on a Linux machine.

**Comment by harish-infinity** [comment]
Yes, I was facing the same problem from last month.

**Comment by shrey27tri01** [comment]
@wkerzendorf Any updates on the issue? :)

**Comment by JigarJoshi04** [comment]
Any updates on this issue?

**Comment by epassaro** [comment]
The TARDIS installation is in good shape, we test it several times per day on continuous integration. I would suggest remove your env and start again.

**Comment by epassaro** [comment]
Also, check if you have `PYTHONPATH` variable declared in your env, this is troublesome and not fully compatible with Anaconda.

**Comment by JigarJoshi04** [comment]
thank you.
