### ISSUE TITLE
Update citation guidelines

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1338]
Update the citation procedure in various places in TARDIS. PR #974 was an attempt to do this but needs to be rebased.

**Comment by priyanshu2706** [comment]
Hey guys, is this issue closed?

**Comment by KevinCawley** [comment]
This issue is still open @priyanshu2706.

**Comment by priyanshu2706** [comment]
Hello @KevinCawley , I want to contribute to this issue but I can't understand how to. I get that i need to update some citation details but where? Can you please help me?

**Comment by KevinCawley** [comment]
@priyanshu2706 Sorry for the late response, it slipped my attention. I will get back to you as soon as I have an answer for what this issue wants to accomplish specifically and where changes should be made.

**Comment by KevinCawley** [comment]
@priyanshu2706 From what I have gathered. https://github.com/tardis-sn/tardis/blob/master/docs/tardis.bib is a bibliographic file that's used to create references in the TARDIS docs. The first reference in that file on line two would be called by :cite:`Abbott1985`. 

Citations in the docs that are missing proper entries in this file should be added. You can get this .bib style entries from the NASA ADS. Let me know if you have any other questions and I will try to answer them.
