### ISSUE TITLE
Remove virtual packet logging compile flag

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#1342]
#### Problem description

--with-virtual-packet-logging is deprecated with the numba code and can be removed.

**Comment by DhruvSondhi** [comment]
Hello, I was going through the code so as to find this setting but I am afraid I am not able to pinpoint the exact location ... I do have found something in `setup.py` but this exact flag is not found 😞 ... Can you please shed some more light on this if possible? 🤔

**Comment by antreev-brar** [comment]
Since it has been almost two weeks since the last comment. I would like to work on this issue.
