### ISSUE TITLE
Config parser should verify that parameters are physically realistic

### ISSUE THREAD

**Issue by Rodot-** [tardis-sn/tardis#1343]
#### Problem description

tardis will currently run when given negative abundances without complaining.  Other physically unrealistic parameters like negative densities are also run without complaint resulting in odd behavior of TARDIS (freezing up for example).  We should implement some sort of checks in the config parsers (or when we run tardis) to make sure that the config represents a physically realistic system

**Comment by aribalam** [comment]
@Rodot- Would like to take this up. Could you point me in the right direction?

**Comment by DhruvSondhi** [comment]
@andrewfullard this issue can be closed !!
