### ISSUE TITLE
Document refdata comparison with pytest

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1350]
Update the documentation to not use `python setup.py test` and use `pytest` in ref data comparison 
https://tardis-sn.github.io/tardis/development/update_refdata.html

**Comment by epassaro** [comment]
That page needs a full rebuild, still using Travis (!).

**Comment by sourabhsingh282** [comment]
@epassaro hello sir can you assign me this issue

**Comment by epassaro** [comment]
Hi @sourabhsingh282 , currently we are re-implementing reference data comparison in a very different way and would be ready soon. There are other issues to work on by the time!.

**Comment by epassaro** [comment]
Closed by #1609
