### ISSUE TITLE
Parallelization in montecarlo main loop

### ISSUE THREAD

**Issue by Rodot-** [tardis-sn/tardis#1355]
### Problem description
Since the numba merge, the option for enabling parallelization is no longer functional when running setup.py.  Currently, there is no way to enable parallelization from the nthreads field in the config files.  Numba supports parallelization through jit kwargs and environment variables.  These changes should be made to the numba branch to allow user-specified multithreading.  The setup.py openmp argument should also be removed from both the script and the documentation as parallelization is inherent in numba.

**Comment by andrewfullard** [comment]
This was partially fixed with PR #1365
