### ISSUE TITLE
Add virtual_packet_logging option to run_tardis()

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1356]
Current way (after merging numba) is to specify this option in the configuration file. Considering visualization tools we're developing, it'll be more convenient if user can set this option during run-time instead of adding/removing it again & again from their configuration file.

**Comment by andrewfullard** [comment]
Would it not be reasonable to add it to the visualization script using:
`config.spectrum.virtual.virtual_packet_logging = True`?

**Comment by wkerzendorf** [comment]
I agree

**Comment by andrewfullard** [comment]
I should be clear- the script that the user runs should begin with that option if they want to enable the logging without modifying their YAML. Note that the logging is not a high performance cost as far as I can tell, it simply increases the size of the HDF, so there is not much downside for the user to leave it turned on.
