### ISSUE TITLE
Restructure documentation to make sidebar look more informative

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1357]
## Problem description

Current structure in docs doesn't organizes pages in a way that is easy to find. We need to make changes in hierarchical changes in TOC, so that sidebar in https://tardis-sn.github.io/tardis/ becomes informative enough to get a gist of important pieces of content at one glance!

## Expected Solution
Required hierarchy in sidebar:
![image](https://user-images.githubusercontent.com/36361463/100095935-48161e00-2e81-11eb-9f7c-0150b24f049b.png)

- 1st level entries with "main title" refers to the top level heading that appears in blue - like "Using TARDIS" at sidebar on https://tardis-sn.github.io/tardis/
- 2nd level bullets with "shown in scrollbar" refers to the items that directly appear under them (in white) - like "Running TARDIS" at sidebar on https://tardis-sn.github.io/tardis/
- 3rd level bullets refer to the contents that appear only when clicking on a 2nd level item (above) redirects us to its page and then sidebar expands to show them - like try clicking "Running TARDIS" you'll reach https://tardis-sn.github.io/tardis/running/index.html

Most of these changes will only need to change TOCs but some may require to actually move rst files from one directory to another under `docs/`

**Comment by smithis7** [comment]
What would we be doing with the testing section?
