### ISSUE TITLE
Many links in the documentation do not work

### ISSUE THREAD

**Issue by smithis7** [tardis-sn/tardis#1363]
#### Problem description

The references in ```docs/running/to_hdf.rst``` are not appearing correctly when the documentation is built. This can be seen here: https://tardis-sn.github.io/tardis/running/to_hdf.html

#### Expected Output

The two references (marked with ```:ref:```) should link to ```docs/running/interaction/to_hdf.ipynb``` and ```docs/running/interaction/hdf_writer.ipynb``` respectively.

**Comment by smithis7** [comment]
Several other links marked the same way with ```:ref:``` throughout the documentation also do not work. There are warnings that you get when locally building the documentation that gives you all of these links.

**Comment by smithis7** [comment]
For the following images, what should these links be pointing to (they are currently pointing to nonexistent documents):
![tardis2](https://user-images.githubusercontent.com/71480393/103068319-e7b2f300-458a-11eb-8f8a-d6a696d8c972.png)
![tardis3](https://user-images.githubusercontent.com/71480393/103068334-eda8d400-458a-11eb-8fa1-572521cb67fd.png)
![tardis4](https://user-images.githubusercontent.com/71480393/103068346-f3061e80-458a-11eb-9361-47bdfb2b023a.png)

**Comment by smithis7** [comment]
Additionally, `docs/physics/plasma/old_plasma.rst` is not in any toctree. Do we still need it? It was referenced in `docs/using/components/configuration/configuration.rst` but I think that can be switched over to the new plasma page (`docs/physics/plasma.rst`). The only other thing is that it has a section on tau_sobolev which is referenced in at least one other document. I don't think we have something like that on the new plasma page.

**Comment by epassaro** [comment]
There's a command to check all non-working links, it's something like `sphinx-build -b linkcheck . _build/html ` (assuming you are on `docs/`) and I think just works for external links.

**Comment by smithis7** [comment]
Yeah, I know what links are broken. It's just that I don't know how to fix the links that I just pointed out (I don't know what document they should point to). They're all internal links.
