### ISSUE TITLE
Add instruction to enable virt_packet_logging in widgets documentation

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1374]
Line info widget, Kromer Plot, and future visualization tools need virtual packet data but it is not enabled by default (since it is a costly operation). So we need instructions to tell them how to enable it by editing their configuration file.

**Comment by karban8** [comment]
Hi sir I would like to take up this issue. Please guide me in the right direction.

**Comment by jaladh-singhal** [comment]
This instruction is already present in SDEC plot notebook in documentation. But you should add this suitably in the line info widget section in the generating widgets notebook.

**Comment by karban8** [comment]
> This instruction is already present in SDEC plot notebook in documentation. But you should add this suitably in the line info widget section in the generating widgets notebook.

Thank you for guiding me. Working on it
