### ISSUE TITLE
Add documentation for parallel numba execution

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#1376]
#### Problem description

Currently there is no clear documentation for how to run the numba code in parallel. The user must set the montecarlo.nthreads value in the configuration to set a number of threads equal to nthreads. numba will then automatically use these threads where it can to parallelise the code. 

I believe that the formal integrator currently requires the OpenMP setup still for parallel computation, and therefore uses the same nthreads variable.

**Comment by aribalam** [comment]
@andrewfullard I would like to take this up. Could you point me in the right direction?

**Comment by andrewfullard** [comment]
Instances of OpenMP parallelization need to be removed from the documentation for modules that aren't the formal integrator. The installation guide must be updated to exclude OpenMP. A new section of the documentation should be added describing the requirements for parallel execution that are described in the issue here. I would suggest putting it in the "Using TARDIS" section.
