### ISSUE TITLE
Incorrect data types for real packet logging output data

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#1389]
#### Problem description

last_interaction_type , last_line_interaction_in_id and last_line_interaction_out_id are saved as float in sim.runner whereas corresponding properties for virtual packets are saved as int which is the expected type. 

#### Expected Output

Save them as int

**Comment by DhruvSondhi** [comment]
Hello,  Can some more light be shed upon this issue? Where can I find the required function?
I found this virtual packets variable in 2-3 files but was not able to pinpoint the location where this bug is arising. :thinking:

**Comment by andrewfullard** [comment]
I think it most likely arises in `montecarlo_main_loop` in `tardis/montecarlo/montecarlo_numba/base.py` where the arrays are defined to pass through to the sim.runner.
