### ISSUE TITLE
Documentation on Virtual Packets

### ISSUE THREAD

**Issue by sofiatti** [tardis-sn/tardis#139]
It would be great to have a better description.

**Comment by unoebauer** [comment]
@ssim - status of this issue? A quick peruse of the documentation didn't reveal anything detailed about the virtual packet scheme...If so - we should definitely keep this issue open.

**Comment by unoebauer** [comment]
A more detailed description of the virtual packet scheme is now part of the documentation (part of Monte Carlo primer section) - closing
