### ISSUE TITLE
TARDIS version not correctly displayed in docs

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/tardis#1391]
Not correctly displayed on https://tardis-sn.github.io/tardis, but correctly displayed when building site locally.

EDIT: See upper left corner of the site.

**Comment by JigarJoshi04** [comment]
I have created a PR #1400  for this issue.

**Comment by epassaro** [comment]
Hi @JigarJoshi04 ! That's not what the issue is about, `README.md` is not important here.

**Comment by DhruvSondhi** [comment]
Hello @epassaro, 
After going through this issue I actually saw it was showing Dev 3.0 version. Do you want it to have a hardcoded value or should it be dynamic (dynamic one may be a bit tricky) :thinking: . If it's fine can I work on this?

**Comment by epassaro** [comment]
We don't want to have it hardcoded. The problem is this was already done and stopped working for unknown reasons (maybe something related to documentation deployment on GitHub Pages?). I can't tell you this is not easy to figure out, but feel free to tackle this issue.

**Comment by epassaro** [comment]
I was porting the carsus doc to GA and suddenly realized what's happening. The `checkout` action from GA by default just fetches the latest commit, and the "old" `astropy_helper` version solver uses the number of commits to calculate the `dev` version. Using `fetch-depth: 0` in the step args solves this issue.
