### ISSUE TITLE
PyQT dependency

### ISSUE THREAD

**Issue by orbitfold** [tardis-sn/tardis#140]
Is it sensible to not be able to build TARDIS without pyqt and sip present? This makes it a bit harder to build and use in clusters and in general the fewer dependencies the merrier. It should be possible to make the GUI optional. Another thing is that you cannot install pyqt and sip via pip anymore as far as I can work it out. Or am I missing something?

**Comment by unoebauer** [comment]
@orbitfold - is this still an issue?

**Comment by orbitfold** [comment]
No, we can close it.

On Mon, Nov 30, 2015 at 4:33 PM, unoebauer <notifications@github.com> wrote:

> @orbitfold <https://github.com/orbitfold> - is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tardis-sn/tardis/issues/140#issuecomment-160646621>.
>



-- 
"Cheshire-Puss," she began, "would you tell me, please,
which way I ought to go from here?"
"That depends a good deal on where you want to get to," said the Cat.
"I don't care much where--" said Alice.
"Then it doesn't matter which way you go," said the Cat.
