### ISSUE TITLE
automatically change copyright year in docs

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/tardis#1401]
Just like the Carsus site: https://tardis-sn.github.io/carsus

**Comment by DhruvSondhi** [comment]
Hello, 
I am new in this repository & while browsing through the issues found this ... Can you please specify some more information so that I can work on it if that's not a problem ?

**Comment by epassaro** [comment]
Look at the `carsus` package https://github.com/tardis-sn/carsus.

**Comment by DhruvSondhi** [comment]
Yes it does show 
![image](https://user-images.githubusercontent.com/66117751/103297521-7d80cf00-4a1e-11eb-9971-e46be3bab3eb.png)

so we should update it to 2021 ? 
Any main points to look out for would be much appreciated :smile:

**Comment by DhruvSondhi** [comment]
But upon searching in `Tardis` Main Package ... Copyright year is 2013

**Comment by epassaro** [comment]
There's a way to automatically update the copyright year, I suggest start reading about how the `sphinx` package work. `carsus` already has this feature, noo need to update there.

**Comment by DhruvSondhi** [comment]
The documentation build is failing. I have changed the code for sphinx to accommodate for the automatic changing of the year. Shall I make a Draft PR & you may look into the issue? Or is there anything that I am doing wrong such that the documentation is not being built?

**Comment by DhruvSondhi** [comment]
> The documentation build is failing. I have changed the code for sphinx to accommodate for the automatic changing of the year. Shall I make a Draft PR & you may look into the issue? Or is there anything that I am doing wrong such that the documentation is not being built?

Fixed it ... Made a new development environment so that the dependencies may not be a bottleneck for the building of the documentation. It's building now ... checking for the changes & making a PR for the same :smile:

**Comment by DhruvSondhi** [comment]
Please review #1404. Do suggest if any other changes are required to be done:smile:

**Comment by DhruvSondhi** [comment]
Updated the PR for the corresponding addition. 
Please check & let me know anything else can be done. Would be trying to solve other issues as well :smile:

**Comment by epassaro** [comment]
Closed by #1404
