### ISSUE TITLE
Tardis Example YML link fails in Quickstart

### ISSUE THREAD

**Issue by marxwillia** [tardis-sn/tardis#1407]
Currently the link in the docs Quickstart to the TARDIS example yml file fails.  The current link is: 

https://https//raw.githubusercontent.com/tardis-sn/tardis/master/docs/using/components/models/examples/tardis_example.yml

And I believe that the link should be:

https://raw.githubusercontent.com/tardis-sn/tardis/master/docs/using/components/models/examples/tardis_example.yml

**Comment by DhruvSondhi** [comment]
Hello, Yes while I was reading the quickstart guide I saw this error. Thought that it was something odd but never mind as the issue is evident & open. If its possible can, I make a fix for the same?

**Comment by nikki1234567** [comment]
Hello, I am Nikhilesh. I am new to open source and want to be a open source contributor can I work on this issue?

**Comment by andrewfullard** [comment]
> 
> 
> Hello, I am Nikhilesh. I am new to open source and want to be a open source contributor can I work on this issue?

All issues are open to be worked on

**Comment by himanshu007-creator** [comment]
> Currently the link in the docs Quickstart to the TARDIS example yml file fails. The current link is:
> 
> https://https//raw.githubusercontent.com/tardis-sn/tardis/master/docs/using/components/models/examples/tardis_example.yml
> 
> And I believe that the link should be:
> 
> https://raw.githubusercontent.com/tardis-sn/tardis/master/docs/using/components/models/examples/tardis_example.yml

I fixed this issue.https://github.com/tardis-sn/tardis/pull/1413
