### ISSUE TITLE
t_rad data are missing in the kurucz_cd23_chianti_H_He.h5 file

### ISSUE THREAD

**Issue by mklauser** [tardis-sn/tardis#141]
The current version of TARDIS complains about the missing t_rad data in the atomic data file kurucz_cd23_chianti_H_He.h5. Since the zeta_data are included in the atomic data, we should also add the t_rads to the data.

**Comment by unoebauer** [comment]
Never heard of this issue again - given the lack of interest and activity I am closing this issue. @wkerzendorf, @ssim: Re-open if you disagree.
