### ISSUE TITLE
Add black to tardis environment YML

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#1411]
#### Problem description

Now that `black` is automatically applied to authored code, this is not a required step, but it is useful for contributors to see what `black` will do to their code locally. See also PR #1405

**Comment by epassaro** [comment]
Black is already in the [environment file](https://github.com/tardis-sn/tardis/blob/f2e82f8895143f3cf24a4546d893fdaa3003cc85/tardis_env3.yml#L68).
