### ISSUE TITLE
coverage failing too often

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/tardis#1419]
## Description

Coverage check fails too often, even when only configuration files are changed, for example: 

- https://github.com/tardis-sn/tardis/pull/1415#partial-pull-merging
- more examples coming...

Probably this can be fixed modifying `.coveragerc`.

**Comment by jaladh-singhal** [comment]
Another example: https://github.com/tardis-sn/tardis/pull/1421#issuecomment-767049548

**Comment by smithis7** [comment]
> Another example: [#1421 (comment)](https://github.com/tardis-sn/tardis/pull/1421#issuecomment-767049548)
#1403 had the same issue as well.
