### ISSUE TITLE
Incorporate the old physics section of the documentation

### ISSUE THREAD

**Issue by smithis7** [tardis-sn/tardis#1422]
#### Problem description
We would like to incorporate the old physics section of the documentation into the newer physics section.

#### Expected Output
Currently, the old physics section contains two files of interest: ```docs/physics/old_physics/montecarlo_old.rst``` and ```docs/physics/old_physics/old_plasma.rst```. The following changes need to occur:
- Make sure all important information in ```docs/physics/old_physics/montecarlo_old.rst``` is included within ```docs/physics/montecarlo/```.
- Make sure all important information in ```docs/physics/old_physics/old_plasma.rst``` is included within ```docs/physics/plasma/```.
- Delete ```docs/physics/old_physics/``` and remove it from the toctree in ```docs/index.rst```.
- Make sure any hyperlinks referencing a document in ```docs/physics/old_physics/``` is changed to reference the appropriate still existing document.

**Comment by jaladh-singhal** [comment]
@marxwillia now that @smithis7 has laid out all the steps, it can be done quickly.

**Comment by smithis7** [comment]
> @marxwillia now that @smithis7 has laid out all the steps, it can be done quickly.

Just to note (for @marxwillia ), you may want to wait for #1421 to be merged (which should hopefully happen today) before working on this.
