### ISSUE TITLE
Need formal integral test for C code to compare new Numba code to

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#1448]
This needs to almost certainly be the formal integral output from a standard TARDIS input file. Then we can run a residuals comparison with the Numba version to make sure it's close enough (where close enough is probably less than 1% difference in results)

**Comment by andrewfullard** [comment]
This needs to become part of the refdata as well, probably

**Comment by karban8** [comment]
Hi, I would like to work on this issue. What I infer from the description is that I need to plot the spectrum using formal integral method as given[ here](https://tardis-sn.github.io/tardis/using/interaction/using_formal_integral.html) and compare the results obtained by running the new numba code. Also the results must be within 1% variation. Please guide me further

**Comment by andrewfullard** [comment]
That is one possibility. It is currently accomplished in the workflow here: https://github.com/tardis-sn/tardis/blob/master/azure-pipelines/compare-refdata.yml (you can see a result here #1467 )

The other method is to follow #1499 and work with @aribalam regarding it.

**Comment by andrewfullard** [comment]
This has been at least partially fixed
