### ISSUE TITLE
Kernel crashes when nthreads > 1

### ISSUE THREAD

**Issue by ycamacho** [tardis-sn/tardis#1449]
#### Problem description

If the .yml input file has 
montecarlo:
  nthreads: >1

the jupyter notebook kernel crashes with error

python(77911,0x70000d4e5000) malloc: double free for ptr 0x7ff487819400
python(77911,0x70000d4e5000) malloc: *** set a breakpoint in malloc_error_break to debug
[I 09:05:07.135 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports

#### Expected Output

If nthreads parameter is set to 1 or removed (default is 1), then tardis works.

**Comment by jaladh-singhal** [comment]
I can confirm, that's the same case with me. Thank you for creating issue @ycamacho - I almost forgot to create one.

**Comment by MarkMageeAstro** [comment]
Another confirmation, this is happening to me too.

**Comment by andrewfullard** [comment]
I can't reproduce this with e.g. tardis_example.yml with nthreads > 1. Is this still occurring?

**Comment by andrewfullard** [comment]
To update the issue: this occurs when vpacket logging is turned on with nthreads > 1. A fix is being worked on.
