### ISSUE TITLE
Simulation.to_hdf fails to save simulation objects

### ISSUE THREAD

**Issue by Rodot-** [tardis-sn/tardis#1452]
#### Code Sample, a copy-pastable example if possible

```
sim = run_tardis(...)
sim.to_hdf("filename.h5")
```
#### Problem description
Creates the file then fails with an error claiming the file cannot be overwritten

**Comment by epassaro** [comment]
@jaladh-singhal added a parameter `overwrite=False` recently

**Comment by jaladh-singhal** [comment]
@Rodot- I second what @epassaro mentioned. Can you post error log?

AFAIR the error not just claims that file cannot be overwritten (because it already exists) but also **tell** that you need to set `overwrite=True` if you want to overwrite it.

**Comment by jaladh-singhal** [comment]
@Rodot- closing this since this isn't a bug. If you still face problems let me know by commenting below.
