### ISSUE TITLE
sim.runner.spectrum_integrated doesn't work when spectrum: integrated: interpolate_shells: > 0

### ISSUE THREAD

**Issue by ycamacho** [tardis-sn/tardis#1463]
#### Problem description

When interpolate_shells: > 0 in input yml file sim.runner.spectrum_integrated results in following error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-4d322c8a718a> in <module>()
----> 1 sim24.runner.spectrum_integrated

/Users/yssavo/Documents/GitHub/tardis/tardis/montecarlo/base.py in spectrum_integrated(self)
    233         if self._spectrum_integrated is None:
    234             self._spectrum_integrated = self.integrator.calculate_spectrum(
--> 235                 self.spectrum_frequency[:-1], **self.integrator_settings
    236             )
    237         return self._spectrum_integrated

/Users/yssavo/Documents/GitHub/tardis/tardis/montecarlo/formal_integral.py in calculate_spectrum(self, frequency, points, interpolate_shells, raises)
     94         self.interpolate_shells = interpolate_shells
     95         frequency = frequency.to("Hz", u.spectral())
---> 96         luminosity = u.Quantity(formal_integral(self, frequency, N), "erg") * (
     97             frequency[1] - frequency[0]
     98         )

/Users/yssavo/Documents/GitHub/tardis/tardis/montecarlo/montecarlo.pyx in tardis.montecarlo.montecarlo.formal_integral()

AttributeError: 'numpy.ndarray' object has no attribute 'values'

#### Expected Output

Formal integral should work when interpolate_shells: > 0

Issue is occurring because sim.runner.electron_densities_integ is a numpy array instead of a pandas series. Fix needs to occur in tardis/tardis/montecarlo/formal_integral.py line 253

**Comment by ycamacho** [comment]
@chvogl This issue seems to have occurred during your PR 1358 https://github.com/tardis-sn/tardis/pull/1358

**Comment by chvogl** [comment]
Yes, this was a relatively stupid error on my part. Thanks for fixing it @Rodot. The problem should be resolved through the merge of PR #1464.

**Comment by chvogl** [comment]
I am closing this for now.
