### ISSUE TITLE
Combine elements from absorption AND emission components

### ISSUE THREAD

**Issue by marxwillia** [tardis-sn/tardis#1468]
There is a problem with the SDEC plot when the user specifies a wavelength range.  Currently, the elements list is determined only by looking at the elements in the emission part.  However, it is possible that the user could specify a wavelength range where an element is very important for absorption, but does not appear in the emission.  In this case, the element would not be plotted in the absorption part of the spectrum.

This will be fixed as part of the planned nelements update.

The code works fine as long the wavelength range is not specified, and instead the user changes the wavelength range plotted after the plot is generated.

**Comment by jaladh-singhal** [comment]
@MarkMageeAstro @jamesgillanders I think this is fixed by now - can we close this?

**Comment by jamesgillanders** [comment]
is this just the same as issue #1516 ? If so, then yes we can close it

**Comment by MarkMageeAstro** [comment]
Yes, this should be fixed now.
