### ISSUE TITLE
python setup.py install giving error

### ISSUE THREAD

**Issue by guptadhaval18** [tardis-sn/tardis#1475]
after forking and downloading the repository. I created a new environment in conda to install python. After that I changed directory to tardis-master. Then I ran python setup.py install. Which gave error as shown below.
![image](https://user-images.githubusercontent.com/47078156/110996944-b20bf200-83a2-11eb-89d0-8ade25b7e14f.png)

**Comment by epassaro** [comment]
Please try `python setup.py clean` and then `git clean -dfx` and install again.

**Comment by guptadhaval18** [comment]
@epassaro thanks for replying. But this doesn't solve the problem. Same error.

**Comment by epassaro** [comment]
Try `python setup.py develop` instead. If that's fails, delete your environment and start again.

**Comment by guptadhaval18** [comment]
Still failing. Tried using both python 3.6 and 3.8. Can it be due to using conda env?

**Comment by epassaro** [comment]
The provided conda environment file should work without any modification.

**Comment by Davidgokimmung** [comment]
you need to run tardis_env3.yml inside anaconda, and then run the command `conda env create -f tardis_env3.yml` there.

**Comment by yuyizheng1112** [comment]
Hi, have you resolved the problem?

**Comment by andrewfullard** [comment]
Closing due to lack of communication
