### ISSUE TITLE
No module named 'tardis.montecarlo.montecarlo'

### ISSUE THREAD

**Issue by dhiganthrao** [tardis-sn/tardis#1482]
Greetings! While trying to execute cells in the notebook mentioned in the [Quickstart](https://tardis-sn.github.io/tardis/quickstart/quickstart.html) page, I face a problem:
#### Code Sample, a copy-pastable example if possible

```python
sim = run_tardis('tardis_example.yml')
```
#### Problem description

On running the code above, I run into an error which says `ModuleNotFoundError: No module named 'tardis.montecarlo.montecarlo'`

#### Expected Output
```python
INFO:tardis.simulation.base:Simulation finished in 20 iterations and took 47.87 s
```
I have just attached the last line of the output as shown in the Quickstart page.
On searching for the solution, I came across issue #1148 and issue #1480 . However, the solution to issue #1148 did not resolve my problem. 
I have installed tardis using the commands as specified from the [Installation](https://tardis-sn.github.io/tardis/installation.html):
`
git clone https://github.com/tardis-sn/tardis.git
cd tardis
python setup.py install
`
The only changes I have made are using JupyterLab instead of Jupyter Notebook, and changing the download path specified in 
`~/.astropy/config/tardis_internal_config.yml`. 
What could be the cause of this problem? Apologies if the solution is very easy, but I could not get this to work.
For reference, I have attached the entire output here:
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-1a68e481065f> in <module>
      1 #TARDIS now uses the data in the data repo
----> 2 sim = run_tardis('tardis_example.yml')

~/tardis/tardis/base.py in run_tardis(config, atom_data, packet_source, simulation_callbacks)
     23     from tardis.io.config_reader import Configuration
     24     from tardis.io.atom_data.base import AtomData
---> 25     from tardis.simulation import Simulation
     26 
     27     if atom_data is not None:

~/tardis/tardis/simulation/__init__.py in <module>
----> 1 from tardis.simulation.base import Simulation

~/tardis/tardis/simulation/base.py in <module>
      6 from collections import OrderedDict
      7 
----> 8 from tardis.montecarlo import MontecarloRunner
      9 from tardis.model import Radial1DModel
     10 from tardis.plasma.standard_plasmas import assemble_plasma

~/tardis/tardis/montecarlo/__init__.py in <module>
----> 1 from tardis.montecarlo.base import *

~/tardis/tardis/montecarlo/base.py in <module>
     13 from tardis.io.util import HDFWriterMixin
     14 from tardis.montecarlo import packet_source as source
---> 15 from tardis.montecarlo.formal_integral import FormalIntegrator
     16 from tardis.montecarlo import montecarlo_configuration as mc_config_module
     17 

~/tardis/tardis/montecarlo/formal_integral.py in <module>
     15 )
     16 
---> 17 from tardis.montecarlo.montecarlo import formal_integral
     18 from tardis.montecarlo.spectrum import TARDISSpectrum
     19 

ModuleNotFoundError: No module named 'tardis.montecarlo.montecarlo'
```

**Comment by dhiganthrao** [comment]
Apologies for creating a duplicate issue! I just realized I could comment on the issue that was already open 😅. However, I came across a fix for this problem; I simply went into `~/tardis/tardis/montecarlo/formal_integral.py` and imported `formal_integral` from `tardis.montecarlo` instead of `tardis.montecarlo.montecarlo` (effectively removing the extra word). This worked for me, and I received the following output:
```python
[tardis.simulation.base][INFO   ]  Simulation finished in 20 iterations and took 56.61 s (base.py:381)
```
However, I now run into another problem: While executing the next cell (shown below), I receive the following error:
Cell:
```python
%pylab inline

spectrum = sim.runner.spectrum
spectrum_virtual = sim.runner.spectrum_virtual
spectrum_integrated = sim.runner.spectrum_integrated

figure(figsize=(10,6))
plot(spectrum.wavelength, spectrum.luminosity_density_lambda, label='normal packets')
plot(spectrum.wavelength, spectrum_virtual.luminosity_density_lambda, label='virtual packets')
plot(spectrum.wavelength, spectrum_integrated.luminosity_density_lambda, label='formal integral')
xlabel('Wavelength [$\AA$]')
ylabel('Luminosity [erg/s/$\AA$]')
legend()
xlim(3000, 9000)
```

Output:
```python
Populating the interactive namespace from numpy and matplotlib

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-88827dc9d765> in <module>
      3 spectrum = sim.runner.spectrum
      4 spectrum_virtual = sim.runner.spectrum_virtual
----> 5 spectrum_integrated = sim.runner.spectrum_integrated
      6 
      7 figure(figsize=(10,6))

~/tardis/tardis/montecarlo/base.py in spectrum_integrated(self)
    232     def spectrum_integrated(self):
    233         if self._spectrum_integrated is None:
--> 234             self._spectrum_integrated = self.integrator.calculate_spectrum(
    235                 self.spectrum_frequency[:-1], **self.integrator_settings
    236             )

~/tardis/tardis/montecarlo/formal_integral.py in calculate_spectrum(self, frequency, points, interpolate_shells, raises)
     95         self.interpolate_shells = interpolate_shells
     96         frequency = frequency.to("Hz", u.spectral())
---> 97         luminosity = u.Quantity(formal_integral(self, frequency, N), "erg") * (
     98             frequency[1] - frequency[0]
     99         )

TypeError: 'module' object is not callable
```
Is this somehow related to the change I made? And also, I realize that this comment is too big to include under a single issue; so, should I create a separate issue for this? Again, apologies for creating a duplicate issue.

**Comment by wkerzendorf** [comment]
I presume you are in the cloned repository. leave that directory and run it from somewhere else.

**Comment by dhiganthrao** [comment]
Oh! Thank you so much, that worked! Sorry for the extensive lines of code, should've just tried that in the first place 😅

**Comment by antreev-brar** [comment]
@dhiganthrao you should close this issue since it is resolved

**Comment by dhiganthrao** [comment]
Oops, forgot to do so! Thanks for the reminder!

**Comment by NJI-CHE** [comment]
Hello @dhiganthrao. please how did you leave the cloned repository and a run it else where as @wkerzendorf  said in order to run the plot the spectrum??
