### ISSUE TITLE
Axis Labels Not Parsing Correctly in SDEC Plot via Plotly 

### ISSUE THREAD

**Issue by DhruvSondhi** [tardis-sn/tardis#1485]
#### Problem description
The axis labels in SDEC plots made with `plotly` are not being parsed correctly. This can be seen in the docs [here](https://tardis-sn.github.io/tardis/using/visualization/sdec_plot.html#id1). 
Attaching screenshot as applicable:
![image](https://user-images.githubusercontent.com/66117751/111259500-059d6a80-8645-11eb-9608-4dff51b0a2c1.png)
I ran the notebook & the example on my local machine & it was working as intended ... I think we need to re-run the notebooks in docs to check if this is a problem for the parsing or native function definition problem. 

#### Expected Output
The axis needs to be parsed correctly as shown :
![image](https://user-images.githubusercontent.com/66117751/111259668-6462e400-8645-11eb-8eb0-e9a3c998fc48.png)

Please confirm the same & hence if it is a problem I would like to help in fixing it 😄

**Comment by andrewfullard** [comment]
This is definitely an issue and should be fixed!

**Comment by DhruvSondhi** [comment]
Hello @andrewfullard, I can re-run the notebook on my local environment & generate the output that way ... After that I can commit the changes for the notebook directly 😄

**Comment by jaladh-singhal** [comment]
> Hello @andrewfullard, I can re-run the notebook on my local environment & generate the output that way ... After that I can commit the changes for the notebook directly

@DhruvSondhi go ahead and make a PR

**Comment by DhruvSondhi** [comment]
Hey @jaladh-singhal ... Where can I find the `demo.hdf` data for `hdf_plotter` [here](https://tardis-sn.github.io/tardis/using/visualization/sdec_plot.html#Using-simulation-saved-as-HDF)? 🤔
