### ISSUE TITLE
Hyperlink not working on a Documentation Page

### ISSUE THREAD

**Issue by karban8** [tardis-sn/tardis#1500]
#### Problem description
The[ Generating TARDIS Widgets](https://tardis-sn.github.io/tardis/using/visualization/generating_widgets.html) page in the documentation has a hyperlink [Using TARDIS Widgets](https://tardis-sn.github.io/tardis/running/tardis_widgets/using_widgets.html) which shows a file not found 404 error upon clicking.
Please confirm if others are also experiencing the same problem.If so then I would be happy to resolve it.
#### Expected Output
It should be correctly linked to this [webpage](https://tardis-sn.github.io/tardis/using/visualization/using_widgets.html).

**Comment by KevinCawley** [comment]
Thanks for pointing this out, I'll fix this.
