### ISSUE TITLE
Sidebar of docs has buggy layout

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1522]
Somehow layout of TARDIS Docs sidebar has changed:
![image](https://user-images.githubusercontent.com/36361463/113608735-8f4ebf80-9668-11eb-878c-3d91006a2c6e.png)

- The headings like "Using TARDIS", "Physics of TARDIS", etc. are now in grey that used to be in blue. 
- These headings are sticking to left side of browser window - the left margin that used to be there is missing
- The vertical margins around headings are also weird - there's no top margin and extra bottom margin

## Pointers to debug
- Search if there's latest release in RTD-theme which introduced this bug for projects like TARDIS using certain config settings
- Search since which commit in TARDIS codebase this buggy layout has been introduced
- Probably, this can be fixed by writing custom css

**Comment by smithis7** [comment]
See https://github.com/sphinx-doc/sphinx/issues/9051 and https://github.com/sphinx-doc/sphinx/pull/9053. This is not just us with this problem.
