### ISSUE TITLE
config validator documentation cleanup

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#155]
the documentation page:

http://tardis.readthedocs.org/en/latest/configuration/config_validator.html

should be cleaned up and language clarified for the general user (or made clear that these are details for the developers to worry about only)

**Comment by unoebauer** [comment]
@ssim: status of this issue? My suspicion is that it hasn't progressed very much, being a documentation issue...

**Comment by unoebauer** [comment]
The file ``config_validator.rst`` has not been modified since this issue has been filed. Thus, this issue is still relevant.

**Comment by unoebauer** [comment]
The configuration validator scheme has changed in the course of GSOC 2016. Closing
