### ISSUE TITLE
default config file in documentation

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#156]
This documentation page:

http://tardis.readthedocs.org/en/latest/configuration/configuration.html

needs a pre-able explaining why this is there and what we are using it for

**Comment by unoebauer** [comment]
This is still relevant! Somebody just has to find some time to do it...(easier said than done)

**Comment by souravsingh** [comment]
I would like to work on it

**Comment by unoebauer** [comment]
Closing - will aggregate documentation issues in a TEP
