### ISSUE TITLE
Moving Config File Under `docs/`

### ISSUE THREAD

**Issue by smithis7** [tardis-sn/tardis#1561]
**Is your feature request related to a problem? Please describe.**
As mentioned in #1478 the example configuration file is fairly difficult to find. It is currently in `docs/using/components/models/examples/tardis_example.yml`. We only keep one real copy of the file, and the rest of the time we use symlinks to reference the file.

**Describe the solution you'd like**
We would like to have to have the real copy in an easier location to access, perhaps just under `docs/`. This involves:
- Moving the real copy of the file.
- Adding a symlink to `docs/using/components/models/examples/`.
- Updating all of the other symlinks in the documentation to reflect the new location of the real copy.

**Comment by parikshit14** [comment]
Can I work on this as well?
