### ISSUE TITLE
SDEC plotly graphs not showing in the documentation

### ISSUE THREAD

**Issue by atharva-2001** [tardis-sn/tardis#1585]
**Describe the bug**

SDEC plotly graphs are not visible in the documentation and are replaced by blank spaces. They are visible locally, however. 

**To Reproduce**

[Link to the documentation](https://tardis-sn.github.io/tardis/using/visualization/sdec_plot.html)

**Screenshots**

![image](https://user-images.githubusercontent.com/55894364/119317777-1b0ec080-bc96-11eb-882c-ae3bf0f298ac.png)

Plots are visible locally: 
![image](https://user-images.githubusercontent.com/55894364/119316964-3927f100-bc95-11eb-978b-18625aa2c334.png)

**System**
 - OS:
    - [X] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by Molkree** [comment]
Works for me (even with these errors):

![image](https://user-images.githubusercontent.com/12860284/119369719-275a4400-bcbd-11eb-9da8-163aefb8c0d0.png)

**Comment by atharva-2001** [comment]
Oh no, the matplotlib charts show up just fine. I meant the plotly charts. Are they visible to you?

**Comment by Molkree** [comment]
Oh, you are right, my mistake, the same name of the heading confused me. Yes, they are not rendering.

**Comment by DhruvSondhi** [comment]
Hey @atharva-2001, I think so this is a bug from the recent building of the documentation ... I am using Firefox & the documentation is being built correctly (tested using different branches locally) ... Sharing a Screenshot for the same:
Virtual Packets Mode :-
![image](https://user-images.githubusercontent.com/66117751/119449184-f119d480-bd4f-11eb-8213-5647699a0f86.png)

Plotting a Specific Wavelength Range :-
![image](https://user-images.githubusercontent.com/66117751/119449193-f70fb580-bd4f-11eb-9efa-c9cefba9ad28.png)

**Comment by atharva-2001** [comment]
This issue is tracked here https://github.com/spatialaudio/nbsphinx/issues/572
