### ISSUE TITLE
Pull Request & Issue Templates needs to be Updated 

### ISSUE THREAD

**Issue by DhruvSondhi** [tardis-sn/tardis#1587]
**Describe the bug**

Currently, the PR templates have a checklist for all the task that needs to be done in order for the PR to be in a mergeable state. But the following checkbox `- [x] I have assigned and requested two reviewers for this pull request` cannot be done by New Contributors who are not a part of the TARDIS Organisation.
The Issue Template also requires a small Update as it is old 

**Screenshots**

Pull Request Checklist
![image](https://user-images.githubusercontent.com/66117751/119455567-58875280-bd57-11eb-96b2-3a49671ecf67.png)

Issue Template
![image](https://user-images.githubusercontent.com/66117751/119455517-4c9b9080-bd57-11eb-9a74-8268e9daa757.png)

**System**
 - OS:
    - [x] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

The Pull Request Template requires removal of the checklist & updating regarding the same with something that can be done by a new contributor such as requesting review by tagging relevant person (needs a better explanation for the heads of the teams [here](https://tardis-sn.github.io/tardis/team_and_governance/team.html))
The Issue Template can also see some updates on the same lines 😄 

**Note :** The Templates are present [here](https://github.com/tardis-sn/.github)

**Comment by ahcodes** [comment]
Hi, I'm willing to work on this issue, but I would need some guidance since I'm a newbie.

**Comment by DhruvSondhi** [comment]
Hello @ahcodes, sure you can work on this issue. Feel free to message your queries here or ping me 👍🏼
