### ISSUE TITLE
Make a script that decays an abundance file

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#159]
Make script that will take a tardis abundance file and a day after explosion and decays the abundances

PR #409 is a prototype implementation of this feature request.

**Comment by unoebauer** [comment]
@wkerzendorf, @ssim  - status of this? From what I understand this is still work in progress, right? Would be really useful to have this capability (especially for our tomography projects - currently we are doing this by hand).

**Comment by wkerzendorf** [comment]
I updated the text.

**Comment by unoebauer** [comment]
Thanks - let's leave this issue open until PR #409 has found it's way into the master.

**Comment by unoebauer** [comment]
Thanks to @vg3095 no longer an issue.
