### ISSUE TITLE
Installation Instructions on the Documentation are Outdated 

### ISSUE THREAD

**Issue by DhruvSondhi** [tardis-sn/tardis#1591]
**Describe the bug**

The current instructions for installation of TARDIS package are old are outdated & needs to be updated.
These can be seen [here](https://tardis-sn.github.io/tardis/installation.html#installation-troubles-faq)
Some potential changes may include TARDIS not supporting Python 2.7, changes for the sphinx builds etc. 

**System**
 - OS:
    - [x] GNU/Linux
    - [ ] macOS

**Comment by smithis7** [comment]
This is being worked on by one of our highschool students!
