### ISSUE TITLE
Issue creating new TARDIS env (pyside2)

### ISSUE THREAD

**Issue by jamesgillanders** [tardis-sn/tardis#1608]
**Describe the bug**
When creating a new TARDIS environment, the most up-to-date version of pyside2, which downloads as default, gives the following error when trying to plot output spectra after a simulation:

This application failed to start because it could not find or load the Qt platform plugin "cocoa" in "".

**To Reproduce**
git clone git@github.com:jamesgillanders/tardis.git
cd tardis/
git remote add upstream git://github.com/tardis-sn/tardis.git
conda env create -f tardis_env3.yml
conda activate tardis
python setup.py develop

Then run any TARDIS model + try to plot output spectrum

**Screenshots**

**System**
 - OS:
    - [ ] GNU/Linux
    - [*] macOS

 - Environment (`conda list`):
[conda_list.txt](https://github.com/tardis-sn/tardis/files/6592407/conda_list.txt)

**Additional context**
Problem can be resolved by rolling back the version of pyside2 used, from 5.13.2 --> 5.9

**Comment by epassaro** [comment]
I couldn't reproduce your issue in the pipelines. Did you checked out to `upstream/master` before creating the env?

**Comment by epassaro** [comment]
OK, I think your steps to reproduce the error are not ok, but you are using the `tardis_env3.yml` from upstream effectively. I thought `pyside2` was using just for the Qt GUI but I'm not sure.

You can try to comment out `pyside2` from the env before installing and see. Then we can decide if we downgrade `pyside2` or just  comment out from the env (people should install it manually if they want to use the Qt GUI).

**Comment by jamesgillanders** [comment]
Apologies if the steps weren't clear!

**Comment by jamesgillanders** [comment]
I'm not sure why it's throwing an error either, but perhaps removing it entirely would be sensible - I'll try a test to see how that works and be back in touch, thanks

**Comment by epassaro** [comment]
I don't know why this happened recently because the latest `pyside2` in conda-forge release was made 5 months ago.

This is going to be closed soon by #1652
