### ISSUE TITLE
Discussion about Github PR Review Checklist Comment Bot

### ISSUE THREAD

**Issue by DhruvSondhi** [tardis-sn/tardis#1620]
**Describe the Problem**
We had implemented the GH Bot for commenting a PR Review Checklist for each commit that is pushed on a branch. Due its repetitive nature, the bot is currently being disabled in #1619. We need to have a better structure for the Checklist that needs to be presented on the PR. It could be structured in a way for the Reviewer to have a number of things to lookout in the code changes before merging. Also, having it comment only once on the PR makes it way better in situations where a lot of commits have been pushed. Please do suggest the things that could be present in the checklist so that it adds to the review process.

**Comment by epassaro** [comment]
I think we should repurpose that workflow. 

Why do we want the bot commenting our PRs? The original idea overlaps with the PR template and seems redundant.

A new implementation could be, for example, making the bot posting some warning message when someone push changes to important files such as `tardis_env3.yml` or the Astropy package template files (`setup.py`, etc). Or detect if changes were made to `docs/` and suggest how to run the documentation preview, etc.
