### ISSUE TITLE
to_hdf() failed for Simulation object

### ISSUE THREAD

**Issue by yuyizheng1112** [tardis-sn/tardis#1624]
**Describe the bug**

`to_hdf()` doesn't work when called by a Simulation object. A `FileExistsError` is raised though there was no such file before running.

The bug might be here:
https://github.com/tardis-sn/tardis/blob/8ac89320d50561647399ee35c84d6ec8f3b55cf0/tardis/io/util.py#L233-L247
`buf = pd.HDFStore(path_or_buf, complevel=complevel, complib=complib)`in `try` block will create the HDF file. Therefore, FileExistsError will be definitely raised if `overwrite=False` while running `else` block.

**To Reproduce**

Follow the instruction in the documentation [here](https://tardis-sn.github.io/tardis/using/interaction/to_hdf_notebook.html#to-hdf-notebook).

**Screenshots**

![image](https://user-images.githubusercontent.com/80535029/120952354-6c7e7b80-c77d-11eb-93d2-2f6ebc725fc0.png)

**System**
 - OS:
    - [ ] GNU/Linux
    - [x] macOS

**Comment by Rodot-** [comment]
It looks like it is creating the file before checking if the file exists, a simple rearrangement for rectify this issue.
