### ISSUE TITLE
Replace PyNE Usage

### ISSUE THREAD

**Issue by lemointm** [tardis-sn/tardis#1654]
TARDIS currently uses the [PyNE](https://github.com/pyne/pyne) nuclear engineering package to parse isotope names and to calculate decay abundances of radioactive elements in the simulated supernova ejecta. However, PyNE is largely written in C++, which has created some stability issues in TARDIS.

We hope to create the relevant custom modules or find an existing package to replace the PyNE functionality in TARDIS.

The [radioactivedecay](https://alexmalins.com/radioactivedecay/) package is an existing code which calculates the activity of the elements of a specific decay chain after a certain amount of time has passed. With further edits to increase functionality to include abundances, this package could serve as a simple and reliable PyNE replacement for calculating decay abundances.

Tags: @epassaro @wkerzendorf

**Comment by andrewfullard** [comment]
PyNE is used in Tardis to:

1. translate nuclide names from element symbols
2. create data frames of PyNE materials that can be decayed over a period of time

**Comment by epassaro** [comment]
Also related to: https://github.com/tardis-sn/tardis/issues/1537
