### ISSUE TITLE
Updating Documentation for Testing via `tardis-refdata`  

### ISSUE THREAD

**Issue by DhruvSondhi** [tardis-sn/tardis#1655]
**Describe the bug**

Currently, the testing documentation is a bit outdated & doesn't specify the correct way to setup the testing environment for TARDIS testing suite. 
We need to update the documentation with better explaination & examples. For example, `git lfs` needs to mentioned in the documentation so that `tardis-refdata` can be downloaded correctly (I had problems with downloading `tardis-refdata` for testing). 
Better explaination for Pytest flags would also enhance the quality for this part of the documentation. 
Similar thing must be down with `tardis-refdata` & the `README` for the same must specify that the repository is a `git lfs` repository & the instructions for using the same.

**Comment by andrewfullard** [comment]
Deprecated with move to regression-data. See also #1258
