### ISSUE TITLE
Outdated code in to_hdf notebook

### ISSUE THREAD

**Issue by atharva-2001** [tardis-sn/tardis#1669]
**Describe the bug**

The code in the to_hdf notebook is outdated. The print statements are written in Python 2 syntax and it seems the code doesn't display what it is supposed to display when it's run. Maybe we can change this according to the new syntax?

**To Reproduce**

[Link](https://tardis-sn.github.io/tardis/io/output/to_hdf_notebook.html) to the notebook.

**Screenshots**

![image](https://user-images.githubusercontent.com/55894364/123550315-a3e3b500-d78a-11eb-835a-dda3693e20ee.png)

**System**
 - OS:
    - [X] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by epassaro** [comment]
I think using `print` to display Series or DataFrames in notebooks is redundant.

**Comment by atharva-2001** [comment]
@smithis7, Since the notebook I am talking about here, was replaced by a [new notebook](https://tardis-sn.github.io/tardis/io/output/to_hdf.html)(many thanks to your PR https://github.com/tardis-sn/tardis/pull/1763), can we close this issue?

**Comment by smithis7** [comment]
Yeah, I didn't notice this issue before, I should have closed it with my PR that fixed it 😅
