### ISSUE TITLE
Inconsistent use of astropy and tardis constants

### ISSUE THREAD

**Issue by chvogl** [tardis-sn/tardis#1672]
**Describe the bug**
TARDIS uses a specific version of astropy constants (astropy.constants.astropy13constants).
The intended way to import these constants is: `from tardis import constants as const`. However, this is currently not done everywhere in the code (see e.g. https://github.com/tardis-sn/tardis/blob/master/tardis/simulation/base.py).

**Comment by shilpiprd** [comment]
from what i understand, you need all files to  import constants from tardis instead of 'astropy or anything else'. 
Is this correct?

**Comment by chvogl** [comment]
Yes, that's it!

**Comment by shilpiprd** [comment]
I've fixed this issue in PR: #1825 
Please review

**Comment by shilpiprd** [comment]
is the pr #1825 merged? How would I know? Can i close the pr?
