### ISSUE TITLE
Convert Old Python 2 String formatting into Python 3

### ISSUE THREAD

**Issue by DhruvSondhi** [tardis-sn/tardis#1705]
**Describe the bug**

TARDIS Source code still contains python2 compliant formatted strings.
See for example [this](https://github.com/tardis-sn/tardis/blob/7d3899eda099b6d3aa170208f51ccf88eeaa48b7/tardis/io/parsers/csvy.py#L35)
This needs to be converted to Python 3 string formatting, preferably `f-string` formatting.

**Comment by svenkat19** [comment]
I would like to look into this.
