### ISSUE TITLE
Fix file paths in tests

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/tardis#1715]
**Describe the bug**

It's not possible to test the `tardis` package once installed by doing `pytest --pyargs tardis`. This happens because some `yml` have their paths hardcoded in the test files.

This is particularly important to test the conda-forge package release.

**To Reproduce**

`pytest --pyargs tardis`

See: https://docs.pytest.org/en/6.2.x/example/pythoncollection.html#interpreting-cmdline-arguments-as-python-packages

**Comment by rohithvarma3000** [comment]
@epassaro, I am not able to understand the exact issue. I can run the command without problems(except for some failing tests). Could you retry this command and let me know the error you are facing?

**Comment by andrewfullard** [comment]
Since we don't plan to keep supporting a conda package, this is no longer relevant
