### ISSUE TITLE
Documentation Main Page Unresponsive on Firefox 89.0.2

### ISSUE THREAD

**Issue by Rodot-** [tardis-sn/tardis#1717]
**Describe the bug**
Accessing https://tardis-sn.github.io/tardis causes the browser to slow to a crawl and use a large amount of CPU.  Tends to end with Firefox saying the page is unresponsive and asking to stop it.

**To Reproduce**
Access https://tardis-sn.github.io/tardis on Firefox 89.0.2 (possibly on other versions as well)

**Screenshots**

**System**
 - OS:
    - [x] GNU/Linux (Ubuntu 20.04.2 LTS x86_64, Linux 5.4.0-77-generic)
    - [ ] macOS

 - Environment (`conda list`):

**Comment by atharva-2001** [comment]
The link returns a 404 for me, maybe try this [link](https://tardis-sn.github.io/tardis/)?

**Comment by Rodot-** [comment]
Thanks, I've edited the issue
