### ISSUE TITLE
ci/cd status page

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/tardis#1749]
I would like to have a page in docs (or new main page?) summarizing the status of CI/CD pipelines like: https://conda-forge.org/status/

**Comment by smithis7** [comment]
Something under `developemtn/` maybe?

**Comment by Molkree** [comment]
Do you want something as simple as a collection of badges indicating if the workflow passes or not? Or something more advanced like on the linked conda-forge page?
Badges can be created very easily in the GitHub Action UI on each workflow's page:
![image](https://user-images.githubusercontent.com/12860284/130360635-4249678f-d5c8-426a-9009-6d422460ca1c.png)

For Azure something like [this](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/badge/get-build-badge-data?view=azure-devops-rest-6.0) should work?

**Comment by epassaro** [comment]
working on it https://epassaro.github.io/status

soon on https://tardis-sn.github.io/status


Closed.
