### ISSUE TITLE
Problem with reading the convergence section

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#176]
Many of our example have convergence_criteria - whereas now it should be called convergence-section. 
update.

**Comment by unoebauer** [comment]
What happened here? The milestone was set to v1.0 (which has been released a while ago...). Were all config files thoroughly checked and the proper names used in the v1.0 release, @wkerzendorf?

**Comment by unoebauer** [comment]
Just verified: all .yml files have the correct name for the convergence section in the current version, 86a7d958d9b328ae5da8baf886bbb9805565002e. Thus, closing this issue.
