### ISSUE TITLE
Enforce naming conventions of PEP8

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1762]
Currently we have no automated way to ensure that code being added follows PEP8 [naming conventions ](https://realpython.com/python-pep8/#naming-conventions) - like naming variables in snake case and only classes in captialized words, etc. A recent example of such violation is #1738 since it only depends on reviewers as of now.

Black (being an [autoformatter](https://realpython.com/python-pep8/#autoformatters)) only helps in PEP8 formatting conventions. For naming conventions we need a [linter](https://realpython.com/python-pep8/#linters) like flake8 that can point out any violations - we can create another PR check workflow for that.

Although we have to make sure that this linter plays together nicely with black becuase black is opinionated PEP8 formatter (i.e. it enforces one option in cases where PEP8 recommends >1 options of formatting)

**Comment by Molkree** [comment]
flake8 by itself won't be enough, but there's [pep8-naming](https://github.com/PyCQA/pep8-naming) plugin for flake8 and I think this is exactly what you are looking for.
