### ISSUE TITLE
Using built-in GitHub citation support

### ISSUE THREAD

**Issue by Molkree** [tardis-sn/tardis#1783]
**Is your feature request related to a problem? Please describe.**
Providing a standardised way of citing tardis-sn.

**Describe the solution you'd like**
Leverage built-in GitHub citing support by adding CITATION.cff file to the repository. [Announce](https://github.blog/2021-08-19-enhanced-support-citations-github/) of the feature, [docs](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files).

**Describe alternatives you've considered**
Keeping citation info only in [readme](https://github.com/tardis-sn/tardis/blob/575002cf8f01cce9182f9343b544bff70820ae16/README.rst), [tardis.bib](https://github.com/tardis-sn/tardis/blob/master/docs/tardis.bib) (and possibly other places that I missed).

**Additional context**
Here's how it will look if implemented:
![GitHub-citation-demo](https://user-images.githubusercontent.com/12860284/130353143-264a1721-911a-405b-8dc0-72c64cfa2c28.gif)

**Comment by epassaro** [comment]
Hi @Molkree! We are already working on how to implement this on the continuous delivery pipeline. Thanks!

**Comment by Molkree** [comment]
That's awesome! Can you provide a link to where this work happens? Or just link a PR to this issue when it's ready.

**Comment by epassaro** [comment]
This is already done in the post release workflow.

Closing.
