### ISSUE TITLE
Workflow to automatically comment documentation preview link on PRs

### ISSUE THREAD

**Issue by jaladh-singhal** [tardis-sn/tardis#1791]
- It should trigger (though only once) whenever documentation preview workflow triggers for a PR
- Should generate the documentation preview link (that can be created using same logic how docs-preview workflow does it ) and comment it on the PR

**Comment by epassaro** [comment]
I have a better documentation pipeline, see: https://github.com/epassaro/actions-rtd-workflow

**Comment by jaladh-singhal** [comment]
> I have a better documentation pipeline, see: https://github.com/epassaro/actions-rtd-workflow

@epassaro why haven't we adopted it in tardis?

**Comment by epassaro** [comment]
Mostly a matter of time, I submitted that to the GH Actions Hackathon last november

**Comment by epassaro** [comment]
Already implemented :)
