### ISSUE TITLE
TARDIS version 0.9 and 0.9.2 producing different results

### ISSUE THREAD

**Issue by sofiatti** [tardis-sn/tardis#181]
My new favorite SN is now 11FeM063 at 11.5 days since explosion. That's what the config files are for. The luminosity requested is the bolometric luminosity published at Rui et. al. table 2.

Config file for v.0.9: http://pastebin.com/XLAUg4Ef
Config file for v.0.9.2: http://pastebin.com/X7p08UF1
w7_sphere_abundance.dat: http://pastebin.com/QkDgFftB
w7_sphere_density.dat: http://pastebin.com/rqSdvvu2

**Comment by unoebauer** [comment]
Did anybody, @ssim, @wkerzendorf ever look into this? From the description above, it is not obvious to me whether the differences are actually worrisome or not. Moreover, the referenced Tardis versions are quite old... I am tempted to close this one.

**Comment by unoebauer** [comment]
FYI @ssim, @wkerzendorf: I am closing this, since the referenced Tardis versions are quite outdated. Reopen if you disagree
