### ISSUE TITLE
Kilonova-model crash when no recombination data available

### ISSUE THREAD

**Issue by gleck97** [tardis-sn/tardis#1829]
**Describe the bug**
The bug appears when trying to run a (kilonova) model where _only_ elements with atomic number Z > 28 are abundant and when using "nebular" and "dilute-lte" as ionization and excitation for the plasma state. In this case, TARDIS does not seem to find any recombination data (which so far seems to be provided up to Z = 28, see "knox_long_recombination_zeta.dat") and the model crashes when trying to compute the plasma state.

**To Reproduce**
As mentioned above, run a model using
1. only elements above Z = 28 (atomic data is also needed for them)
2. ionization: nebular
3. excitation: dilute-lte

in the config file.

**Additional context**
I created a branch for myself to work on this and found a way to solve this issue (see https://github.com/gleck97/tardis/blob/master/tardis/plasma/properties/ion_population.py in lines 166-183), but I would be happy to receive feedback or comments to improve on it and bring it up to the standard of the code as much as possible.

**Comment by chvogl** [comment]
Fixed with merge of #2150.
