### ISSUE TITLE
Wrong name for t_initial_rad in example config

### ISSUE THREAD

**Issue by mklauser** [tardis-sn/tardis#186]
In the example config file currently provided, the plasma parameter ```t_initial_rad``` contains a typo (right now it is ```t_initial_rads```)

**Comment by utkbansal** [comment]
Could you please provide the file path?

**Comment by kaushik94** [comment]
@mklauser  isn't the example file in a dropbox ?. Someone from the inside can fix it, just my two cents.

**Comment by souravsingh** [comment]
@mklauser Are you referring to this file-https://github.com/tardis-sn/tardis/blob/master/tardis/data/tardis_example_config.yml
As Far as I know,It seems correct to me

**Comment by unoebauer** [comment]
No longer an issue - yaml format has actually changed in the meanwhile. FYI, @wkerzendorf, I am closing this one.
