### ISSUE TITLE
Move tardis/io/tests/data/arepo_snapshot.json to refdata

### ISSUE THREAD

**Issue by smithis7** [tardis-sn/tardis#1892]
The file `tardis/io/tests/data/arepo_snapshot.json` is about 6MB and should probably be located in the refdata.

When this is changed, this file is symlinked in the directory `docs/io/configuration/components/models/converters`, so that will need to be fixed -- ideally we could get a smaller JSON file to be used in the docs example. Even if we just move the full JSON to the docs folder, this is better than the current situation as symlinks from test data to the documentation is not ideal.

**Comment by epassaro** [comment]
Done https://github.com/tardis-sn/tardis-refdata/pull/56
