### ISSUE TITLE
system pickle overriden

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1895]
@epassaro you are messing with numba using this method - see https://github.com/numba/numba/issues/7807

https://github.com/tardis-sn/tardis/blob/c70594674b4e0998f3ea8a349911c1096e877331/tardis/__init__.py#L26

Can we fix this?

**Comment by epassaro** [comment]
I don't know.

pyne holds macOS Python version to 3.7. Reference data was created with 3.8, so we needed to backport pickle 5.

Maybe we can re-generate the reference data with 3.7 and push it again, but I'm not sure if this is going to work.

**Comment by wkerzendorf** [comment]
@epassaro do we still need this

**Comment by epassaro** [comment]
I think the right thing to do is wait to merge Thom's PR and then move to Python 3.9 @wkerzendorf
