### ISSUE TITLE
Make Sure MultiIndices are Named

### ISSUE THREAD

**Issue by Rodot-** [tardis-sn/tardis#1909]
**Is your feature request related to a problem? Please describe.**
Many parts of the code reference elements of a pandas MultiIndex, represented by undocumented integers.  

**Describe the solution you'd like**
These values should either be well documented, set to named constants, or use pandas column names directly.

**Comment by rishav-karanjit** [comment]
@Rodot- can you give an example of this issue?

**Comment by xansh** [comment]
@Rodot- Are you referring to statements like these:

`current_level_population /= atom_data.levels.loc[14, 1].g`

**Comment by Rodot-** [comment]
I've written this a while ago so I'm not sure what I'm referring to given that I didn't provide any examples.  I'll close this for now unless it comes up again and I can better document it.
