### ISSUE TITLE
Tardis - segmentation fault

### ISSUE THREAD

**Issue by cradesto** [tardis-sn/tardis#191]
With the latest version ('tardis-sn==1.0.0.dev1328' from Fri Oct 3 12:14:33 2014)
python crashes if we will use next configs (see below).

For example with the version ('tardis-sn==1.0.0.dev1142' from Tue Jul 1 18:13:34 2014 +0300) it does not.

for convenience
https://dl.dropboxusercontent.com/u/13622198/tardis_segmentation_fault.zip

# --- BEGIN tardis_pure_hydrogen_with_datafiles_ph.yml
tardis_config_version: v1.0
supernova:
    luminosity_requested: 2.315e+8 solLum
    time_explosion: 14.806 day

atom_data: kurucz_cd23_chianti_H_He.h5

model:
    structure:
        type: file
        filename: density_ph.dat
        filetype: simple_ascii
    abundances:
        type: uniform
        H: 1.0

plasma:
    disable_electron_scattering: no
    ionization: nebular
    excitation: lte
    radiative_rates_type: dilute-blackbody
    line_interaction_type: macroatom

montecarlo:
    seed: 23111963
    no_of_packets : 4.0e+4
    iterations: 20
    black_body_sampling:
        start: 1 angstrom
        stop: 1000000 angstrom
        num: 1.e+7
    last_no_of_packets: 1.e+5
    no_of_virtual_packets: 50
    convergence_criteria:
        type: specific
        damping_constant: 1.0
        threshold: 0.05
        fraction: 0.8
        hold: 3
        t_inner:
            damping_constant: 1.0

spectrum:
    start : 500 angstrom
    stop : 12000 angstrom
    num: 10000
# --- END tardis_pure_hydrogen_with_datafiles_ph.yml

# --- BEGIN density_ph.dat
14.806 day 
# index velocity (km/s) density (g/cm^3)
0   6.840295E+03  8.710827E-14
1   6.961582E+03  1.613836E-13
2   7.099322E+03  9.241860E-14
3   7.359631E+03  3.120753E-14
4   7.712450E+03  1.430077E-14
5   8.089749E+03  8.212198E-15
6   8.476791E+03  4.915406E-15
7   8.858690E+03  3.070856E-15
8   9.217784E+03  2.027493E-15
9   9.530969E+03  1.458678E-15
10  9.784131E+03  1.147518E-15
11  9.919257E+03  1.394631E-15
12  9.960857E+03  3.003028E-15
13  9.984631E+03  3.523379E-15
14  1.000309E+04  3.049716E-15
15  1.002077E+04  2.142197E-15
16  1.004037E+04  1.298851E-15
17  1.006222E+04  7.831760E-16
18  1.008786E+04  4.483936E-16
19  1.011365E+04  2.992674E-16
20  1.013865E+04  2.074242E-16
21  1.016430E+04  1.357561E-16
22  1.019308E+04  8.120063E-17
23  1.023444E+04  3.788431E-17
24  1.027825E+04  2.393643E-17
25  1.032346E+04  1.552242E-17
26  1.037432E+04  9.226976E-18
27  1.044749E+04  4.277198E-18
28  1.058052E+04  1.556895E-18
29  1.079154E+04  6.412973E-19
30  1.109068E+04  2.912456E-19
31  1.148940E+04  1.385031E-19
32  1.169391E+04  1.729256E-19
33  1.173140E+04  6.233894E-19
# --- END density_ph.dat

**Comment by unoebauer** [comment]
@wkerzendorf - this is quite old - so is the used tardis version. We should just test whether this issue is still present in the current version and then close or reinvigorate this issue. I'll have a look at this.

**Comment by unoebauer** [comment]
FYI @ssim, @wkerzendorf 

Update: 

**Good News**:
  - with the current Tardis version (upstream/master, 34f667a465b36b7f76f7e9229a7d93d057c38d4a), no segmentation fault interrupts the calculation

** Bad News**:
  - despite having ``no_of_virtual_packets = 50`` set, the final virtual spectrum has zero flux everywhere
  - the real spectrum is non-zero and packets have interacted

Need to investigate further

**Comment by unoebauer** [comment]
Ok - the original problem addressed by this issue (segfault) is no longer a problem with the current Tardis version. A new issue, #445, has been opened which is dedicated solely to the issue with the virtual spectrum. Thus, I am closing this one.
