### ISSUE TITLE
Related to GSoC Project first ojective

### ISSUE THREAD

**Issue by its-sushant** [tardis-sn/tardis#1936]
**Discription**

Project Name - Better testing framework to ascertain the scientific accuracy of TARDIS

Objective - Look at the documentation to run the TARDIS documentation (http://tardis-sn.github.io/tardis) with refdata enabled. Run them locally on your machine and post the last part of the tests in an issue on the GitHub repository.

**Describe**

I ran following test command `pytest tardis --tardis-refdata=/home/shushant/tardis-refdata/` on my local and got the following result
![Screenshot from 2022-03-23 23-10-37](https://user-images.githubusercontent.com/76658675/159776574-bdb3d80c-32f7-4f0c-be4f-8e41a1baa51e.png)

**Additional context**

@epassaro @wkerzendorf  I have done the first objective for the above **GSoC project**. I would like to continue my work on this project and be part of **GSoC 22**. Looking forward for your feedback to further approach this project.
Thankyou :)

**Comment by wkerzendorf** [comment]
so 14 tests fail - have a look what is wrong.

**Comment by its-sushant** [comment]
Hey @wkerzendorf  i ran the same command `pytest tardis --tardis-refdata=home/shushant/tardis-refdata` after completely pulling the lfs file. Now it is not showing any error. 
![Screenshot from 2022-03-28 22-31-51](https://user-images.githubusercontent.com/76658675/160451297-0a249770-af4e-43fd-8f36-53bb831e7f6f.png)
Kindly review it and suggest what i need to do further.
Thankyou :)
