### ISSUE TITLE
The first objective for "Monte Carlo 2D Packet Visualization"

### ISSUE THREAD

**Issue by jl-liu2022** [tardis-sn/tardis#1947]
I have tried to work on the first objective for "Monte Carlo 2D Packet Visualization" and made a notebook. I post the notebook as a pdf here.
[one_packet_tracking.pdf](https://github.com/tardis-sn/tardis/files/8460713/one_packet_tracking.pdf)

Looking forward to your feedbacks, thanks!

**Comment by wkerzendorf** [comment]
also can you make a draft application available on google docs or overleaf so we can easily comment.

**Comment by wkerzendorf** [comment]
We also can not take you as a student if it is not submitted via the official google website.

**Comment by jl-liu2022** [comment]
> We also can not take you as a student if it is not submitted via the official google website.

OK. In fact, I'm trying to find the entry for submitting in the official google website (haha).
