### ISSUE TITLE
Astropy development travis has issues passing as cython doesn't seem to be recognized

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#195]
See https://travis-ci.org/tardis-sn/tardis/builds/40332722

**Comment by kaushik94** [comment]
@wkerzendorf  I think I figured out the fix, a similar thing happened in `sympy` community as well https://github.com/sympy/csympy/issues/308. The solution is https://github.com/sympy/csympy/pull/313. Hope it helps.

**Comment by unoebauer** [comment]
@wkerzendorf - Status update? Looks like this is no longer an issue...
