### ISSUE TITLE
The First Objective for Monte Carlo 2D Packet Visualization 

### ISSUE THREAD

**Issue by ayesca** [tardis-sn/tardis#1955]
Here you will find a project (MC_2D.pdf) that runs a TARDIS simulation with packet logging enabled with only 1 packet. The trajectory of the packet was plotted through the ejecta by graphing mu vs r.

Please let me know if there are any changes required!

Thanks!

[MC_2D.pdf](https://github.com/tardis-sn/tardis/files/8483265/MC_2D.pdf)

**Comment by jaladh-singhal** [comment]
@ayesca can you please create a PR with the notebook?
