### ISSUE TITLE
 The first objective for "Better testing framework to ascertain the scientific accuracy of TARDIS"

### ISSUE THREAD

**Issue by Tanuj-rai** [tardis-sn/tardis#1960]
Description-

Project Name-Better testing framework to ascertain the scientific accuracy of the TARDIS

Objective - Look at the documentation to run the TARDIS documentation (http://tardis-sn.github.io/tardis) with refdata enabled. Run them locally on your machine and post the last part of the tests in an issue on the GitHub repository.

Issue Description-

I ran the test command provided in the documentation "pytest tardis --tardis-refdata=/path/to/tardis-refdata/" on my local machine and got the following results 

![tardis](https://user-images.githubusercontent.com/84439872/163674515-112a4ce4-75b0-4d74-8abb-59d5a573a66b.PNG)

@wkerzendorf @epassaro @AlexHls I have completed the first objective of GSoC project. I am excited to work on this project and looking forward for your feedback for further improvement. 
Thank you

**Comment by Tanuj-rai** [comment]
Hello! Dhruv can you please reopen this issue so that I got feedback regarding this issue.

**Comment by DhruvSondhi** [comment]
Can you try to reopen the issue? I am not able to reopen this from my side. At first the issue seemed trivial thats why I closed it but now as this is meaningful, I cannot do so. Sorry for the inconvenience caused.

**Comment by Tanuj-rai** [comment]
No problem @DhruvSondhi. I am also unable to reopen the issue from my side also. The option to reopen the issue is not visible to me.

**Comment by Tanuj-rai** [comment]
Thank you so much @DhruvSondhi

**Comment by andrewfullard** [comment]
It appears that you did not clone the reference data repository, or you did not point the tests at the cloned reference data repository. That is probably why the tests are failing. Only a small number of tests seem to have been run, too. Please read the documentation carefully.

If the documentation is unclear, please make an issue highlighting the confusing parts. Thanks!

**Comment by Tanuj-rai** [comment]
Thanks, @andrewfullard for your feedback and I will consider your feedback to improve it.
