### ISSUE TITLE
Isotopes specified at what time in STELLA

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#1964]

**Comment by matteocantiello** [comment]
Isotopes are specified at the time of STELLA input (so at MESA handout). STELLA does not include a nuclear reaction network except for the radioactive decay chain initiated from 56Ni (basically heating by decays 56Ni → 56Co→ 56Fe, See Blinnikov & Sorokina 2004).

**Comment by matteocantiello** [comment]
Useful STELLA references: 
https://www.aanda.org/articles/aa/pdf/2006/25/aa4594-05.pdf 
https://iopscience.iop.org/article/10.1086/305375/pdf
https://arxiv.org/abs/astro-ph/0212530
