### ISSUE TITLE
TARDIS May produce different results when multithreading.

### ISSUE THREAD

**Issue by Rodot-** [tardis-sn/tardis#2021]
**Describe the bug**
Updating the estimators when in parallel during the montecarlo main loop is not an atomic operation, resulting in invalid values when run with multiple threads.

Should be fixed by adding multithreaded tests.

**To Reproduce**
Hard to compare, see continuum branch

**Screenshots**

**System**
 - OS:
    - [x] GNU/Linux
    - [x] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by jayantbhakar** [comment]
I think the same issue is with progress bars. I am trying to figure out a way for it. I have gone through its code and the multithread loop is causing the problem. I didn't find a way to control that loop for single execution of the progress bars as well.

**Comment by Rodot-** [comment]
Should be noted while this was partially fixed by #2022 there may still be inconsistencies in the v_packet energy histograms as they are not properly handled in parallel (though the likelihood they run into such problems is lower, but non-zero)
