### ISSUE TITLE
Local and Conda Environment Clash Issue

### ISSUE THREAD

**Issue by rohithvarma3000** [tardis-sn/tardis#2056]
**Describe the bug**

Even though the env was built and activated properly on the local machine, python was using packages in ~/.local which had a different version instead. The packages may have been installed in that location when I had used pip install without using the an env. This bug needs to be documented.

This problem can be solved by removing these packages in ~/.local using the command `pip freeze --user | xargs pip uninstall --yes`

**To Reproduce**

Install tardis without using an env. Then setup the tardis env and run the quickstart.ipynb file. If there is a clash due to package version difference then it will through these errors.

**Screenshots**

**System**
 - OS:
    - [x] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

Python tends to prioritise the ~/.local location over the conda env location.

**Comment by epassaro** [comment]
I disagree. 

At some point you must forgot to activate the environment before installing the package with `pip install -e .`. Otherwise, this wouldn't be possible.

**Comment by rohithvarma3000** [comment]
Agreed. Not activating the environment before installing the package is the cause of this issue. We should provide a warning regarding this.
