### ISSUE TITLE
Configuration parameter description for `no_of_packets` in the Documentation needs correction

### ISSUE THREAD

**Issue by jayantbhakar** [tardis-sn/tardis#2066]
**Description**
The Monte Carlo Configuration Parameter `no_of_packets` has currently some inappropriate description in the TARDIS [Documentation](https://tardis-sn.github.io/tardis/io/configuration/components/montecarlo.html#montecarlo-config).

**To Reproduce**
A Better description that tells the actual use of the input parameter.

**Comment by grgkaran03** [comment]
@jayantbhakar 
Changed the description. Please review my correction.
