### ISSUE TITLE
binary search problem see #204 and #206

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#207]
I think the #204 problem is traced to a typo in the reverse binary search

Related to this, in cmontecarlo.c we still have a "binary_search" (lines 76 - 119). That routine appears to have the same bug, and also several other peculiarities: e.g. the last "if" statement makes no sense.

However, it seems to be that that binary_search is not currently used or needed. Therefore I proposed that we simply remove it, unless someone foresees a need for it. In which case it must be fixed too.

**Comment by pfrcks** [comment]
@ssim What's the status on this bug ? Does the Binary Search needs fixing?

**Comment by unoebauer** [comment]
@ssim, @wkerzendorf - is this still relevant? #204 has been long closed. Looks like this one should find the same fate.

**Comment by ssim** [comment]
We can close this one - doing it now.
