### ISSUE TITLE
model reader / artis file - offset?

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#213]
In doing work for He project, Aoife spotted a possible issue in model_reader.py: when asked to read artis abundances file it actually uses ascii ...this leads to the first zone data being ignored (and a mismatch to the density profile). 

This issue is a placeholder to remind me/us to look at this an fix! @wkerzendorf

**Comment by pfrcks** [comment]
@ssim Can you please provide me the atis abundance file , so that I can try working on this fix ?

**Comment by wkerzendorf** [comment]
@ssim let's chat about this offline.

**Comment by wkerzendorf** [comment]
@aoifeboyle is that the issue that your new PR just fixed? If so - let's close it.

**Comment by aoifeboyle** [comment]
@wkerzendorf Yes actually! I don't think I'm able to close it but feel free :)
