### ISSUE TITLE
Pre/post release automerge fails

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#2157]
**Describe the bug**
Auto merging the pre/post release PRs is not currently working due to upstream git action failures.

**To Reproduce**

Run the pre/post release workflows

**Comment by prathamesh7255** [comment]
Hello @andrewfullard, I am prathamesh from India. I am currently pursuing my B. Tech. from IIT Roorkee. I am looking forward to contribute to Tardis organization. In the given issue, I am not getting what the use of system and environment description is and why is it given. May I know what it means?

**Comment by andrewfullard** [comment]
It's not actually relevant to this issue, it's just part of our default issue template that I left in by mistake.
