### ISSUE TITLE
Bokeh is causing failures for refdata testing

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#2162]
**Describe the bug**

When the refdata comparison is run, Bokeh fails and kills the notebook because of upstream changes to `jinj2`.

**To Reproduce**

Run the refdata comparison

**Screenshots**

![image](https://user-images.githubusercontent.com/20341051/203096109-70dd840b-d7da-40b2-9111-d18a1a023629.png)

**System**
 - OS:
    - [ ] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

Recommend replacing Bokeh with plotly, which can do the same things and is already in the env.

**Comment by Soumya624** [comment]
Hi @andrewfullard ,

Just curious to know, can we solve the problem by upgrading or downgrading the versions of Jinja2 and/or Bokeh to find a compatible combination? Or we should try using a different environment or notebook to see if the issue persists?

I think this could help to isolate the problem and determine whether it is specific to our current setup or a more general issue with the libraries themselves.
