### ISSUE TITLE
Conda-forge package outdated

### ISSUE THREAD

**Issue by jsilvabeyer** [tardis-sn/tardis#2181]
I don't know if this is an issue that is more on the TARDIS side or the conda-forge side, but the conda-forge package is very outdated, being the June 19th release, making it incompatible with new TARDIS releases.

**Comment by epassaro** [comment]
Hi @jsilvabeyer 

The conda-forge package was not automatically released because [a bug](https://github.com/tardis-sn/tardis/issues/2167) in the TARDIS source code, but should be available in a few hours.

**Comment by epassaro** [comment]
The new package has been uploaded to conda-forge :smiley: 

In the future, issues related to the conda-forge package should be opened at https://github.com/conda-forge/tardis-sn-feedstock

Thank you for submitting this issue.

**Comment by jsilvabeyer** [comment]
Thank you for the info!
