### ISSUE TITLE
The Tests Pipeline Is Failing on my fork

### ISSUE THREAD

**Issue by atharva-2001** [tardis-sn/tardis#2191]
**Describe the bug**

The test pipeline is failing. 
To check:
- [Link](https://github.com/atharva-2001/tardis/actions/runs/3958861195) to the failed workflow.
- [Link](https://github.com/tardis-sn/tardis/compare/master...atharva-2001:test_branch?expand=1) to the branch.

**To Reproduce**

Run the tests workflow.

**Screenshots**

**System**
 - OS:
    - [X] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by epassaro** [comment]
The test pipeline is failing on your fork. That's because your master branch is 179 commits behind upstream.

**Comment by atharva-2001** [comment]
But the branch on which the workflow failed is [synced](https://github.com/tardis-sn/tardis/compare/master...atharva-2001:test_branch?expand=1) with the master branch on the TARDIS repository, right?

**Comment by epassaro** [comment]
I don't know, the link is not correct I guess. I assume you can see your branch but I don't.

**Comment by epassaro** [comment]
Are working with a new atomic file?

MD5SUM and UUID1 signatures are no longer encoded in new Carsus atomic files, I think that's the problem.

**Comment by epassaro** [comment]
The pipeline passed on the master branch.

**Comment by chvogl** [comment]
I guess this is no longer relevant @atharva-2001? Closing for now.
