### ISSUE TITLE
Not able to run example program 

### ISSUE THREAD

**Issue by prakash09** [tardis-sn/tardis#221]
I am trying to run tardis from http://tardis.readthedocs.org/en/latest/running.html
After running the below command -
tardis tardis_example.yml output_spectrum.dat

I am getting "AttributeError: 'DataFrame' object has no attribute 'replace'"

**Comment by wkerzendorf** [comment]
can you give the full traceback?

**Comment by prakash09** [comment]
Full traceback -
prakash@prakash-pc:~/Downloads/tardis_example$ tardis tardis_example.yml abc.dat
tardis.io.config_reader - INFO - Reading Atomic Data from kurucz_cd23_chianti_H_He.h5
tardis.atomic - INFO - Read Atom Data with UUID=5ca3035ca8b311e3bb684437e69d75d7 and MD5=21095dd25faa1683f4c90c911a00c3f8
Traceback (most recent call last):
  File "/usr/local/bin/tardis", line 62, in <module>
    tardis_config = config_reader.Configuration.from_yaml(args.config_fname)
  File "/usr/local/lib/python2.7/dist-packages/tardis/io/config_reader.py", line 784, in from_yaml
    return cls.from_config_dict(yaml_dict, test_parser=test_parser)
  File "/usr/local/lib/python2.7/dist-packages/tardis/io/config_reader.py", line 939, in from_config_dict
    abundances = abundances.replace(np.nan, 0.0)
  File "/usr/lib/pymodules/python2.7/pandas/core/frame.py", line 1437, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'replace'

**Comment by wkerzendorf** [comment]
what versions of packages are you using? you can do pip freeze that will show you what is going on.

**Comment by wkerzendorf** [comment]
We recommend using anaconda for python installation as described in our manual tardis.readthedocs.org

**Comment by prakash09** [comment]
The output of pip freeze is http://dpaste.com/277W40G
I have used system-wide installation

**Comment by wkerzendorf** [comment]
you have a very old version of pandas. Please use anaconda (it is only installed in user space -- won't interfere with your system and can be easily uninstalled), as this will ensure that you have the correct version installed.

**Comment by wkerzendorf** [comment]
let me know how it goes.

**Comment by orbitfold** [comment]
We should still probably add an exception handler and print something like "You likely have pandas version below so and so"

**Comment by orbitfold** [comment]
Which is what you can do @prakash09

**Comment by wkerzendorf** [comment]
I think there is a proper way of doing this for python setup files. But I don't know how.

**Comment by orbitfold** [comment]
http://stackoverflow.com/questions/15834628/how-to-specify-explicit-python-packaging-dependencies-in-setup-py

This might help.

**Comment by wkerzendorf** [comment]
It should read it from the `pip-requirements` file (which should be renamed to `anaconda-requirements`).

**Comment by orbitfold** [comment]
Is that the same as dependencies? https://github.com/pypa/pip/issues/988

**Comment by wkerzendorf** [comment]
I think so. it uses the same format. pytables however is not pip installable

**Comment by prakash09** [comment]
@wkerzendorf can I use virtualenv instead of anaconda?

**Comment by wkerzendorf** [comment]
anaconda will give you virtual environments. It is much easier to use as it also brings the required c-libraries. I used virtual environments for a long time and then switched. In the end it is up to you.

**Comment by prakash09** [comment]
It worked after upgrading pandas manually.

**Comment by orbitfold** [comment]
This should still be resolved though. There shouldn't be a way for a user to arrive at an unhandled exception.

**Comment by pfrcks** [comment]
@orbitfold A minimum version for all the needed packages can be given so that whenever setup.py runs it gives a warning if the version is below the workable version.

**Comment by wkerzendorf** [comment]
This might be useful addition to the code.

**Comment by prakash09** [comment]
I am a gsoc 2015 aspirant. Can I work on this issue?

**Comment by orbitfold** [comment]
It should not be possible to install if pandas is outdated, a warning is not enough.

**Comment by pfrcks** [comment]
@orbitfold In that case do you have a minimum requirement list for tardis to work optimally?
If you can please provide me that, I'll be very happy to work on this issue.

**Comment by wkerzendorf** [comment]
@pfrcks there's a `pip-requirements` file and the requirements should be read from that.
