### ISSUE TITLE
Documentation pipeline fails too often and randomly

### ISSUE THREAD

**Issue by epassaro** [tardis-sn/tardis#2252]
Causes? HDF5 files sometimes get corrupted when downloaded? Investigate

**Comment by Soumya624** [comment]
Hi @epassaro ,

Can you share the specific error messages or symptoms to determine the root cause of the issue?

**Comment by andrewfullard** [comment]
Example failing docs builds:
https://github.com/tardis-sn/tardis/actions/runs/4480888651/jobs/7876824671#step:8:314
https://github.com/tardis-sn/tardis/actions/runs/4479572224/jobs/7873683130#step:8:290
https://github.com/tardis-sn/tardis/actions/runs/4479278185/jobs/7873047212#step:8:304
https://github.com/tardis-sn/tardis/actions/runs/4441163461/jobs/7795893189#step:8:251

**Comment by epassaro** [comment]
This still happens after merging #2267 and #2298.

But good news, the source of this behavior is that the documentation pipeline renders notebooks in parallel, and HDF5 files are somehow locked.

The solution is:

a) stop building docs in parallel or
b) somehow tell h5py to not lock the h5 files

See: https://github.com/h5py/h5py/issues/1804
