### ISSUE TITLE
Error while running pytest coverage

### ISSUE THREAD

**Issue by vidit23** [tardis-sn/tardis#228]
When in the tardis directory, running the following command:
py.test --cov tardis tardis/tests/      gives the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 543, in importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 629, in pyimport
    __import__(pkgpath.basename)
  File "/home/vidit/tardis/tardis/__init__.py", line 7, in <module>
    from ._astropy_init import *
  File "/home/vidit/tardis/tardis/_astropy_init.py", line 125, in <module>
    config.configuration.update_default_config(__package__, config_dir)
  File "/usr/local/lib/python2.7/dist-packages/astropy/config/configuration.py", line 844, in update_default_config
    version = mod.__version__
AttributeError: 'module' object has no attribute '__version__'
ERROR: could not load /home/vidit/tardis/tardis/conftest.py

**Comment by wkerzendorf** [comment]
@vidit23 Can you please run it with anaconda, that will mean that you will have the right packages installed. This is described in the manual.

**Comment by wkerzendorf** [comment]
let me know how it goes.

**Comment by vidit23** [comment]
I ran it using anaconda but I am still getting the same error.

I used py.test --traceconfig, I get errors like:
/usr/local/lib/python2.7/dist-packages/py/_path/common.py:334: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
/usr/local/lib/python2.7/dist-packages/py/_path/common.py:370: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:628: in _recurse
    ihook.pytest_collect_directory(path=path, parent=self)
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:166: in call_matching_hooks
    plugins = self.config._getmatchingplugins(self.fspath)
/usr/local/lib/python2.7/dist-packages/_pytest/config.py:688: in _getmatchingplugins
    plugins += self._conftest.getconftestmodules(fspath)
/usr/local/lib/python2.7/dist-packages/_pytest/config.py:521: in getconftestmodules
    mod = self.importconftest(conftestpath)
/usr/local/lib/python2.7/dist-packages/_pytest/config.py:545: in importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: (local('/home/vidit/tardis/tardis/conftest.py'), (<type 'exceptions.AttributeError'>, AttributeError("'module' object has no attribute '__version__'",), <traceback object at 0x7f515baefe60>))

**Comment by vaibhav4595** [comment]
@vidit23 were you trying this command from inside the tardis directory ? Using this command from your home folder, or wherever the tardis directory is, seemed to work fine for me. Whereas when I was trying to the same from inside the directory, I had the same error.

**Comment by wkerzendorf** [comment]
*/usr/local/lib/python2.7/dist-packages/_pytest/main.py shows me that you
are not running with anaconda. you need to activate your conda environment.
Check out the anaconda webpage. *

*Cheers,*
*   Wolfgang*

**Comment by kaushik94** [comment]
Did you install `pytest`. I ran into a similar problem, just try running `pip install pytest` on command line and try running again.

**Comment by vidit23** [comment]
@wkerzendorf I hadn't activated it when I copied the the error, but even after activating anaconda, I still see the same error.
Traceback (most recent call last):
  File "/home/vidit/anaconda/envs/tardis/lib/python2.7/site-packages/_pytest/config.py", line 543, in importconftest
    mod = conftestpath.pyimport()
  File "/home/vidit/anaconda/envs/tardis/lib/python2.7/site-packages/py/_path/local.py", line 629, in pyimport
    __import__(pkgpath.basename)
  File "/home/vidit/tardis/tardis/__init__.py", line 7, in <module>
    from ._astropy_init import *
  File "/home/vidit/tardis/tardis/_astropy_init.py", line 125, in <module>
    config.configuration.update_default_config(__package__, config_dir)
  File "/home/vidit/anaconda/envs/tardis/lib/python2.7/site-packages/astropy/config/configuration.py", line 844, in update_default_config
    version = mod.__version__
AttributeError: 'module' object has no attribute '__version__'
ERROR: could not load /home/vidit/tardis/tardis/conftest.py

@kaushik94 Yes, I had done that already
@vaibhav4595 Could you possibly send the exact command you ran for the coverage

**Comment by kaushik94** [comment]
Okay I fixed it. The astropy expects us to supply an optional version number. @vidit23  try applying this fix and let me know. Kudos !

**Comment by vidit23** [comment]
I hadn't run the command: "conda install pip".
To fix this I ran this command, then uninstall pytest-cov and install it again then the coverage command works

**Comment by kaushik94** [comment]
@vidit23  Ohh thanks for letting us know. Moreover @wkerzendorf  merged a fix #250  for this which now works on non conda installations as well. Thought you might be interested :)
