### ISSUE TITLE
Wrong usage of yield in test_utils.py

### ISSUE THREAD

**Issue by kaushik94** [tardis-sn/tardis#233]
I just figured out that yeild does not run the function, it simply returns a generator object, and hence the assertions are not really tested there. For example if we make this change
```
--- a/tardis/tests/test_util.py
+++ b/tardis/tests/test_util.py
@@ -49,7 +49,7 @@ def test_element_symbol_reformatter():
 def test_species_string_to_species():
     atom_data = atomic.AtomData.from_hdf5(atomic.default_atom_h5_path)
     def _test_species_string_to_species_tuple(species_string, species_tuple):
-        assert species_string_to_tuple(species_string) == species_tuple
+        assert species_string_to_tuple(species_string) != species_tuple
 
     data = [('si ii', (14, 1) ),
             ('si 2', (14, 1)),
```
It still passes the tests without an error. When I did a little research I found this SO question http://stackoverflow.com/questions/231767/what-does-the-yield-keyword-do-in-python
Please read it carefully.
I have submitted a PR #234 removing instances of yeild usage and now things seem to work fine

**Comment by orbitfold** [comment]
No, yield does not disable all statements in a function it is in. Unless you mean something different by a statement then what it is - a smallest standalone element in an imperative programming language.

**Comment by orbitfold** [comment]
Try running this for example:

def a():
    i = 0
    while True:
        if i < 100:
            yield i
            i += 1
            print i, i, i
        else:
            raise StopIteration

if __name__ == '__main__':
    for x in a():
        pass

**Comment by kaushik94** [comment]
Sorry my bad, what I meant to say is that yield doesn't run the code in the function, it lazily returns a generator object that has to be iterated. Take a look at my PR, when we are yielding the function, we are not really running them hence not running assertions in the tests

**Comment by kaushik94** [comment]
@orbitfold  thanks for pointing out, I just updated the comment. @wkerzendorf  take a look and let me know what you think.

**Comment by orbitfold** [comment]
I don't know why whoever wrote those used yield there, but you should not assume it was by mistake. I think it might have something to with this http://pytest.org/latest/yieldfixture.html, but I don't know for sure.

**Comment by wkerzendorf** [comment]
I wrote them. If you don't use yield, then pytest will just show this as one test and not as multiple tests.

**Comment by wkerzendorf** [comment]
it is a way to parametrize a test

**Comment by wkerzendorf** [comment]
Apparently yield has now been replaced by parametrize, so that should be used, but it still works. @kaushik94 can you either close or modify (use parametrize) your PR for yield

**Comment by kaushik94** [comment]
> I wrote them. If you don't use yield, then pytest will just show this as one test and not as multiple tests. 

Ohh sorry, I was looking for a quick fix but din't look through that
>can you either close or modify (use parametrize) your PR for yield

sure.

**Comment by kaushik94** [comment]
I removed a lot of redundant code in `test_utils` and used `parametrize`, also added missing test for `species_tuple_to_string` in the PR #234 . @wkerzendorf , @orbitfold  please take a look and let me know what you think.
