### ISSUE TITLE
How about writing doctests ?

### ISSUE THREAD

**Issue by kaushik94** [tardis-sn/tardis#235]
Its always a good practice to write doctests for any feature thats being implemented. It will let readers know whats happening in the function without going to the docs everytime. Take a look at [official python guide](http://docs.python-guide.org/en/latest/writing/tests/). @wkerzendorf  what do you think ?

**Comment by orbitfold** [comment]
If py.test works with them then fine. Otherwise no one is going to separately run them.

**Comment by wkerzendorf** [comment]
@kaushik94 it's a good idea (pytest can deal with them). But that would require some more documentation.
