### ISSUE TITLE
Update Configuration Validator

### ISSUE THREAD

**Issue by mavidser** [tardis-sn/tardis#239]
The [Configuration file validator](https://github.com/tardis-sn/tardis/blob/master/docs/configuration/config_validator.rst) seems a bit outdated.

> For every specified container item, the code expects the declaration of all sub items. The keywords for this are “_“ + “name of the container item”. 

But the current config file has elements like:

```
property_type: container-declaration
containers: ['branch85_w7','exponential','power_law', 'uniform']
_uniform: ['value']
_branch85_w7: []
+branch85_w7: ['w7_time_0', 'w7_rho_0', 'w7_v_0']m”
_power_law: ['time_0', 'rho_0', 'v_0', 'exponent']
_exponential: ['time_0', 'rho_0', 'v_0']
```

I'm not sure what does  “+“ + “name of the container item” specifies as in `+branch85_w7`.

It looks like it specifies non-mandatory items, but that seems redundant due to a mandatory property in every item, so I may be wrong.

**Comment by wkerzendorf** [comment]
@mavidser I have to look into it. It might outdated, we're considering switching to a third party YAML schema validator but have not found a good one (maybe another GSoC project)

**Comment by mavidser** [comment]
Okay. 

Meanwhile, I think I should consider `_container` as mandatory and `+container` as optional, for the pull requests for the web-app.

**Comment by wkerzendorf** [comment]
I think that's probably right anyways. Sorry, I just have to deal with some
other things currently. good luck and let me know how it goes.

**Comment by unoebauer** [comment]
I am closing this one, since it should have been addressed by @ftsamis work. If not, please re-open, @ftsamis.
