### ISSUE TITLE
WebApp project

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#241]
These are the specifications for the PR for the WebApp:
- A nice intuitive interface that has suitable inputs (textfields, dropdown boxes, etc.) and help items
- it should have as few third party dependencies as possible
  - anaconda packages preferred
  - ipython is used a lot and uses tornado, which **might** be a good solution 
- the webapp should automatically generate the form from our YAML [schema](../blob/master/tardis/data/tardis_config_definition.yml)
- the end form should have a download button to download YAML file
- there should be some instructions on how to run the webapp

The further development of the webapp throughout the summer:
- Run TARDIS with the given YAML file
- write the TARDIS output in a window (similar to the QT app in TARDIS)
- plot the spectrum(similar to the QT app in TARDIS)
- make this multi-user compatible allowing a number of users to run the code
- implement a queue (with history)
- add a backend async webservice

**Comment by wkerzendorf** [comment]
@utkbansal @mavidser @andarms So these are the PR requirements and our concrete summer ideas for the webapp. I'll post it as well on gitter/mailinglist and website, but thought you guys can already have a look.

**Comment by chhabraharsh** [comment]
Hi,
I am Harsh,I have been the part of Gsoc-2013 and currently working in Adobe Systems.
I have gone thorough your projects on Idea page and looking forward to be as potential mentor this year for the above project.
So if you want we can have a discussion on the same ?

Thanks
Harsh

**Comment by utkbansal** [comment]
@chhabraharsh Maybe you should contact Wolfgang [here](https://gitter.im/tardis-sn/tardis)

**Comment by dofod** [comment]
Hello, 
I'm Saurabh currently in 4th year of Computer Engineering at Mumbai University. I would like to work on this project as a part of GSOC 2015. I have experience in django web application development and would like to use it for this webapp too. Is this acceptable as a framework for webapp development? Please reply so that I may start work on the PR. 

Thanks

**Comment by wkerzendorf** [comment]
As described, we do not suggest django but will rather go with Tornado.

**Comment by dofod** [comment]
I have started work with the PR using tornado, please have a look:
https://github.com/dofod/tardis-web

**Comment by wkerzendorf** [comment]
Can you please make a PR to the TARDIS repo?

Cheers,
    W

**Comment by Astronautpk** [comment]
Hi,I'm Zawar Nadeem, 3rd Year Computer Science Student at Gift University.I have worked in MySql Database Engine, I have strong grip in C++. as well as in web applications in PHP. I would like to work on this project. Kindly tell me ,what are the further requirements?

**Comment by wkerzendorf** [comment]
@Astronautpk are you applying for GSoC?

**Comment by Astronautpk** [comment]
Yes. But I forgot to submit the proposal. Any compensation?

On Thu, Apr 2, 2015 at 12:11 AM, Wolfgang Kerzendorf <
notifications@github.com> wrote:

> @Astronautpk <https://github.com/Astronautpk> are you applying for GSoC?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tardis-sn/tardis/issues/241#issuecomment-88597885>.
>



-- 
Best,
Zawar Nadeem

**Comment by wkerzendorf** [comment]
So I guess you are not applying to GSoC.

**Comment by wkerzendorf** [comment]
you are more than welcome to work on TARDIS for open source.

**Comment by Astronautpk** [comment]
Ok. So another way to work on this project other than GSoC?


On Thu, Apr 2, 2015 at 12:21 AM, Wolfgang Kerzendorf <
notifications@github.com> wrote:

> So I guess you are not applying to GSoC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tardis-sn/tardis/issues/241#issuecomment-88600329>.
>



-- 
Best,
Zawar Nadeem

**Comment by wkerzendorf** [comment]
It's an open source project so you are more than welcome to work on it.

**Comment by Astronautpk** [comment]
Thanks. I'll look into it.

On Thu, Apr 2, 2015 at 12:24 AM, Zawar Nadeem <zawar.dev@gmail.com> wrote:

> Ok. So another way to work on this project other than GSoC?
>
>
> On Thu, Apr 2, 2015 at 12:21 AM, Wolfgang Kerzendorf <
> notifications@github.com> wrote:
>
>> So I guess you are not applying to GSoC.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tardis-sn/tardis/issues/241#issuecomment-88600329>.
>>
>
>
>
> --
> Best,
> Zawar Nadeem
>



-- 
Best,
Zawar Nadeem

**Comment by unoebauer** [comment]
Guess this one is still an active feature request. GSoC 16, @wkerzendorf, @ssim, @orbitfold?

**Comment by souravsingh** [comment]
Is the issue still open? @wkerzendorf @orbitfold If so,I can work on it.

**Comment by unoebauer** [comment]
Should be turned into a TEP...

**Comment by deep110** [comment]
@wkerzendorf @unoebauer  is this issue still open to work upon. If so, can I work on it.
