### ISSUE TITLE
Atomic Database project specifications

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#242]
The development of the Atomic Database happens in github.com/tardis-sn/cassis

As an explanation, the atomic databases contains two big tables: (1) a table for levels in atoms (2) a table of lines that connect these levels. 

These are the specifications for the PR for the Atomic database:
- the parser should live in cassis/io/kurucz
- parse http://kurucz.harvard.edu/atoms/1401/gf1401.gam
  - use pyparsing to parse the first line into how many lines saved, etc. -> save to dictionary
  - at line 33 there is a fixed format table; use pandas to read in the first six columns (until g Lande)
  - the sqlalchemy can live in cassis/alchemy
  - Use sqlalchemy to build an sqlite table for the pandas table
- [optional] read in the lines file and link in database with the levels file. (will update this with specifics soon).

The further development for the atomic database throughout the summer
- Add more metadata to the atomic database from the given files
- prepare the database for inputting data from multiple sources
  - ChiantiPy will bring the same information measured by the CHIANTI team
  - Topbase atomic data and some others 
- Make a writer for the TARDIS HDF5 format
- visualize the atomic data through grotrian diagrams
- compare the difference in simulations with the different atomic databases

**Comment by wkerzendorf** [comment]
@pfrcks @dumindux @Mnw2212 @aadilh @mohit-agarwal you all have done PRs for this project. These are the specific instructions for the PR and for the summer

**Comment by wkerzendorf** [comment]
let me know if some of the things are unclear

**Comment by pfrcks** [comment]
What about the lines 2-32 are they to be parsed or stored too, or should they be overlooked?

**Comment by wkerzendorf** [comment]
for now we ignore them.

**Comment by pfrcks** [comment]
@wkerzendorf From line number 1803, the dataset seems of another format.
Do we have to store that too using pandas. If so is the 6th column from line 1803 onwards still g Lande' ?

**Comment by pfrcks** [comment]
@wkerzendorf https://github.com/tardis-sn/cassis/pull/10 Implemented what you asked for please check

**Comment by Mnw2212** [comment]
@wkerzendorf  I think I failed to understand the third point mentioned in the issue.
The third point being : 
* read in the lines file and link in database with the levels file. (will update this with specifics soon)

Could you please give a little more detail on what do you mean by lines file and levels file ?
Thank You

**Comment by pfrcks** [comment]
@Mnw2212 The levels file is the one that you extracted using pandas.Add a primary key to it(Can be simple Integer.)
The lines file is an empty file(as of now) with two columns upper_id and lower_id.
Now you have to link both the files. As upper_id and lower_id both reference the primary key of levels.

I guess that was pretty much it. 
Right @wkerzendorf ?

**Comment by wkerzendorf** [comment]
@Mnw2212 @pfrcks that's roughly right.

**Comment by light94** [comment]
@wkerzendorf  Please see the PR at https://github.com/tardis-sn/cassis/pull/11

**Comment by MayankVachher** [comment]
Shouldn't it be line 38, the location of the fixed format table?

**Comment by unoebauer** [comment]
This seems still very relevant, despite the lack of activity since March. GSoC 16, @wkerzendorf, @ssim, @chvogl?

**Comment by unoebauer** [comment]
Closing this one since we have a dedicated TEP and the CARSUS (@mishinma) project.
