### ISSUE TITLE
Fitting Project

### ISSUE THREAD

**Issue by orbitfold** [tardis-sn/tardis#243]
For the fitting project you should check out DALEK which can be found at https://github.com/tardis-sn/dalek.

DALEK is the framework we use to run multiple instances of TARDIS over several machines connected in to a cluster. TARDIS usually takes several minutes to run on a single CPU so if you want to use any kind of population based algorithms for optimization it would translate to several months of CPU time if you decided to try it on a single core machine. Even on most powerful multicore machines it still means weeks. DALEK simplifies running several instances of TARDIS in parallel with various parameters and then analyzing the results.

Before the beginning of the program you should:
- get and install a copy of DALEK
- create a grid of 4x4 of oxygen and silicon abundances, get DALEK to run TARDIS on that grid (you can take all the other parameters from a YAML file you used to run TARDIS)
- [optional] get DALEK to run on a supercomputing cluster and test one of the optimization algorithms in https://github.com/wkerzendorf/dalek/blob/master/dalek/fitter/optimizers.py

To get you started you should look at https://github.com/wkerzendorf/dalek/blob/master/dalek/fitter/tests/test_base_fitter.py

Please have in mind that DALEK is not complete or well documented. It will require you to try to figure out what is going on on your own in a lot of cases.

During the program you will be helping us implement and  test various optimization algorithms, understand the fitness surface of the function. Ideally in the end of the program we should have a black box you can give a spectrum of a real supernova to and that would give us its physical properties.

**Comment by sarvjeetsinghghotra** [comment]
I am interested in working on this. Can someone tell about the potential mentor of this project?

**Comment by unoebauer** [comment]
Do we want to propagate this project into GSoC 16, @orbitfold, @wkerzendorf?

**Comment by orbitfold** [comment]
I'd like to say yes. But it's a pretty messy, hard and nebulous task, not sure how fair it would be to expect the students to make any kind of good progress/produce showable code with this.

**Comment by souravsingh** [comment]
I wish to start work on the project. I have tried to install DALEK and faced installation errors.

**Comment by souravsingh** [comment]
Alright,I have installed DALEK and learning about it. @orbitfold Can you help me in this?

**Comment by unoebauer** [comment]
Closing since it is outdated (c.f. DALEK and @yeganer's emulator project instead)
