### ISSUE TITLE
Duplicate level index when using continuum interaction

### ISSUE THREAD

**Issue by AlexHls** [tardis-sn/tardis#2442]
**Describe the bug**

When enabling continuum interactions duplicate level indices appear (see screenshot), causing TARDIS to crash during the re-indexing process ``tardis/plasma/properties/transition_probabilities.py:362``

Currently #2443 implements a bandaid fix that throws a warning. Once Carsus implemented a fix upstream, this warning should be removed and an exception should be raised instead.

**To Reproduce**

**Screenshots**

![2023-10-11T15:21:24,292949360-04:00](https://github.com/tardis-sn/tardis/assets/70367168/c3d2bfe7-6423-436d-8a4d-5e114f1ce731)

**System**
 - OS:
    - [x] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by chvogl** [comment]
Should be dealt with in Carsus (see carsus#384).

**Comment by chvogl** [comment]
Is this not what #2444 is for?
