### ISSUE TITLE
Quickstart needs to be updated after the recent restructure

### ISSUE THREAD

**Issue by sonachitchyan** [tardis-sn/tardis#2449]
**Describe the bug**

Recent restructure in TARDIS has moved, for example, the config reader and the simulation into new/restructured directories. This, as far as I can tell, has not changed in the quickstart.
**To Reproduce**

**Screenshots**

**System**
 - OS:
    - [ ] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by andrewfullard** [comment]
This seems to have been resolved. The quickstart has succeeded in the docs and has `sim.transport` correctly used.
