### ISSUE TITLE
Running py.test throws an import error

### ISSUE THREAD

**Issue by kaushik94** [tardis-sn/tardis#246]
I ran py.test in the /tests directory and getting errors like this
```
_____________________ ERROR collecting test_tardis_full.py _____________________
test_tardis_full.py:5: in <module>
    from tardis import io, model, simulation
../model.py:12: in <module>
    from tardis import packet_source, plasma_array
../plasma_array.py:11: in <module>
    from tardis import macro_atom, io
E   ImportError: cannot import name macro_atom
```

**Comment by wkerzendorf** [comment]
use `python setup.py test` that will build the c modules

**Comment by kaushik94** [comment]
>use python setup.py test that will build the c modules

That din't help. I guess the error is because of some circular import since I see only `plasma_array.py`  tests barfing

**Comment by wkerzendorf** [comment]
It's because cython was not compiled. macro_atom needs to be compiled before. I encountered this when things didn't build correctly.

**Comment by vidit23** [comment]
Same thing is happening to me too, this is when I run test for atomic.py.  I tried "python setup.py test" but its not helping.

**Comment by vidit23** [comment]
Anyone found a solution?

**Comment by kaushik94** [comment]
This was fixed.
