### ISSUE TITLE
Change conftest pytest fixture scope from ``function`` to ``module``

### ISSUE THREAD

**Issue by AlexHls** [tardis-sn/tardis#2481]
https://github.com/tardis-sn/tardis/blob/799e35ba7f333c15b9ab451dac3a287f4d73f4d5/tardis/conftest.py#L192

The scope should be changed to e.g. ``module``. Probably for all functions doing similar things.

**Comment by andrewfullard** [comment]
Could you explain more as to why?

**Comment by AlexHls** [comment]
I actually have no idea anymore why this was an issue. I just remember discussing this with @wkerzendorf .  Myabe it had something to do with the fact that we use the same config file for both nlte solvers but modify its contents? Not sure if this is even relevant still.

**Comment by andrewfullard** [comment]
In that case I'll close this out. There are definitely concerns around fixture scope that I have but I need to research the actual impact of `scope`.
