### ISSUE TITLE
Testing project

### ISSUE THREAD

**Issue by orbitfold** [tardis-sn/tardis#249]
The goal of this project is to ensure uniform test coverage of all TARDIS methods and functions. We use pytest for testing. The goal is to ensure 100% coverage. You can check coverage here https://coveralls.io/r/tardis-sn/tardis (note this does not include C function testing). The main challenge will be to test the C-part with pytest. The tests should run via issuing "setup.py test".

Before beginning of the program you should:
- pick an untested function or two and write tests for them
- [optional] write a test for some of the C functions in cmontecarlo.c/or cmontcarlo.h
  - an easy one can be `rpacket_get_nu`/`rpacket_set_nu`

During the program you will help the team making this code reach a coverage of close to 100% for both the python and c part

**Comment by unoebauer** [comment]
@wkerzendorf - certainly still relevant. I guess also for GSoC 16.

**Comment by unoebauer** [comment]
Deprecated - addressed by a dedicated TEP and the GSOC 2016 project of @karandesai-96.

Closing
