### ISSUE TITLE
Build docs fails because of an old hdf used to generate the sdec plot

### ISSUE THREAD

**Issue by jvshields** [tardis-sn/tardis#2497]
When triggering build_docs, the job fails when trying to run this line:
hdf_plotter = SDECPlotter.from_hdf("demo.hdf")

It reports failing with this error:
KeyError: 'No object named /simulation/simulation_state/r_inner in the file'

I believe this is because the demo.hdf file used to generate the sdec plot was made before the radiation field restructure. The demo needs to be regenerated with the new (still changing) tardis structure for build_docs to be able to run.

**Comment by demohatesrng** [comment]
Doesn't this error show up when the object is not found in the file. Try checking the file Structure, try using hp5py to see whats inside. Please correct me if i am wrong .

**Comment by andrewfullard** [comment]
Since docs are building successfully this is presumably fixed
