### ISSUE TITLE
Equation and Code not matching in Energy Packet Initialization documentation

### ISSUE THREAD

**Issue by CePowers** [tardis-sn/tardis#2511]
**Describe the bug**
The equation for the Planck distribution does not match the cell below it in the documentation. In the equation pi is not squared, but it is squared in the cell below it.

**To Reproduce**

**Screenshots**
![luminosity_equation](https://github.com/tardis-sn/tardis/assets/144163718/43e6e606-a25e-4431-8b99-242335604273)
![luminosity_code](https://github.com/tardis-sn/tardis/assets/144163718/ed8c5ebb-849d-48f2-8406-a087403b8904)

**System**
 - OS:
    - [ ] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):

**Additional context**

**Comment by DeerWhale** [comment]
Update: the code part is actually correct, rather it is equation in the documentation that had the error, this is being udpated in PR #2555 .
