### ISSUE TITLE
Convergence plot correction 

### ISSUE THREAD

**Issue by jamesgillanders** [tardis-sn/tardis#2519]
**Describe the bug**
In the convergence plot widget, both T and W are plotted against shell velocity. These plots should present their data as a step function, instead of a scatter line, since the T and W values are constant throughout each individual shell.

**To Reproduce**
Run the convergence plot.

**Comment by Vivek-Joshi17** [comment]
Sir, I'm willing to work on this issue with your permission.

**Comment by jamesgillanders** [comment]
Go for it!

On 25 Feb 2024, at 17:59, Vivek Joshi ***@***.***> wrote:



Sir, I'm willing to work on this issue with your permission.

**Comment by sarthak-dv** [comment]
@jamesgillanders Since this issue was pending since weeks, I have taken the liberty to fix it.
[PR containing fix](https://github.com/tardis-sn/tardis/pull/2528).
Please review, thanks in advance!
