### ISSUE TITLE
Duplicated packet source initialization

### ISSUE THREAD

**Issue by DeerWhale** [tardis-sn/tardis#2585]
**Describe the bug**
In the [tardis/model/parse_input.py](https://github.com/tardis-sn/tardis/blob/1718002b4db7fd1a93e475844582ed9b41aa7cdf/tardis/model/parse_input.py#L589), there are 2 functions contains duplicated codes for the packet source initialization, see the screenshot below:  
<img width="1435" alt="image" src="https://github.com/tardis-sn/tardis/assets/48139543/9cf1a96b-06d0-4211-9fbe-b10c8fe28677">

Currently each of the two functions is being called somewhere else (see screenshot below), but someone should investigate carefully if the duplication is on purpose or by mistake. 
![image](https://github.com/tardis-sn/tardis/assets/48139543/1b74ef88-4469-4068-af35-b92abb67c096)

**Comment by Sumit112192** [comment]
I think we should remove the reinitialization of `packet_source` from the function `initialize_packet_source`
https://github.com/tardis-sn/tardis/blob/dfb4975e71431baa44e6e5338c3c3f1d3470cf75/tardis/model/parse_input.py#L553-L591

The reasoning,
`initialize_packet_source` is called two times:
1) 
https://github.com/tardis-sn/tardis/blob/dfb4975e71431baa44e6e5338c3c3f1d3470cf75/tardis/model/parse_input.py#L624-L638

We have already initialized the `packet_source` before passing it to the `initialize_packet_source` function.

2) https://github.com/tardis-sn/tardis/blob/dfb4975e71431baa44e6e5338c3c3f1d3470cf75/tardis/simulation/base.py#L706-L712
The reinitialization will overwrite the custom `packet_source` passed to the default one, which I think is not desired as we pass a custom `packet_source`.

**Comment by andrewfullard** [comment]
Will be fixed with #2652
