### ISSUE TITLE
Shell info widget fails to render

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#2599]
**Describe the bug**

The shell info widget fails to render and produces javascript errors related to qgrid.

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'QgridModel' from module 'qgrid'
makeError@https://moria-jupyterhub.egr.msu.edu/user/afullard/static/nbclassic/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:168:17
onScriptError@https://moria-jupyterhub.egr.msu.edu/user/afullard/static/nbclassic/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:1735:36
```

**To Reproduce**

Run the how-to generating widgets docs notebook.

**Screenshots**

![image](https://github.com/tardis-sn/tardis/assets/20341051/bc95a52d-9065-4b32-a990-b16b8677df13)

**System**
 - OS:
    - [x] GNU/Linux
    - [ ] macOS

 - Environment (`conda list`):
TARDIS 2024.4.21

**Comment by Sumit112192** [comment]
I was getting the same error where some other model was not loading. Tweaking with the environment libraries version somehow solved the problem.

**Comment by andrewfullard** [comment]
> I was getting the same error where some other model was not loading. Tweaking with the environment libraries version somehow solved the problem.

Can you post the environment you used that worked?

**Comment by Sumit112192** [comment]
I will post it by tomorrow. I have an exam tomorrow morning.

**Comment by Sumit112192** [comment]
I tried running the above code and this was the result I obtained.
![Screenshot from 2024-04-25 15-07-12](https://github.com/tardis-sn/tardis/assets/53135486/37821883-2773-492e-b1ea-aa6db10f3f09)

![Screenshot from 2024-04-25 15-06-59](https://github.com/tardis-sn/tardis/assets/53135486/8b8a1eee-361d-4395-bbd1-a82fd333949e)

**Comment by Sumit112192** [comment]
My environment
[condaEnvironment.txt](https://github.com/tardis-sn/tardis/files/15107591/condaEnvironment.txt)

**Comment by jamesgillanders** [comment]
Any updates on this @Sumit112192 ? Did you manage to pinpoint the package that was causing the issue and how one could resolve it?

**Comment by Sumit112192** [comment]
> Any updates on this @Sumit112192 ? Did you manage to pinpoint the package that was causing the issue and how one could resolve it?
> 

Haven't looked at it for a while. I will revert back if I find something useful.

**Comment by atharva-2001** [comment]
This might be solved using the new lock files in https://github.com/tardis-sn/tardis/pull/2641/files
I'd suggest you try to replicate this issue using those @Sumit112192

**Comment by Sumit112192** [comment]
> This might be solved using the new lock files in https://github.com/tardis-sn/tardis/pull/2641/files
> I'd suggest you try to replicate this issue using those @Sumit112192 

Ok, will do that.

**Comment by Sumit112192** [comment]
@atharva-2001 Still showing the same error as the previous one,
![image](https://github.com/tardis-sn/tardis/assets/53135486/09095e1c-6f13-4c6c-ab11-debf7f46ad63)

**Comment by andrewfullard** [comment]
I'm not seeing the same javascript error in your screenshot, but in general I expect we must just replace qgrid in some form.

**Comment by Sumit112192** [comment]
@andrewfullard I haven't included the console error. I'll add those.

**Comment by Sumit112192** [comment]
Qgrid has been inactive for quite a while. Their GitHub had last merged pull requests four years ago.
![image](https://github.com/tardis-sn/tardis/assets/53135486/8c85a9c8-41c0-4fc8-816b-d2d1b9e863be)

**Comment by Sumit112192** [comment]
Here is what I found
my python version==3.12.3

qgrid any version is not compatible with ipywidgets>=4
jupyterlab_widgets>=3 is officially not compatible with ipywidgets<4
jupyterlab_widgets<3 throws an error with ipywidgets<4, though my Python version might cause this; I will have to check that.

In all, it is to replace qgrid with a different library, which is actively maintained and compatible with the latest versions of ipywidgets and jupyterlab_widgets.

**Comment by MarkMageeAstro** [comment]
Should be fixed now with qgridnext
