### ISSUE TITLE
Plasma project

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#263]
The goal of this project is to replace the existing with a new Framework for Plasma calculations. The new Framework is more modular than the current one and allows easy implementation of additional physics. Currently this is not in the code, but is part of a branch as outlined on the ideas page.

These are the suggestions to do a PR on the `plasma/restructure`-branch:

 1. Get familiar with the new structure
 2. Implement the `beta-sobolev` calculation in a new `ProcessingPlasmaProperty` - a stump exists here: https://github.com/tardis-sn/tardis/pull/215/files#diff-2c2a4ed36d667e096096f9a62d21216bR127
In the existing code they are calculated here: https://github.com/tardis-sn/tardis/blob/master/tardis/plasma_array.py#L537

Over the summer we would like to see:
 * a full test suite for the new plasma branch
 * finishing of the visualization features for the plasma
 * Implementing additional physics needed for late time spectra

**Comment by liangjiaxing** [comment]
Could the function `macro_atom.calculate_beta_sobolev()` be called in the new `ProcessingPlasmaProperty`
For example, doing something like this:
```
class BetaSobolev(ProcessingPlasmaProperty):
    name = 'beta_sobolev'
    def calculate(self, tau_sobolev):
        beta_sobolevs = np.zeros_like(tau_sobolevs.values)
        macro_atom.calculate_beta_sobolev(self.tau_sobolevs.values.ravel(order='F'),
                                          self.beta_sobolevs.ravel(order='F'))
        return beta_sobolevs
```

**Comment by wkerzendorf** [comment]
make a PR @liangjiaxing

**Comment by unoebauer** [comment]
@wkerzendorf: status of this? Is this still relevant after the plasma overhaul?
