### ISSUE TITLE
GUI project

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#264]
This project involves transforming the current rudimentary GUI into a more fully fletched analysis tool that will also allow TARDIS to be executed.

Suggestions for the PR: 
1. Get familiar with the code and the current problems pyside/pyqt
2. As seen on the ideas page the concentric shells are displayed as an Ellipse. Make the figure in a way that they are circles.

Over the summer:
1. Make sure the GUI runs on a wide array of platforms
2. Generate a input form for TARDIS yaml file
3. Run TARDIS and display the output.
4. Make this into a standalone application.

**Comment by LeKhan9** [comment]
I am interested in this project with my interests heavily vested in astrophysics/astronomy. I wanted to ask if the PR were taken to be part of the application process. In any case, I am also interested in a couple of the other projects, including: WebApp and "the hard one". In the case of the latter project I just listed, I do have experience with evolutionary algorithms/genetic algorithms, but my other skills do not match up. Would it be possible to apply some of my Artificial Intelligence experience into a side-project related to this. I've also research Neural Networks heavily over the past few years. Thank you for taking a look! :)

**Comment by wkerzendorf** [comment]
@LeKhan9 Google requires a PR to be part of the application process (which we also think is a sensible option). But apart from a requirement: Writing some of these PRs will enable you to write a much better application (with more details and more realistic timelines).

**Comment by G10h4ck** [comment]
I am very interested in this proposal, how i can comunicate with you (mailinglist ?), I have a lot of experiences in free and opensource software developing with Python, C/C++ and Qt and I also like astronomy but i am not an expert.

I would expand my knowldege participating to GSoC 2015 with this proposal.

Hope to read a reply from you soon!

**Comment by wkerzendorf** [comment]
Hi @G10h4ck. Yes mailing list or gitter.im/tardis-sn/tardis. Try to do the PR first.

**Comment by darshpandya18** [comment]
Hi.
I am interested in doing this project as a part of GSoC 2015. I have recently worked on a project of developing a data analysis tool using python. 
I am little late posting here, but can you please help me through.

**Comment by wkerzendorf** [comment]
@darshpandya18 To participate in GSoC you need to make an application and a proposal

**Comment by unoebauer** [comment]
This one is still relevant for GSoC 2016, right? @wkerzendorf

**Comment by unoebauer** [comment]
Should become a TEP....
