### ISSUE TITLE
Rename "model" property in benchmarks/transport_montecarlo_packet.py

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis#2648]
It could use a more descriptive name

@officialasishkumar

**Comment by officialasishkumar** [comment]
The file is changed with the recent PRs.

**Comment by andrewfullard** [comment]
> The file is changed with the recent PRs.

Which one?

**Comment by officialasishkumar** [comment]
1. https://github.com/tardis-sn/tardis/pull/2722
2. https://github.com/tardis-sn/tardis/pull/2717
