### ISSUE TITLE
Set Up is not Installing in Ubuntu 14.04

### ISSUE THREAD

**Issue by spyshiv** [tardis-sn/tardis#270]
I have ubuntu 14.04 Os in my laptop, and i have tried to install setup according to instructions but when i run command in terminal 
"sudo apt-get install python-dev python-pip python-numpy python-scipy python-h5py python-pandas python-yaml"   it works fine 
but when i run next line of instruction it failed to install
i ran this command 
"pip install astrophy --user"
and found errors something like that..

"Downloading/unpacking astrophy
  Could not find any downloads that satisfy the requirement astrophy
Cleaning up...
No distributions at all found for astrophy
Storing debug log for failure in /home/shiv/.pip/pip.log"

reply someone to this...thanks

**Comment by wkerzendorf** [comment]
hi,

please use the anaconda installation instructions

cheers,
    Wolfgang

**Comment by unoebauer** [comment]
@wkerzendorf - looks pretty straight foward. I'd close this.
