### ISSUE TITLE
No need to need benchmarks for different values of length for generate_rpacket_last_interaction_tracker_list.

### ISSUE THREAD

**Issue by Sumit112192** [tardis-sn/tardis#2777]
@officialasishkumar Currently the said benchmark runs for different values of length, which is not required.
The related code:
https://github.com/tardis-sn/tardis/blob/e1aa88723a6836e8a25cc1afb24b578b1b78651f/benchmarks/transport_montecarlo_packet_trackers.py#L33-L38

My question, was this intended? if not can you please remove that since it can increase the runtime of benchmark workflow.

**Comment by officialasishkumar** [comment]
Yeah it can be removed and the repeat can be set to 3 or 4 for better accuracy.
