### ISSUE TITLE
Issue with montecarlo.pyx file in build

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#291]
When I tried to build the current master branch

python setup.py build

I get a complaint about 

error: [Errno 2] Could not find C file tardis/montecarlo/montecarlo.c for Cython file tardis/montecarlo/montecarlo.pyx when building extension tardis.montecarlo.montecarlo. Cython must be installed to build from a git checkout.: 'tardis/montecarlo/montecarlo.c'

@mklauser pointed out that I can get around by going in and making the Cython file myself

cython montecarlo.pyx

However, it would be better if someone (@wkerzendorf) can modify the setup script to do this (it used to work?)

**Comment by wkerzendorf** [comment]
@ssim  can you clone into a new repository and try it there (maybe also trying the installation instructions)

**Comment by ssim** [comment]
@wkerzendorf 

Yes ok - I tried making a fresh clone now and indeed it worked without complaint on that. So I guess this is some oddness with my repository only. In which case this is probably not worth worrying about further. I will close this thread - thanks for the response!

**Comment by wkerzendorf** [comment]
For future reference, use `git clean -dfx` that will remove any file that is not in the currently tracked by git. This will make it a clean repository.
