### ISSUE TITLE
GSoC 2015 - Re-factor Montecarlo 

### ISSUE THREAD

**Issue by kaushik94** [tardis-sn/tardis#293]
- [x] Remove all the getter and setter functions and all the endpoints(ones which are accessible to user) to a separate file `montecarlo.c`
- [x] Functions like computing distances and other helper routines should be moved into separate file like `geometry.c`
- [x] Functions like binary search, linear search should be a separate file like `search_routines.c`

@wkerzendorf, @mklauser , @orbitfold  Please let me know what you guys think. Update the checklist with other ways you think appropriate.

**Comment by wkerzendorf** [comment]
I think that is a good start. The computing distances part is more a geometry task and should maybe go into `geometry.c`. I think a PR is the best way to proceed as one can much easier comment.
