### ISSUE TITLE
interpolate outside of 2000 and 50000 setting zeta to 1.

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#3]

**Comment by unoebauer** [comment]
@wkerzendorf, @ssim: I guess that this refers to the temperature grid for the zeta values...Not sure how the PR #395 relates to this....Is the interpolation actually an issue or kept for documentation purposes. If it's the latter, let's close this issue and put a note on the docu.

**Comment by unoebauer** [comment]
PR #395 is completely unrelated to this. However, in the course of the plasma overhaul, zetas were automatically set to 1 whenever the temperatures outside the grids are encountered. See ```tardis/plasma/ion_population.py```:

```python
    @staticmethod
    def get_zeta_values(zeta_data, ion_index, t_rad):
        zeta_t_rad = zeta_data.columns.values.astype(np.float64)
        zeta_values = zeta_data.ix[ion_index].values.astype(np.float64)
        zeta = interpolate.interp1d(zeta_t_rad, zeta_values, bounds_error=False,
                                    fill_value=np.nan)(t_rad)
        zeta = zeta.astype(float)

        if np.any(np.isnan(zeta)):
            warnings.warn('t_rads outside of zeta factor interpolation'
                                 ' zeta_min={0:.2f} zeta_max={1:.2f} '
                                 '- replacing with 1s'.format(
                zeta_data.columns.values.min(), zeta_data.columns.values.max(),
                t_rad))
            zeta[np.isnan(zeta)] = 1.0

        return zeta
```

Thus, this issue is resolved - closing!
