### ISSUE TITLE
Issue with anaconda install

### ISSUE THREAD

**Issue by orbitfold** [tardis-sn/tardis#321]
I get this when trying to install tardis on our cluster. Works after wget'ing conda-requirements.

```bash
di73kuj@login:~> conda create -n tardis --file https://raw.githubusercontent.com/tardis-sn/tardis/master/conda-requirements python=2 pip
�����΂����' in: https://raw.githubusercontent.com/tardis-sn/tardis/master/conda-requirements
```

**Comment by wkerzendorf** [comment]
I don't know why this is going on.

**Comment by souravsingh** [comment]
@wkerzendorf I think PR-https://github.com/tardis-sn/tardis/pull/424 will now fix this issue.

**Comment by unoebauer** [comment]
Does the problem still persist @orbitfold? Did PR #424 indeed fix this issue? Otherwise, close @wkerzendorf?
