### ISSUE TITLE
Masking lines still makes them not 'invisible'

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#33]
When Masking lines by setting tau_sobolev=0 it still sometimes happens that d_line is the smallest one and it jumps into the line evaluation procedure. 

This should not happen and must have something todo with electron scattering problems.

**Comment by unoebauer** [comment]
@wkerzendorf: I guess this has been resolved by now. Given also the lack of activity for more than two years, I am going out on a limb and close this one :)
