### ISSUE TITLE
New plasma structure / montecarlo interfacing issues

### ISSUE THREAD

**Issue by aoifeboyle** [tardis-sn/tardis#331]
@wkerzendorf @orbitfold I know we were going to have a proper chat at some point, but I thought I'd raise an issue just to clarify what the problem is here and see if we can sort it out. 

So this all refers to branch plasma/restructure. When I was trying to figure out some differences in the convergent temperatures when comparing the old and new plasma structures, I narrowed the problem down to the line 353 of model.py:

`montecarlo_nu, montecarlo_energies, self.j_estimators, self.nubar_estimators, \
last_line_interaction_in_id, last_line_interaction_out_id, \
self.last_interaction_type, self.last_line_interaction_shell_id = \
montecarlo.montecarlo_radial1d(self, virtual_packet_flag=no_of_virtual_packets)`

This module seems to read in just the `electron_densities` and `tau_sobolevs` properties of the plasma. So we found that the `tau_sobolevs` data took the form of a view rather than a copy, which was the biggest source of the error, but there was still a discrepancy. It turned out that I got the correct values (the same as those returned for the old plasma structure) if I sorted the `tau_sobolevs` values to have the same index as the `lines` data, but only if the `lines` data was indexed exactly as it was obtained from the atomic data file. If, for example, I reindexed the `tau_sobolevs` series so that the index was in ascending order, the montecarlo module would return the wrong values. 

Now the issue with this is that the new plasma structure uses the `selected_atoms` property as a key property. Its purpose is to retain the atomic data related to elements actually contained in the input model and to discard everything else. Although the model I use for testing contains all of the relevant elements (Z=2-30), the filtering process seems to reindex the lines data when reading it in. The `tau_sobolevs` property generated by the new plasma takes as its index `lines.index` and therefore the montecarlo module, as it seems to only read the tau values while disregarding the index, returns the wrong values. 

To get around this issue, I have modified tardis/plasma/properties/atomic.py (see PR #319) so that the `lines` data is forced to have the same index as comes from the original atomic data file. But this is a poor way of working around the issue, as it will not work properly when there are fewer elements involved (as the index will be shorter than the filtered list of lines). This works well enough for now that I can continue adding new properties to the plasma, but it's not a solution. 

So my two questions are:
1. Would it be ok if I removed the `selected_atoms` property from the new plasma structure, and just read in all of the atomic data regardless of the model? That would fix the issue but a lot of the other properties are dependent on this one, so I wanted to check it was ok first.
2. Could/should the montecarlo module be modified so that it takes account of the index of the `tau_sobolevs` input series, to ensure the correct answer regardless of the lines index?

Thanks for your help! If we can't get this worked out on here it would be great if we could have a Skype session sometime in the coming week.

**Comment by wkerzendorf** [comment]
This is very detailed and useful! I'll need to have a look later.

**Comment by wkerzendorf** [comment]
@aoifeboyle So a quick thing that we can and should do is maybe introducing a `MontecarloRunner` (name can be changed) class in the `montecarlo` subpackage (I always like to make a `base.py` file where to stuff this into). This would have an easy way to interface between the montecarlo part and the python part. This should also be the place where these `.copy('F')` operations should go. I think @aoifeboyle you can get started on this and then maybe also make sure that @kaushik94 is involved.

**Comment by aoifeboyle** [comment]
@wkerzendorf Is what I've done in PR #333 kind of what you were hoping for?

**Comment by unoebauer** [comment]
The concept of a MontecarloRunner has been realised. @aoifeboyle did this solve the interfacing issue?

**Comment by unoebauer** [comment]
Outdated - the concept of a ``runner`` class has been realized.

Closing
