### ISSUE TITLE
Missing conversions between lab frame and comoving frame opacities in cmontecarlo.c ?

### ISSUE THREAD

**Issue by chvogl** [tardis-sn/tardis#335]
@ssim @wkerzendorf
If we want to preserve O(v/c) accuracy in transforming between observer and comoving frame, there are in my opinion some Doppler factors missing in the cmontecarlo.c .

For example:
INLINE double
compute_distance2electron (rpacket_t * packet, storage_model_t * storage)
{
  if (rpacket_get_virtual_packet (packet) > 0)
    {
      return MISS_DISTANCE;
    }
  double inverse_ne =
    storage->
    inverse_electron_densities[rpacket_get_current_shell_id (packet)] *
    storage->inverse_sigma_thomson;
  return rpacket_get_tau_event (packet) * inverse_ne;
}

Since we want to calculate the distance to an electron scattering event in the observer frame, we would have to use the electron scattering opacity in the observer frame (electron density * cross section * Doppler factor).

**Comment by ssim** [comment]
Hi @chvogl 

This is a known issue - see #55 #55 and #57.

It has never been a high priority to fix (and isn't really now either) - but it's easy to do, so if you'd like to take this on that'd be great - but don't invest too much time right now!

**Comment by unoebauer** [comment]
Closing this one in favour of #448
