### ISSUE TITLE
Missing openmp compatability of chi_bf_tmp_partial array

### ISSUE THREAD

**Issue by chvogl** [tardis-sn/tardis#348]
The chi_bf_tmp_partial array in the storage is not thread safe yet.
(The array is used for storing the sum of bf-opacities up to a certain continuum_id and is used for selecting a bf-continuum for absorption.)

**Comment by unoebauer** [comment]
The extensions of @cvogl, summarised in #430 will not work with open-MP in the near future. We can keep this issue to remind us of this fact (or maybe create a milestone?), @wkerzendorf, @ssim?

**Comment by ssim** [comment]
Making a milestone of it is probably wise. What will happen at the moment? Does the code print out a warning (or abort or something) or will it just carry on anyway if you try to use them with openmp (and then find a wrong result)?

**Comment by unoebauer** [comment]
Hmm - good point. Currently we never use open-MP with #430. But we should add a safety guard to prevent running the code when open-MP is active. Could you elaborate on this, @chvogl?

**Comment by cvogl** [comment]
Looks as if you've added the wrong guy to your discussion:
I'm cvogl and have no clue about your extension #430.

/cav

**Comment by unoebauer** [comment]
Ups - sorry my bad - omitted an h.

**Comment by unoebauer** [comment]
Will be addressed by @chvogl soon-to-come PR

**Comment by chvogl** [comment]
Fixed by PR:#670
