### ISSUE TITLE
correct caligraph Rs to lower Rs in the NLTE 

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#359]
Should be easy to do

**Comment by souravsingh** [comment]
I wish to work in the issue.How do I start?

**Comment by wkerzendorf** [comment]
@souravsingh have a look in the documentation in the nlte rst file and find the latex caligraph Rs and change them to lower Rs

**Comment by souravsingh** [comment]
I have sent a Pull Request.But the Travis tests failed.

**Comment by souravsingh** [comment]
Here is the link to the PR-https://github.com/tardis-sn/tardis/pull/421

**Comment by souravsingh** [comment]
I will try once again to send a PR

**Comment by souravsingh** [comment]
The tests have failed.Here is the link to PR-https://github.com/tardis-sn/tardis/pull/422
