### ISSUE TITLE
use memory view in Storagemodel

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#36]
`cdef float_type_t[:,:,:] arbitrarily_np_array_view` works in class definition

**Comment by unoebauer** [comment]
@wkerzendorf: I strongly suspect that this is no longer relevant, given the transition from cython to C. I am closing this one on a hunch - reopen if I am wrong.

**Comment by wkerzendorf** [comment]
@unoebauer we are using memoryviews in the cython part of the code now. using this `[:, :]` notation are cython memory views.
