### ISSUE TITLE
New Plasma breaks to_hdf5 of model

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#378]
Issue based on revision d84d1f6

After the plasma overhaul, the model can no longer be saved to an HDF file (via to_hdf5). The reason seems to be that the properties requested in model.py

```python
include_from_plasma_ = {'level_populations': None, 'ion_populations': None, 
                                         'tau_sobolevs': None, 'electron_densities': None,
                                         't_rads': None, 'ws': None}
include_from_model_in_hdf5 = {'plasma_array': include_from_plasma_, 'j_blues': None,
```
are no longer saved in the model under `plasma-array`.

**Comment by aoifeboyle** [comment]
Just seeing this now @unoebauer. I can fix it.

**Comment by aoifeboyle** [comment]
I've just fixed it (I think). Can you check if it works for you?

**Comment by unoebauer** [comment]
Thanks @aoifeboyle for swiftly taking care of this! Works fine for me now.
