### ISSUE TITLE
Problem with ion populations in LegacyPlasmaArray

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#380]
Hello,

I'm playing around a bit with the GUI and am repeatedly running into the following error:

```
Traceback (most recent call last):
  File "/Users/stuartsim/Tardis/tardis/build/lib.macosx-10.10-x86_64-2.7/tardis/gui/widgets.py", line 753, in on_atom_header_double_clicked
    self.table2_data = self.parent.model.plasma_array.ion_populations[
  File "/Users/stuartsim/Tardis/tardis/build/lib.macosx-10.10-x86_64-2.7/tardis/plasma/base.py", line 28, in __getattr__
    super(BasePlasma, self).__getattribute__(item)
AttributeError: 'LegacyPlasmaArray' object has no attribute 'ion_populations'
```

I'm not 100% clear what the LegacyPlasmaArray is doing, but I assume this is something to do with the recent changes. Can you help,  @aoifeboyle ?

In my configuration file I'm currently using:

```
plasma:
    ionization: nebular
    excitation: dilute-lte
    radiative_rates_type: dilute-blackbody
    line_interaction_type: scatter
```

is that all still fine, or do I need to do something else with the new plasma?

**Comment by aoifeboyle** [comment]
Yeah I know what it is actually! That property has been renamed `ion_number_density` in the new plasma. Sorry, I should have gone through the gui to correct those terms. I'll do it now.

**Comment by ssim** [comment]
Great - thanks!

**Comment by aoifeboyle** [comment]
@ssim It seems to work for me now! Let me know if it works for you.

**Comment by ssim** [comment]
@aoifeboyle Looks good - seems to be working for me now too! Thanks for fixing. I will close this issue now. 

Thanks!
