### ISSUE TITLE
Monte Carlo: inconsistent usage of rpacket accessor functions and members

### ISSUE THREAD

**Issue by mreineck** [tardis-sn/tardis#388]
The rpacket struct has a complete set of getter and setter functions, but in several places throughout cmontecarlo.c, its members are accessed directly (just grep for "packet." or "packet->" in this file).
It would be nice to harmonize this and either use only accessors or remove them.
Since the current accessor functions don't try to preserve any kind of invariant, both solutions are equivalent from a correctness view. Personally I consider direct access to the data member more readable.
I'm happy to provide patches for either solution.

**Comment by orbitfold** [comment]
I'm for keeping accessors, I find accessor code more readable. Plus it's

**Comment by mreineck** [comment]
OK, I'll provide a PR shortly.

**Comment by mreineck** [comment]
Fixed.
