### ISSUE TITLE
Montecarlo: Missing dependencies in the build script

### ISSUE THREAD

**Issue by mreineck** [tardis-sn/tardis#390]
If I run "python setup.py develop --user", then make a change to any of ther .h files in tardis/montecarlo/src/ and finally run "python setup.py develop --user" again, the C files are not recompiled as they should be. This dependency on the header files should somehow be added to the build script in question (I expect that it is tardis/montecarlo/setup_package.py), but I don't know how this can be done.

**Comment by mreineck** [comment]
Same problem with the dependency between .pyx and .c files ... cython does not seem to be re-run automatically whenever a .pyx file is changed.

**Comment by mreineck** [comment]
Another observation: if I delete a .c file by hand that was originally created by Cython, the compilation proces fails completely:
```
/scratch/martin/mytardis2>python setup.py develop --user
running develop
running egg_info
writing requirements to tardis_sn.egg-info/requires.txt
writing tardis_sn.egg-info/PKG-INFO
writing top-level names to tardis_sn.egg-info/top_level.txt
writing dependency_links to tardis_sn.egg-info/dependency_links.txt
writing entry points to tardis_sn.egg-info/entry_points.txt
reading manifest file 'tardis_sn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGES.rst'
warning: no files found matching '*.c' under directory '*.pyx'
warning: no files found matching '*.pxd' under directory '*.pyx'
warning: no files found matching '*.h' under directory '*.pyx'
warning: no files found matching '*' under directory 'licenses'
warning: no files found matching '*' under directory 'cextern'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'tardis_sn.egg-info/SOURCES.txt'
running build_ext
error: [Errno 2] Could not find C file tardis/montecarlo/montecarlo.c for Cython file tardis/montecarlo/montecarlo.pyx when building extension tardis.montecarlo.montecarlo. Cython must be installed to build from a git checkout.: 'tardis/montecarlo/montecarlo.c'
```

This happens despite the fact that Cython was working perfectly well when I first compiled the package directly after cloning from Github.

I have no idea what's happening here.

**Comment by wkerzendorf** [comment]
@embray - this is using the astropy setup tools. Any idea why?

**Comment by embray** [comment]
Something seems to be awry here:
```
warning: no files found matching '*.c' under directory '*.pyx'
warning: no files found matching '*.pxd' under directory '*.pyx'
warning: no files found matching '*.h' under directory '*.pyx'
```

**Comment by embray** [comment]
The syntax on this line is wrong: https://github.com/tardis-sn/tardis/blob/master/MANIFEST.in#L8

**Comment by embray** [comment]
(Note, I don't know for sure if that's the reason for the problem, but I've never had any problem like this--if `./setup.py develop` isn't doing it try `./setup.py build_ext --inplace`.  The latter is what I usually re-run when I'm testing extension modules rather than re-running `develop` over and over (which is more like running `install` over and over).

**Comment by mreineck** [comment]
Thanks for pointing out the syntax error!
Unfortunately the behaviour doesn't change...
```
/scratch/martin/tardis>touch  tardis/macro_atom.pyx
/scratch/martin/tardis>python setup.py build_ext --inplace
running build_ext
copying build/lib.linux-x86_64-2.7/tardis/montecarlo/montecarlo.so -> tardis/montecarlo
copying build/lib.linux-x86_64-2.7/tardis/macro_atom.so -> tardis
/scratch/martin/tardis>rm tardis/macro_atom.c      
/scratch/martin/tardis>python setup.py build_ext --inplace
running build_ext
error: [Errno 2] Could not find C file tardis/macro_atom.c for Cython file tardis/macro_atom.pyx when building extension tardis.macro_atom. Cython must be installed to build from a git checkout.: 'tardis/macro_atom.c'
/scratch/martin/tardis>cd tardis
/scratch/martin/tardis/tardis>cython macro_atom.pyx 
/scratch/martin/tardis/tardis>
```

**Comment by unoebauer** [comment]
This is related to #376.

**Comment by chvogl** [comment]
@wkerzendorf 
The problem that cython does not re-run automatically whenever a .pyx file is changed, can seemingly be fixed by adding the following line of code:  

    from Cython.Build import cythonize
    package_info['ext_modules'] = cythonize(package_info['ext_modules'])

**Comment by unoebauer** [comment]
We should still try to address this issue.

As a workaround, the ``git clean -dfx`` approach helps... 
**WARNING** this will delete all files which are currently not under version control, so be careful! You can inspect the files that would be deleted by this operation with ``git clean -dfxn``

**Comment by unoebauer** [comment]
We have adopted the ``git clean -dfx`` strategy - closing.
