### ISSUE TITLE
Monte Carlo: bug in OpenMP mode

### ISSUE THREAD

**Issue by mreineck** [tardis-sn/tardis#393]
If I understand the code correctly, there is currently a serious problem when running the Monte Carlo part in parallel:
There is a global variable mt_state, which holds the state of the random number generator. Yet every thread treats this variable as if it were their own private copy.

Here an example from montecarlo_main_loop():
#pragma omp parallel
  {
    initialize_random_kit(seed + omp_get_thread_num());
[...]

This causes concurrent writes to mt_state, leaving its contents undefined.

We need to find a way to give every thread its own private mt_state.

**Comment by orbitfold** [comment]
I'm aware of this problem. I'm going to fix it.
Išsiųsta BlackBerry® paštu iš Bitės

-----Original Message-----
