### ISSUE TITLE
Montecarlo tests still doing unrealistic things

### ISSUE THREAD

**Issue by mreineck** [tardis-sn/tardis#408]
After some work, the tests in test_cmontecarlo.c now do proper setup and tear-down of their environment and can be executed in arbitrary order.
Unfortunately they still have the unrealistic prerequisite that their random number generator has an internal state which is identically zero. I have not verified it, but this typically means that the RNG will produce only zeroes, or in any case behave in a much different way than it would after proper initialization.
The situation is like this because RNG initialization was simply forgotten when the tests were written, and in C the default behaviour is to initialize everything with zero.
At some point we need a plan what these tests are actually supposed to achieve. If the main goal is an implicit verification that the interface of the C routines has not changed, we can probably stick to what we currently have. If more is desired, we need thourough redesign of this source file.

**Comment by unoebauer** [comment]
Things have changed - no longer relevant.

Closing
