### ISSUE TITLE
Deal with missing zeta data in a more sensible way

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#411]
https://github.com/tardis-sn/tardis/blob/master/tardis/plasma/properties/ion_population.py#L67

extend the interpolation.

**Comment by aoifeboyle** [comment]
In the old plasma I made it so that the zeta values for the highest temperature available were used even for temperatures exceeding that value. Do you want me to just implement that again here?

**Comment by wkerzendorf** [comment]
@aoifeboyle I think such an extrapolation would be good. The second small issue is that when complaining about missing zeta values that it doesn't specify which ones. It would be good to at least say which atoms. What do you think?

**Comment by aoifeboyle** [comment]
Sure! I can try to do that. Shouldn't be a problem.

**Comment by wkerzendorf** [comment]
@aoifeboyle don't be alarmed but currently the master is broken. There is an issue with pytest. I should have fixed it by now.

**Comment by aoifeboyle** [comment]
@wkerzendorf Ok, I assume that's why my Travis build isn't working? I'm just relieved it's not something I've done!

**Comment by wkerzendorf** [comment]
@aoifeboyle yes it was a problem with new versions of pytest and coverage. It should all be fixed now.

**Comment by wkerzendorf** [comment]
@aoifeboyle I think this issue is fixed - right? If you agree, just close the issue.
