### ISSUE TITLE
Segmentation fault with lots of packets (important)

### ISSUE THREAD

**Issue by aoifeboyle** [tardis-sn/tardis#428]
I'm getting a segmentation fault on the last iteration of every simulation I run with a large number of packets, whether I run it on my desktop, the virtual server or one of the MPA servers. My Tardis version is up to date and I've checked that my python packages are all up to date too. Would anyone be able to run this and see if they can reproduce the issue? I'm running it without OpenMP.

Here's my config file, and the model/abundances files are attached.

tardis_config_version: v1.0

supernova:
    luminosity_requested: 8.97 log_lsun
    time_explosion: 14.0 day
    
atom_data: ../supernova_models/aoife.h5

model:
    structure:
        type: file
        filename: ../supernova_models/LM_model.txt
        filetype: artis
        v_inner_boundary: 6250 km/s
        v_outer_boundary: 36000 km/s

abundances:
        type: file
        filetype: artis
        filename: ../supernova_models/LM_abundances.txt

plasma:
    ionization: nebular
    excitation: dilute-lte
    radiative_rates_type: dilute-blackbody
    line_interaction_type: scatter
    helium_treatment: none

montecarlo:
    seed: 23111963
    no_of_packets : 1.0e+6
    iterations: 30
    last_no_of_packets: 1.0e+6
    no_of_virtual_packets: 5

spectrum:
    start: 500 angstrom
    stop: 20000 angstrom
    num: 10000

[LM_abundances.txt](https://github.com/tardis-sn/tardis/files/18299/LM_abundances.txt)
[LM_model.txt](https://github.com/tardis-sn/tardis/files/18300/LM_model.txt)

**Comment by aoifeboyle** [comment]
@wkerzendorf

**Comment by wkerzendorf** [comment]
any memory issues? What memory was consumed?

**Comment by orbitfold** [comment]
Run it through valgrind and post the results. It will run very slowly. Just install valgrind and do:

Valgrind tardis ...

For me this usually provides enough info what caused the segfault.
Išsiųsta BlackBerry® paštu iš Bitės

-----Original Message-----

**Comment by aoifeboyle** [comment]
For the MPA server simulation, it said 'max vmem' was 14.313G, and 20G was allowed. 

Here's the error output as well: 

Traceback (most recent call last):
  File "tardis_script_1.py", line 8, in <module>
    model = run_tardis('../supernova_models/tardis_config_1.yml', '../aoife.h5')
  File "/afs/mpa/home/aoife/tardis/build/lib.linux-x86_64-2.7/tardis/base.py", line 42, in run_tardis
    simulation.run_radial1d(radial1d_mdl)
  File "/afs/mpa/home/aoife/tardis/build/lib.linux-x86_64-2.7/tardis/simulation.py", line 41, in run_radial1d
    initialize_j_blues=initialize_j_blues)
  File "/afs/mpa/home/aoife/tardis/build/lib.linux-x86_64-2.7/tardis/model.py", line 315, in simulate
    nthreads=self.tardis_config.montecarlo.nthreads) #self = model
  File "/afs/mpa/home/aoife/tardis/build/lib.linux-x86_64-2.7/tardis/montecarlo/base.py", line 97, in run
    nthreads=nthreads)
  File "tardis/montecarlo/montecarlo.pyx", line 243, in tardis.montecarlo.montecarlo.montecarlo_radial1d (tardis/montecarlo/montecarlo.c:3396)
    cdef np.ndarray[int_type_t, ndim=1] virt_packet_last_interaction_type = np.zeros(storage.virt_packet_count, dtype=np.int64)
MemoryError

**Comment by wkerzendorf** [comment]
that is still quite a bit.

**Comment by aoifeboyle** [comment]
@orbitfold Does the error output I posted above help or should I still run the valgrind thing?

**Comment by orbitfold** [comment]
I think there might be a memory leak..? In that case using valgrind makes sense. If you know how to find memory leaks with it then go ahead, otherwise I can try it once I have a spare minute.

**Comment by aoifeboyle** [comment]
@orbitfold It would be really great if you could do it for me at some point. I've given way too much time to this problem already and I need to get back to my cosmology stuff. Thanks. It would even just be really great if you or @wkerzendorf could just run my code and see if you get the same problem.

**Comment by orbitfold** [comment]
Well it doesn't matter even if we don't. As long as someone runs in to it then it is a problem.

**Comment by aoifeboyle** [comment]
@orbitfold @wkerzendorf Have either of you made any progress on this?

**Comment by orbitfold** [comment]
Where do I get the atom data?

**Comment by aoifeboyle** [comment]
https://www.dropbox.com/s/l1oy1pncc5sxhd1/aoife.h5?dl=0

**Comment by orbitfold** [comment]
During the last iteration it seems to be leaking memory at a more or less constant rate until it runs out, which is why you get the MemoryError when an array of zeros is being allocated. I don't get this error, but my TARDIS run is killed when it runs out of memory. Running valgrind with this will take a couple of days. Maybe I can use opensupernova.org for that? Unless someone has any ideas where it might leak during the last iteration.

**Comment by orbitfold** [comment]
For the mean time I'll switch of virtual packet logging, make it optional, maybe that will solve it.

**Comment by aoifeboyle** [comment]
Thank you @orbitfold.

**Comment by aoifeboyle** [comment]
@orbitfold @wkerzendorf Still having some problems. I ran 6 Tardis simulations on the MPA servers. 3 ran with no issues. The other 3 seemed to get stuck in some kind of loop, because they ran for almost 24 hours each and were still stuck on the first (or in one case second) iteration. There were only basic differences between the config. files of the ones that ran and didn't run, e.g. luminosity, time since explosion. Any suggestions? I tried to debug the issue but I don't really know enough about this part of the code.

**Comment by orbitfold** [comment]
Well the files would be helpful. Also maybe start a new issue?

**Comment by aoifeboyle** [comment]
Exact same files as before.

**Comment by orbitfold** [comment]
You said in the comment before that there were basic differences?

**Comment by aoifeboyle** [comment]
Just the times and luminosities (7 and 21 days, 8.87 and 8.91 log_lsun for the runs that failed). Also I didn't start a new issue because it's the same problem as before. I've tried running with fewer packets (e.g. 10^4) and it works fine. Some of the runs completed but we obviously haven't gotten the whole issue.

**Comment by orbitfold** [comment]
I don't think it's necessarily related.

**Comment by unoebauer** [comment]
After talking with @aoifeboyle, I got the impression that this problem is no longer an issue and was basically resolved by introducing the vpacket-logging capability. Thus, I'd consider this one solved and would close it, unless there are objections, @aoifeboyle, @wkerzendorf, @orbitfold

**Comment by wkerzendorf** [comment]
not from my point of view. good work @aoifeboyle @unoebauer !

**Comment by aoifeboyle** [comment]
@unoebauer Agreed!

**Comment by unoebauer** [comment]
Perfect - officially closing this one - another job well done, @orbitfold, @aoifeboyle, @wkerzendorf
