### ISSUE TITLE
Ambiguity in field type for webapp

### ISSUE THREAD

**Issue by utkbansal** [tardis-sn/tardis#437]
Hi! I was working on creating the web form for the config file generation.
The sample config definition file found [here](https://github.com/tardis-sn/tardis/blob/master/tardis/data/tardis_config_definition.yml) defines a property type named quantity. What would this be? A string, int or float?

**Comment by utkbansal** [comment]
@wkerzendorf could you please help me?

**Comment by wkerzendorf** [comment]
a quantity is a float with a string attached. In the end it is '8 km/s' for example

**Comment by utkbansal** [comment]
@wkerzendorf  and what is the significance of container-property ? How are they supposed to be rendered in the form?

**Comment by wkerzendorf** [comment]
@utkbansal sorry for the slow responses currently really busy. The container properties tell us that we can have multiple input ways here. I'm actually thinking that they might not be that useful anymore and that we might want to use yaml tags for this http://pyyaml.org/wiki/PyYAMLDocumentation#YAMLtagsandPythontypes. In general then we would also use the jsonschema for validating our input file. This is actually an interesting project.

**Comment by utkbansal** [comment]
No problem. I myself have been stalling this for quite some time now. Could you please have a look at [here](http://tardis.utkarshbansal.me) and direct me further if the YAML thing might change.

**Comment by wkerzendorf** [comment]
this works for one of the sections in the yaml file, but not for the others. I think the YAML thing change could be an interesting project. The reason why I mentioned it is to see if you are interested in this. I presume you are doing this for GSoC 2016. We are not sure if GSoC 2016 will have a web interface project.

**Comment by utkbansal** [comment]
Yes, I am interested in GSoC 16. Though I'm still interested in the webapp and we still need it do be done, right? Would anything related to this be in GSoc 16?  What work would have have to be done for the YAML change thing?

**Comment by wkerzendorf** [comment]
@utkbansal well it is something that we are interested in, but we realized in the last months that the priorities will lie elsewhere. The YAML change can be something as simple as introducing YAML tags for quantities in the first instance.

**Comment by utkbansal** [comment]
@wkerzendorf in that case what can I help on as of now?

**Comment by wkerzendorf** [comment]
@utkbansal well look at YAML tags and see if you can make a YAML tag for quantities.

**Comment by utkbansal** [comment]
@wkerzendorf okay, I'll try and let you know.
