### ISSUE TITLE
Tardis build system oddness: changing conditional compilation flags doesn't have desired effect

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#451]
Building tardis with Open-MP support by using

``` sh
./setup.py build install --with-openmp
```

after having **first** built it without Open-MP support 

``` sh
./setup.py build install
```

does not trigger the required re-compilation to actually activate Open-MP. The same behaviour can be observed when working with the other conditional compilation flag, `--with-vpacket-logging`

Only when cleaning the repository between the two steps with

```
git clean -dfx
```

Open-MP is properly switched on.

Any ideas, @orbitfold, @wkerzendorf?

**Comment by yeganer** [comment]
I think that problem can't be solved easily with the available tools.

A workaround is to use the `--force` option like so:
```./setup.py build --with-openmp --force```

**Comment by wkerzendorf** [comment]
@yeganer The build system is based on https://github.com/astropy/package-template -- can you see if you can reproduce this problem there. Then we can some of the astropy people and they will also think about fixing this.

**Comment by yeganer** [comment]
@wkerzendorf from what if have read about setuptools and the python setup system is, that it is not designed to be recompiled when compiler flags change.

Since i've only worked with makefiles yet i can confirm that running `make clean && make` is quite common when changing something in the Makefile or when using different compiler flags.

As far as i know, setuptools doesn't save the configuration of the build, so there is no way of telling how the current code was compiled.

What needs to be tested is if ```./setup.py build --with-openmp --force``` correctly rebuilds everything that's needed or if a ```git clean -dfc`` is mandatory.

**Comment by wkerzendorf** [comment]
@yeganer I think that will be the case here as well -- there is a `python setup.py clean` and the `--force` option you suggest is also a sensible idea. 

The `package-template` does contain a `.pyx`-`cython` file however. @unoebauer also had the trouble that changing the pyx file or c file did not trigger recompilation. My idea (and I wasn't very clear on that) was to use `package-template` and build a minimum working example - to showcase the problem.

**Comment by yeganer** [comment]
Building a minimal working example seems like a good idea. What should be integrated there? Cython Interface to C function with different compiler flags. Anything else?

We fixed the problem of cython not recompiling by calling cythonize(Extension(...)) which should be the preferred method anyway.

As far, as i know, there is no build test yet. Perhaps we should write something in that direction.
That way we could test IF the code is compiling and if every build option is working.

**Comment by unoebauer** [comment]
Closing this one since ``git clean -dfx` is our generally agreed upon strategy.
