### ISSUE TITLE
Open-MP number of threads not properly returned in info string

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#454]
I think this one was introduced by PR #452: when running with Open-MP, the information message does not provide the correct number of threads. Instead, it seems to always return 1:

```
Running with OpenMP - 1 threads
```
I've requested 16 threads in the yml file and my process manager confirms that 16 threads are indeed opened.

**Comment by yeganer** [comment]
After merging #457 this can be closed.

**Comment by yeganer** [comment]
Closing since #457 is merged.

**Comment by unoebauer** [comment]
Re-opening this one since PR #457 is **not** yet merged!
