### ISSUE TITLE
Running GUI

### ISSUE THREAD

**Issue by pfreddy** [tardis-sn/tardis#459]
Hopefully, it is the right place to ask about this GUI issue.
I've just tried running GUI after the recommended installation:

>source activate tardis
>conda install ipython=3.0.0 pyside=1.2.1 shiboken=1.2.1

>export QT_API=pyside
>ipython --pylab=qt4

>>> from tardis import run_tardis
>>> model = run_tardis(...)

The model is properly calculated by TARDIS. 

>>> from tardis.gui import interface

ImportError                               Traceback (most recent call last)
<ipython-input-3-06cf3ee12674> in <module>()
----> 1 from tardis.gui import interface

ImportError: cannot import name interface

So basicly, interface.py is not found. Did I miss anything?

**Comment by wkerzendorf** [comment]
@pfreddy I just checked this and it is working with the newest version of TARDIS. can you make sure that you use the exact setup we describe in the Manual.

**Comment by pfreddy** [comment]
I tried again, from the installation (both 1.0.1 and development version) to the GUI.
Now, a new error message appeared:

>>> ImportError: libpng15.so.15: cannot open shared object file: No such file or directory

The lack of this file comes up both at the launch of ipython and the line 'from tardis.gui import interface'.
However, the interactive mode  and model calculation work fine in ipython.

**Comment by wkerzendorf** [comment]
are you using anaconda?

**Comment by pfreddy** [comment]
Yes.
Basicly, I did the next commands (after the installation of Anaconda):

> conda create -n tardis --file https://raw.githubusercontent.com/tardis-sn/tardis/master/conda-requirements python=2 pip
> source activate tardis
> pip install tardis-sn      (or the development version)
> conda install ipython=3.0.0 pyside=1.2.1 shiboken=1.2.1
> cd tardis_example
> export QT_API=pyside  (I also tried to set manually in the bash)
> ipython --pylab=qt4

**Comment by pfreddy** [comment]
There is no error message (ImportError: libpng15.so.15...), when I do not install the newest ipython (conda install ipython=3.0.0). However, in this case I cannot run TARDIS interactively (and it does not find the interface).

With the installation of ipython=3.0.0, the interactive TARDIS runs properly, but after the importation of the interface I get the error message (ImportError: libpng15.so.15...) back.

**Comment by wkerzendorf** [comment]
hmm the newest version of `ipython` is 4.0. This doesn't seem like a tardis related bug. Ill have a look at this later.

**Comment by pfreddy** [comment]
Finally, it works!

It was the matplotlib. After I installed the newest version with conda, the interface.py was able to start.
Thank you for your help!

**Comment by wkerzendorf** [comment]
@pfreddy great! well let me know if there are any other questions. closing this now
