### ISSUE TITLE
Clicking on the Link to AstroPy's workflow leads to error.

### ISSUE THREAD

**Issue by souravsingh** [tardis-sn/tardis#467]
Clicking on the link for Devlopment Workflow for AstroPy leads to a 404 error.This issue can be fixed by modifying the docs.

**Comment by unoebauer** [comment]
Thanks for pointing this out - the correct link seems to be:

http://astropy.readthedocs.org/en/latest/development/workflow/maintainer_workflow.html

This is easily fixed by modifying the corresponding documentation file

**Comment by yeganer** [comment]
PR #469 is merged. Closing.
