### ISSUE TITLE
test_atomic.py:test_atomic_reprepare() improve logic

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#473]
Currently `test_atomic.py:test_atomic_reprepare()` only checks `if len(lines) > 0`.

To improve it's logic and the coverage two improvements come to my mind:
- Rewrite to check `if len(lines) == N`. To get `N` the best approach would be to open the atomic data file, extract the lines, filter them and count them. 
- In a second step one could parametrize the function to work for different `atomic_numbers`. This would ensure that everything is working as expected. ( see pytest.mark.parametrize )

**Comment by unoebauer** [comment]
This sounds very reasonable to me. We should adopt this. Other thoughts, @wkerzendorf?

**Comment by yeganer** [comment]
I think this issue would be a great exercise for GSoC students. That's why i didn't implement it right away.

**Comment by unoebauer** [comment]
Good idea

**Comment by wkerzendorf** [comment]
@yeganer thanks!

**Comment by unoebauer** [comment]
Let's try to close this issue by adopting #476!
