### ISSUE TITLE
Tardis randomly crashing

### ISSUE THREAD

**Issue by aoifeboyle** [tardis-sn/tardis#477]
@wkerzendorf

Tardis randomly commits suicide for some simulations. At the moment, only two of the simulations have finished, and the one that failed is the one where I used 5x10^6 packets instead of 1x10^6 packets, so I'm hoping this issue will only arise in the former case. Here is the output I get: 
```
   tardis.simulation.base - INFO - Remaining run 10
   Running with OpenMP - 1 threads
   /var/spool/sge/MPA/lnx-8/job_scripts/3241: line 17: 11526 Killed python tardis_script_01.py
```
Any input on this would be appreciated. I will update when I know how the other simulations finished. If this only occurs with the larger number of packets, I may just run the simulations for 20 iterations instead of 30 and hope there's sufficient convergence (the higher number of packets is only used in 2 of my 12 simulations).

I was also wondering if anyone has been getting the following pytables error:

```
py.warnings - WARNING - /afs/mpa/home/aoife/anaconda/envs/tardis/lib/python2.7/site-packages/pandas/io/pytables.py:2577: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->values] [items->None]

  warnings.warn(ws, PerformanceWarning)
```

Aoife

**Comment by yeganer** [comment]
@aoifeboyle Can you please upload a zip containing all the files you used ( yaml + abundances + densities + atom_data in case it's different). Which tardis commit were you using?

**Comment by aoifeboyle** [comment]
@yeganer I was using the current master. The zip file with everything was too big to upload to github, so you can download it from my dropbox here: https://www.dropbox.com/s/cxwxpdn4glabpc4/tardis_config_01.zip?dl=0

Thanks for looking at this for me!

**Comment by yeganer** [comment]
@aoifeboyle So i ran your setup on my notebook. That's why it took me so long, sorry.
It didn't crash for me. I attached gdb in the 27th iteration i think and let it run until the last iteration and in the last iteration i stepped through the packets in blocks of ~1e6. I didn't notice any increase in memory usage (~1.2 GB all the time).

I have no idea if attaching gdb can affect the outcome.
If you need data from the model, tell me what you need, I can give it to you, the model is still open in an IPython shell.

Can you provide more information about the crash? I.e. why it was killed ( I assume it exceeded the specified memory )
Did you compile with `./setup.py develop --with-openmp`? Since that's what i used.
The last thing i can think of may be some incompatibility between loaded modules. The warning you received mentioned pandas. I didn't get that warning.

**Comment by aoifeboyle** [comment]
@yeganer Thank you very much for doing that. When I had this problem originally, it only crashed sometimes, so hopefully the same is true here. I'm re-running that particular simulation now, so I'll let you know if it crashes again. Don't worry about the data, I'll hopefully manage to get it myself. The funny thing is that the simulation doesn't seem to use up the specified memory, but I will have a look again to be sure.

**Comment by yeganer** [comment]
@aoifeboyle Have you checked CPU time? I'm not yet familiar with MPA's grid engine but from where I have my experience, I had to specify CPU time and memory usage when submitting jobs and anything that exceeded that got killed.

Maybe you find something in the logs.

**Comment by orbitfold** [comment]
>    tardis.simulation.base - INFO - Remaining run 10
>    Running with OpenMP - 1 threads
>    /var/spool/sge/MPA/lnx-8/job_scripts/3241: line 17: 11526 Killed python tardis_script_01.py

This does looks like something that a scheduler would say after killing a process. Presumably because a time or memory limit was exceeded.

**Comment by yeganer** [comment]
I noticed that, too. But if i remember correctly, SGE(Sun Grid Engine) prints something to the logs when it kills a process.

**Comment by aoifeboyle** [comment]
Sorry for my slow replies (I had to sit an exam for IMPRS on Thursday so I was super busy). I managed to get the simulation above to run the whole way through on the second try. I have two supernova models and six simulations for each. 
For my first batch (the ones I was running when I raised this issue), I have two simulations that require 5x10^6 packets and four that only need 10^6. I managed to get the first simulation of that set (the one specified above) to finish on the second try, but the second simulation with the greater number of packets is now on its third try. Of the other 4, two failed the first time but ran the second time. So I'm now just waiting for one simulation from that batch. Once they are all done I will check the results are consistent with what I had previously. 
The second batch are causing weirder problems. Each requires 10^6 packets. For this batch, all of the simulations finish but they break when writing the output to the hdf files, so I end up with files that only have a fraction of the information in them that they're supposed to, and in each case the data written to the file breaks off at the exact same point it seems. I checked that I have enough storage on my computer. I'm going to try running one of these on my desktop rather than on the MPA server to see if that makes a difference, but if the cause of this jumps out at any of you please let me know.

**Comment by aoifeboyle** [comment]
Correction: It seems that the second batch of simulations actually did not run. I assumed they did because something got saved to the hdf5 files (a spectrum) but I guess this is just from the first iteration or so. The second batch of simulations are running on my laptop but not on my MPA desktop. I think this must be something to do with the conda environments so I'm comparing those now.

**Comment by unoebauer** [comment]
@aoifeboyle, @yeganer 
I ran the setup that you posted above on nct-2, using 16 threads. Since this machine is not a server and not part of the queue systems, there are no CPU time or memory limits. It ran without problems (I did it interactively from within ipython):
```
Running with OpenMP - 16 threads
        [100%] Packets(finished/total): 5000000/5000000
tardis.simulation.base - INFO - Finished in 29 iterations and took 19784.27 s
```

Maybe we discuss briefly on Monday in person potential pitfalls on the MPA IT infrastructure...

**Comment by aoifeboyle** [comment]
@unoebauer Thanks. Hopefully my one remaining simulation from the first batch will finish this time, but if not I will run it on nct-2 (am I allowed?). I've figured out the issue with my conda environment that was causing issues with my second batch of simulations, and those are now running, so it's just this one simulation that I'm waiting for.

**Comment by aoifeboyle** [comment]
@unoebauer The simulation that is now struggling to finish for me on the MPA system is actually identical to the one included above, but in the config file it uses:
```
helium_treatment: recomb-nlte
```
instead. Could you run that for me on nct-2 and forward the results to me? Thanks!

**Comment by unoebauer** [comment]
@aoifeboyle - sure thing.

**Comment by unoebauer** [comment]
@aoifeboyle The setup is running (with 8 threads). I'll let keep you updated.

**Comment by unoebauer** [comment]
@aoifeboyle The run finished without problems - it's still open within an ipython session.

Based on all the information we gathered here, I'd say it is safe to assume that there is nothing fundamentally wrong with Tardis leading to the suicidal behaviour reported in this issue. Instead, the intricacies of the IT infrastructure at MPA seems to be responsible for that.

If we all agree on that, @aoifeboyle, @yeganer, @orbitfold, @wkerzendorf, we can close this one.

**Comment by yeganer** [comment]
I agree with you, this doesn't seem like an issue with tardis. I'm for
closing.

Ulrich Noebauer <notifications@github.com> schrieb am Di., 16. Feb. 2016
09:54:

**Comment by aoifeboyle** [comment]
Agreed!

**Comment by wkerzendorf** [comment]
@unoebauer I wouldn't say that there is nothing fundamentally wrong with TARDIS - just this problem is not one of them :wink: -- closing
