### ISSUE TITLE
test_simulation.py fails with the latest version of numpy

### ISSUE THREAD

**Issue by mishinma** [tardis-sn/tardis#478]
@yeganer @unoebauer @wkerzendorf 
In PR #471 the following (a few of them actually) asset statement was added to test_simulation.py:
```
npt.assert_allclose(
            t_rad, simulation_compare_data['test1/t_rad'], atol=0.0)
```
It is calculated like this: absolute(`a` - `b`) <= (`atol` + `rtol` * absolute(`b`))
The problem here is that t_rad is a Quantity while simulation_compare_data['test1/t_rad'] is just a numpy array. And if somehow works with numpy v 1.9.0, with v 1.10 it fails. An error is raised in the `__array_prepare__` method that is overridden in Astropy:

```

try:
                if _can_have_arbitrary_unit(maybe_arbitrary_arg):
                    converters = [None, None]
                else:
                    raise UnitsError("Can only apply '{0}' function to "
                                     "dimensionless quantities when other "
                                     "argument is not a quantity (unless the "
                                     "latter is all zero/infinity/nan)"
>                                    .format(function.__name__))
E                                    UnitsError: Can only apply 'subtract' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
```

**Comment by mishinma** [comment]
Actually, it would be nice to compare Quantities with a special util function that would validate the units of its arguments. One version of such a function is implemented in Astropy's [module tests/helpers.py]( https://github.com/astropy/astropy/blob/master/astropy/tests/helper.py ): assert_quantity_allclose

**Comment by yeganer** [comment]
I think the right approach should be to use astropy's assert_quantity_allclose. One would have to test if that solution is compatible with different versions of numpy and astropy.

**Comment by mishinma** [comment]
But units still should be added to the tests. `assert_quantity_allclose still` raises an error in this case as well, although with more clear message:

```
(Pdb) assert_quantity_allclose(t_rad, simulation_compare_data['test1/t_rad'], atol=0.0)
*** UnitsError: Units for 'desired' () and 'actual' (K) are not convertible
(Pdb) npt.assert_allclose(t_rad, simulation_compare_data['test1/t_rad'], atol=0.0)
*** UnitsError: Can only apply 'subtract' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
```

**Comment by yeganer** [comment]
So we have two options. Strip the result of its unit or add the unit to the
compare data. In that case we should do the second option.

Misha <notifications@github.com> schrieb am So., 7. Feb. 2016 21:08:

**Comment by yeganer** [comment]
Thank you for pointing out numpy's `assert_quantity_allclose`. I think we should use it whenever possible in our tests.

@wkerzendorf @unoebauer What do you think?

**Comment by mishinma** [comment]
I made PR #479 to use `assert_quantity_allclose` in test_simulation.py

**Comment by mishinma** [comment]
Should the issue be closed now?

**Comment by unoebauer** [comment]
Yes - closing it now.
