### ISSUE TITLE
Virtual packet logging: no check if allocation and reallocation is successful

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#480]
This primarily affects the virtual packet scheme, but is (I think) also relevant for other parts of the C-code. 

When allocating or re-allocating memory for the arrays storing the properties of the virtual packets (when compiled with ``--with-vpacket-logging``), no explicit check for the success of these processes is in place. This worrisome since these arrays tend to become very large.

A check for returned ``NULL`` pointers should be in place.

**Comment by unoebauer** [comment]
Just added PR #481 to address this

**Comment by yeganer** [comment]
I'm not familiar with vpacket_logging but i just thought about using a structure to store the logging information.
This would improve readability extremely and one would only check once.

I'll look into that idea later.
