### ISSUE TITLE
All prints directed to stderr.

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#492]
When I did some checks for the progress bar I noticed that all the prints are directed to `stderr`. From my perspective this isn't desired behavior.
Simple log messages like "Running with n threads" or Info level logging should be directed to `stdout` and only Warnings, Errors and important messages should be directed to stderr.

**Comment by unoebauer** [comment]
Should we merge this issue with #493?

**Comment by wkerzendorf** [comment]
@yeganer - the python logging system disagrees on that point with you. It prints to `stderr` for all log messages as far as I can tell.

**Comment by unoebauer** [comment]
I've stumbled upon this when gettint TARDIS ready for MPA's batch system. All the interesting output ends up in the stderr log file. Not a major hindrance but an annoyance.

**Comment by unoebauer** [comment]
Closing this - #553 is still open after all.
