### ISSUE TITLE
Progress updates have undesired effect when redirecting to file

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#493]
When running `tardis tardis_example.yml out 1>stdout.log 2>stderr.log` the progress bar creates this output:
```

[2K	[1%] Packets(finished/total): 400/40000
[2K	[2%] Packets(finished/total): 800/40000
[2K	[3%] Packets(finished/total): 1200/40000
```

This can be solved by introducing a switch to disable that functionality or by writing to a seperate tty device.

**Comment by unoebauer** [comment]
@yeganer - I'd be in favour of having a switch to turn the status bar on an off. If I remember correctly, @orbitfold stated the same opinion.
