### ISSUE TITLE
Optimization: cmontecarlo.c:compute_distance2boundary restructure logic

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#497]
In cmontecarlo.c:compute_distance2boundary the 1st thing that is calculated is d_outer in [https://github.com/tardis-sn/tardis/blob/master/tardis/montecarlo/src/cmontecarlo.c#L147](L147). Since we are not always using this value, we should only calculate it when we need it.
Thus I propose the following logic:

```pseudocode
if mu>0 // travelling outward
   return d_outer
else //travelling inward
  if (cross inner boundary) // inner boundary is always shorter than outer
    return d_inner
  else // didn't hit inner boundary? calculate d_outer
    return d_outer
```

A profiled run we did some time ago showed 25% execution time for compute_distance2boundary. Reducing the overhead is a simple task and should improve performance a bit.

**Comment by unoebauer** [comment]
I agree that this routine could be improved. The following is taken from my thesis:

This illustrates the propagation problem in spherical symmetry

![spherical](https://cloud.githubusercontent.com/assets/6351165/13320074/7efef5e4-dbc6-11e5-82e9-02da9ba2d8f5.png)

The distance to the next boundary, can then be calculated according to:

![distance](https://cloud.githubusercontent.com/assets/6351165/13320124/cabb433e-dbc6-11e5-81d4-c6e5420dd862.png)
