### ISSUE TITLE
Update documentation:Installation

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#518]
Since several people report having problems with that specific line
```
conda create -n tardis --file https://raw.githubusercontent.com/tardis-sn/tardis/master/conda-requirements python=2 pip
```
I suggest changing it to 
```
conda create -n tardis --file conda-requirements python=2 pip
```
and mention to run that from inside the root of tardis' repository.

There seems to be a problem with using https:// there. The bug seems to be system specific since I didn't encounter it.

**Comment by wkerzendorf** [comment]
@yeganer - agreed.

**Comment by yeganer** [comment]
@wkerzendorf should I do a quick PR?

**Comment by wkerzendorf** [comment]
sounds good

**Comment by yeganer** [comment]
Are we sure we want the part about pip in there?
And on the Installation page we don't even mention cloning git. Is this
still preferred?

Wolfgang Kerzendorf <notifications@github.com> schrieb am Do., 10. März
2016 um 14:09 Uhr:

**Comment by wkerzendorf** [comment]
ditch pip it's nowadays autoinstalled.

**Comment by yeganer** [comment]
If you look at the current installation page [https://tardis.readthedocs.org/en/latest/installation.html](url) you'll notice that the recommended way is to use anaconda and then inside anaconda install tardis with `pip install tardis-sn`.

If one follows the link to the Development Workflow, the first step is to setup the python environment which links to a page where using virtualenv is explained and anaconda isn't even mentioned.

With that confusing going on, I can understand why we got that many questions asking how to install.

Is the recommended way to install tardis for production still pip? In that case I wouldn't change much on the installation page but improve the "Set up your python environment" part.

**Comment by wkerzendorf** [comment]
whatever recommended means

**Comment by wkerzendorf** [comment]
put it on the agenda.
