### ISSUE TITLE
Coverage Report generated by 'coveralls.io' is incomplete.

### ISSUE THREAD

**Issue by karandesai-96** [tardis-sn/tardis#528]
The coverage report we've been receiving from [coveralls.io](https://coveralls.io/github/tardis-sn/tardis) is incomplete. The current coverage report is about 54% and it misses the coverage of tests which are skipped if `atomic-dataset` argument is not provided while running the tests.

Travis CI build system is configured in **.travis.yml**. It has four parallel jobs, the fourth job being: 
> _Run TARDIS and generate the coverage report._ (Command: `test --coverage`).

The coverage report is generated by doing a run without providing `--atomic-dataset` argument. This skips certain tests and hence the report is **incomplete**.

If the tests were always skipped on Travis, it would have been just fine. But in the second job, this argument is provided hence, the tests skipped previously are being run here. 

Hence, the coverage report should be generated from this job and not in a job which skips certain tests.

**Comment by wkerzendorf** [comment]
@karandesai-96 we do not run the coverage with the `atomic-dataset` option as we want to know the coverage of unit tests that actually test the code rather than when running the code in full where only the end product is tested.

**Comment by karandesai-96** [comment]
@wkerzendorf Understood.

**Comment by karandesai-96** [comment]
@wkerzendorf Then the other way around is to exclude the full code tests out of the coverage reports. This can be done by adding a comment `#pragma: no cover` wherever these full codes tests start.
