### ISSUE TITLE
reflecting packets

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#53]
Note that (somewhat arbitrarily) as a quick and dirty approach "reflected" packets currently get a new direction that is chosen from an isotropic distribution in the "outgoing" hemisphere. This is wrong and if we ever want to use that option for anything real we should think about it. E.g. at least use some sort of foreshortening (as for initialization of packets) or better still think about what it really means!

**Comment by unoebauer** [comment]
PR #112 has been merged - not entirely clear from the discussion accompanying the PR whether the issue at hand has been addressed. Are packets actually ever reflected, @ssim, @wkerzendorf? I thought they would be discarded once they intersect the inner boundary...(?)
