### ISSUE TITLE
conda-requirements should be listed once in a common place.

### ISSUE THREAD

**Issue by karandesai-96** [tardis-sn/tardis#546]
After the merge of #539 which adds OSX builds to Travis, the conda-requirements were listed in a separate **tardis_ci/tardis_ci_env27.yml** file and a new conda environment named **tardis-ci** is created in Travis builds through this file. A similar yml config file **tardis_ci/tardis_rtd_env27.yml** has conda-requirements listed for read the docs. The differences between dependencies in both files are:
```
- coverage=3.7.1
- requests=2.9.1
- docopt=0.6.2
- pytest-cov=2.2.1
```
These four dependencies are included in **tardis_ci/tardis_ci_env27.yml** while not in another one. Having them there won't cause any problem. This issue requires certain work to do for a solution:

1. Delete **conda-requirements**.
2. Merge the mentioned config files into one and use it everywhere required.
3. Update the documentation to instruct users for creating a conda environment as:
```
conda env create --name tardis --file tardis_ci/tardis_ci_env27.yml
```
* [Optional] Files may be renamed such that they look suitable in documentation description.

The consequences would be helpful, when the dependencies to be updated will have to be updated only in one place instead of three.

**Comment by wkerzendorf** [comment]
there are more differences in these which pertain to the documentation.

**Comment by karandesai-96** [comment]
@wkerzendorf I did not understand what are "these" referred to here. Do you mean the amount of changes to be done in documentation after making changes with the configurations ?

**Comment by wkerzendorf** [comment]
@karandesai-96 no you are right - nevermind.

**Comment by mangalutsav** [comment]
I would like to know the status of this issue, can a beginner like me take it up ?

**Comment by karandesai-96** [comment]
Hello @mangalutsav 
Yes, you can try your hand at this issue, it is an easy fix. Check the three files highlighted as **bold** in the description. You would see repeated content. The idea is to keep the content at one place and use it everywhere, for easy maintenance.

**Comment by mangalutsav** [comment]
In **tardis_ci/tardis_rtd_env27.yml** and **conda-requirements** pytest==2.6.3 is used whereas in **tardis_ci/tardis_ci_env27.yml** pytest==2.9.1 is used will this be a prolem

**Comment by karandesai-96** [comment]
I don't think pytest should create a problem. Still go ahead, do it and let us know what happened. **tardis_ci/tardis_ci_env27.yml** would be the most suitable to hold the conda requirements.

**Comment by yeganer** [comment]
Actually  I think **conda-requirements** would be the best place, since that's what people will use when they run tardis.

**Comment by karandesai-96** [comment]
@yeganer I just realized that. Also, specifying a filepath in yml would be simpler than parsing the yml file and including in `.rst` docs.

**Comment by ftsamis** [comment]
#569 is relevant to this issue, but I'm not sure if it solves it, since the conda-requirements are still there.

**Comment by ftsamis** [comment]
I think after #569 and #659 were merged this issue is now solved in its entirety.

@karandesai-96 @wkerzendorf Could someone close it?

**Comment by karandesai-96** [comment]
I think it is fine to close it.
