### ISSUE TITLE
PacketSource is returning Quantity for nus but array for energies

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#550]
This is just a small inconsistency

**Comment by unoebauer** [comment]
Still relevant? - if so, let's fix it and be done with it

**Comment by chinmay0301** [comment]
hi is this issue still relevant?

**Comment by unoebauer** [comment]
Just checked it explicitly - ``create_packets`` of ``BlackBodySimpleSource`` in ``tardis/montecarlo/packet_source.py`` returns only dimensionless arrays. Thus, this issue seems to be outdated and I'll close it.
