### ISSUE TITLE
distance2boundary: Result is not checked for NaN

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#552]
During the calculation of the distance to boundary it is assumed that the packet's radius is between r_inner and r_outer. Because of rounding errors this is not always true and there exists a small range of parameters (radius and mu) for which the discriminant gets negative (the packed doesn't hit the boundary). In that case the distance is NaN.

Possible ways to fix this:
- When crossing the boundary explicitly set the radius of the packet
- If dboundary is NaN, set it to a constant maximum (2 \* r_outer for example)
- Return some TARDIS_ERROR and discard packet

**Comment by unoebauer** [comment]
@chvogl - please comment - you've encountered this (or a similar) issue

**Comment by unoebauer** [comment]
According to @wkerzendorf, this issue was not encountered during the many simulations @yeganer performed during his master project. Thus, I am closing this one. Feel free to disagree and reopen.
