### ISSUE TITLE
Log C messages to the same stream python logs to

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#553]
Currently C always prints to `stderr`. If the python log is redirected, C will continue to log to `stderr` making it difficult to redirect the full log properly.

I propose two possible solutions:
1. Implement a wrapper to use the python logging functionality within C (there is a Gist somewhere)
2. Pass a FileDescriptor to `montecarlo_main_loop` which is then used instead of `stderr`

**Comment by unoebauer** [comment]
If I am not mistaken, simple stream redirecting (such as ``tardis config.yml spec.out > log.txt``) does also not work trivially. Something to think about

**Comment by unoebauer** [comment]
@yeganer, @wkerzendorf - should this become a 2.0 milestone or should we abandon this?

**Comment by wkerzendorf** [comment]
with numba this will go away.
