### ISSUE TITLE
test_cmontecarlo.py: partial coverage of cmontecarlo.c

### ISSUE THREAD

**Issue by karandesai-96** [tardis-sn/tardis#556]
Complete refactor of cmontecarlo tests was started in #530, followed by #544 (Refer checklists).

While most of the work is classified as "Done", there are a group of tests which have very complex underlying methods. They are kept under the **"Difficult to Test"** category block comment in **test_cmontecarlo.py**.

These tests are:
- `montecarlo_one_packet`
- `montecarlo_one_packet_loop`
- `montecarlo_main_loop`
- `montecarlo_event_handler`

Current implementation is in this manner:

``` python
@pytest.mark.skipif(True, reason="Yet to be written.")
def test_any_of_these_mentioned (params):
    pass
```

One more method is untested:
- `macro_atom`  
  `macro_atom` uses certain parameters of `StorageModel` for calculations, which are not yet set to default values in the fixture. They should be added in and this method be tested as well. To safely close this issue, a PR is expected to have the five tests mentioned here, in passing conditions.

**Comment by karandesai-96** [comment]
I just edited the title for it to fit in one line ! :sweat_smile:

**Comment by unoebauer** [comment]
@chvogl is working on this

**Comment by unoebauer** [comment]
@chvogl has introduced some unit tests for the C-part. Thus, closing this one!
