### ISSUE TITLE
Segfault during tardis cmontecarlo run

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#560]
This is what appears to cause the issue.

```
[26] last_line = 1822360143409613.250000
[26] next_line = 1822353496842714.500000
[26] ERROR: Comoving nu less than nu_line!
[26] comov_nu = -58783631258883757404258453611703772493428311659382084935097109061384145004566790513369500832759808.000000
[26] nu_line = 1822355712359626.750000
[26] (comov_nu - nu_line) / nu_line = -32256946797049520942182563511351622606622620138438708712185411031008847627110318080.000000
[26] r = 999999999999999967336168804116691273849533185806555472917961779471295845921727862608739868455469056.000000
[26] mu = -0.522198
[26] nu = -3489787318773531.500000
[26] doppler_factor = 16844473857376206614733575835140392265551777909465454558809109268882602250184163328.000000
[26] cur_zone_id = 1
```

I'll update later as I gather more information.
### SETUP:

```
dalek         1ac519cbb9f91941fbc4d51165e1942d9afc1e95
tardis        3370d8d67a9abf4102d9f9e1fb7fbcff8bcede18
```

`run_failed.py` is a simple script that reproduces the problem. You have to run with OMP_NUM_THREADS=8. The way I use it, I'm exporting that environment variable before running the file (nthreads = 0 in config allows for dynamically changing the number of threads)
[packet.zip](https://github.com/tardis-sn/tardis/files/261436/packet.zip)

**Comment by unoebauer** [comment]
@yeganer A bit of context would be good - when does this segfault occur, which setup is used, is there anything particular about the run?

**Comment by unoebauer** [comment]
@yeganer: Before going anywhere further, you should check that ``v_inner`` < ``v_outer``. @chvogl cautioned that this is in principle possible...

**Comment by yeganer** [comment]
I can verify that but I think it's very unlikely that this is causing the
problem. I'm setting v_inner in my config an the rest should be calculated.
As the crash happens during the spectral run and v_inner isn't changed
during the iterations, I think we have an other issue here.

Ulrich Noebauer <notifications@github.com> schrieb am Do., 12. Mai 2016
12:05:

**Comment by yeganer** [comment]
It looks to me like the packet in question is a virtual packet which was moved to miss distance.

**Comment by unoebauer** [comment]
@yeganer - still missing the basic background:
* problem setup
* yaml file

**Comment by yeganer** [comment]
The problem is, there is no yaml file. I am currently not able to reproduce the bug. On my local machine I get a slightly different result ( with the same input! ) which in turn doesn't seem to reproduce it.

**Comment by unoebauer** [comment]
Ok, so this segfault occurs during a DALEK run - this is already an important piece of information. However, without any information about the TARDIS setup triggering this segfault, this Issue report is not very helpful or useful.

**Comment by yeganer** [comment]
The distance2boundary is set to NaN which triggers the problem.

**Comment by unoebauer** [comment]
As discussed during the videocon on 13.05., we should manually set the packet position to the shell boundary during the crossboundary call.

**Comment by unoebauer** [comment]
@yeganer - has this issue been fixed?

**Comment by unoebauer** [comment]
There have been no further reports about segfaults of this sort. Closing!

**Comment by yeganer** [comment]
@unoebauer To be fair, there hasn't been a big bulk of tardis runs either. As this bug has a very low probability of happening we cannot be sure. After this bug was discovered I ran my simulations with a modified version of tardis where this bug was fixed.
