### ISSUE TITLE
[Astropy 1.1] Known Issues Collection

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#568]
Astropy 1.1 currently has some issues with our current codebase. This aims to be a collection of known issues and how to solve them.
## Known Issues:
- [x] #483 Fixed by #581 
  A change to astropy's pytest hooks causes them to fail with tardis. The solution is to override/add `pytest_runtest_setup` in `conftest.py` (This is imported from astropy)
- [x] #564 and a corresponding PR #565 : 
  Astropy changed their unit system to use astropy constants and SI units whenever possible. As a result the value of `unit.u` changes, which we are using to read the mass of our atom data. The solution is to either use `constants.u`(see #565) or to not compare pre1.1 with v1.1+

**Comment by unoebauer** [comment]
Looks like this has been fixed - Closing! (@yeganer - reopen if I am wrong)
