### ISSUE TITLE
angle aberation

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#57]

**Comment by unoebauer** [comment]
There is an entire series of issues dealing with omitted relativistic effects: #335, #57, #56, #55. Maybe we should combine them in one issue/milestone, @ssim, @wkerzendorf?

**Comment by wkerzendorf** [comment]
@unoebauer sounds like a good idea - issue or milestone; your choice.

**Comment by unoebauer** [comment]
Closing this one in favour of #448
