### ISSUE TITLE
[documentation] Example configurations are invalid

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#577]
While testing the new validator I wrote at #576 with `tardis_example.yml` from [Quickstart Guide](http://tardis.readthedocs.io/en/latest/running.html) I noticed that the `convergence_strategy` section is misnamed as `convergence_criteria` and its `hold_iterations` property is misnamed as `hold`.

This produces the following output when running tardis, and it actually runs with different convergence strategy than intended:
`tardis.io.config_reader - WARNING - No convergence criteria selected - just damping by 0.5 for w, t_rad and t_inner`

Same applies for the `tardis_02bo_kurucz.yml` config file in the example.

**Comment by unoebauer** [comment]
There a are two levels to answering this:

1. Obviously, we should just fix the yaml files in which are shipped with the tardis_example archive. However, we may want to wait with this until @ftsamis has completed the TEP 006 project

2. The automated convergence criteria and schemes currently available in TARDIS are a tricky subject. It is very difficult to formulate a strategy which is of general use. Often you have to fine-tune your choices and even your convergence procedure to achieve acceptable results for the problem at hand. That said, we often use a fixed number of plasma iterations (which we deem large enough to achieve convergence) and don't rely on the built in checks. This is particularly true for the tardis example, in which we use 20 iterations. Consequently, changing the config files is not necessary to ensure the desired behaviour in the example calculations.

**Comment by ftsamis** [comment]
Let's solve this by merging #599, so there are no more confused users until I finish with TEP006.

**Comment by ftsamis** [comment]
This is now fixed with the merge of #599.
