### ISSUE TITLE
Cleanup the io.config_reader module

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#579]
The `tardis/io/config_reader.py` module has a lot of legacy or ugly, unstructured code. In this issue we'll pinpoint the parts that need change, and we'll propose alternatives.

Some of the changes that need to be made are:
- Remove unnecessary conversions (spectrum_list2dict)
- Interpret values where they are used (`no_of_packes`, ...)
- Clean up Configuration.from_config_dict (move unit conversions to validator maybe?)
- Remove unused functions(parse_abundance_file_section, parse_supernova_section, parse_density_file_section, parse_model_file_section, etc.)

See #623 for progress.

**Comment by yeganer** [comment]
Remove unused `black_body_sampling` option.

**Comment by ftsamis** [comment]
@wkerzendorf @yeganer I've noticed that the configuration option `montecarlo.virtual_spectrum_range.num` is never used. Instead only start and stop are used. Should we remove `num`?

**Comment by wkerzendorf** [comment]
I think it is needed somewhere

**Comment by ftsamis** [comment]
I think not.

**Comment by wkerzendorf** [comment]
Well logically they need to have a num, right?

**Comment by ftsamis** [comment]
I don't know if it's needed (and therefore we have a bug) but I can surely tell you that it is not used in the code. The Cython and C code only defines and uses  `storage.spectrum_virt_start_nu` and `storage.spectrum_virt_end_nu`

**Comment by ftsamis** [comment]
There is a separate issue for that now #644.

**Comment by unoebauer** [comment]
Seems to still be WIP... (right @ftsamis?)

**Comment by ftsamis** [comment]
While the work is there, the merging is WiP, so yes, I'll close this whenever #652 reads "Merged"

**Comment by ftsamis** [comment]
Fixed as part of #652.
