### ISSUE TITLE
seed is not read from yaml

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#58]
and make seed shorter for 32 bit systems

**Comment by unoebauer** [comment]
@wkerzendorf: still relevant? 32bit compatibility was never really high on our list. I am not sure if we should actually bother with it...thoughts on this, @orbitfold, @ssim?

**Comment by unoebauer** [comment]
This is very outdated - the seed is *actually* read from the YAML file - closing.
