### ISSUE TITLE
handling of missing zeta data

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#62]
When the atomic data base does not contain zeta-values (for nebular ionization mode) there is currently a kluge to put 1.0's into the array (which is based on catching nan's).

This should be done better, ideally not relying on nan catching.

**Comment by unoebauer** [comment]
@ssim, @wkerzendorf: any progess/news on this?

**Comment by unoebauer** [comment]
Issue #411, which has been recently closed, seems to deal with the same problem...Does this mean we can close this issue as well, @ssim, @wkerzendorf, @aoifeboyle?

**Comment by unoebauer** [comment]
This has been improved during the plasma overhaul and there don't seem to be any problems with this part any more. Closing.
