### ISSUE TITLE
'inner_boundary_index' referenced before assignment

### ISSUE THREAD

**Issue by RachelLosacco** [tardis-sn/tardis#622]
This run uses `model/structure/type/specific` and `model/abundances/type/file`. 

[Here](http://pastebin.com/r1DGKPGT) is the pastebin with my terminal commands and full error.
[Here](http://pastebin.com/6P48pczV) is the pastebin with my .yml configuration file.
[Here](http://pastebin.com/dRw813JD) is the pastebin with the abundances file. 

It might not be a good idea to have a file type for abundances and `type:specific` for the structure. The error could stem from the astrophysics side more so than the programming aspect, but I would like to know why this is not working.

**Comment by yeganer** [comment]
I think you are missing shell `0`

**Comment by ftsamis** [comment]
I think that the combination of `abundances.type=file` and `structure.type=specific` will always end up on this error. This is because the variables `inner_boundary_index` and `outer_boundary_index` are only assigned in the ```structure_section['type'] == 'file'``` case, but are accessed anyway in the `abundances_section['type'] == 'file'` case (io/config_reader.py).

**Comment by RachelLosacco** [comment]
The example abundance file(s) show it beginning with 1. 

@ftsamis I think you're right. It also makes sense that a set up with varying abundances should not have a constant density and velocity.

**Comment by unoebauer** [comment]
True - physically it may  not be very meaningful but it could be a useful setup for test calculations. In any case, I'd suggest to add a check which informs the user that the selected combination is currently not supported.

**Comment by ftsamis** [comment]
This issue has probably become irrelevant after #652 was merged.
