### ISSUE TITLE
Configuration file problem?

### ISSUE THREAD

**Issue by piszkosfreddy** [tardis-sn/tardis#627]
I've just successfully installed tardis-sn-1.0.1 via anaconda with all the requirements (only the package 'pytest-html' is missing, the conda install did not find it).

However, after I downloaded the example directory (tardis_example.tar.gz from the page http://tardis.readthedocs.io/en/latest/running.html) and tried to run tardis, I got an error message:

Traceback (most recent call last):
  File "/home/barna/anaconda3/envs/tardis/bin/tardis", line 62, in <module>
    tardis_config = config_reader.Configuration.from_yaml(args.config_fname)
  File "/home/barna/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_reader.py", line 782, in from_yaml
    raise ConfigurationError('Currently only tardis_config_version v1.0 supported')
tardis.io.config_reader.ConfigurationError: Currently only tardis_config_version v1.0 supported

It's strange, because the first row of tardis_example.yml is "tardis_config_version: v1.0".

Has something changed recently about the configuration files?

**Comment by karandesai-96** [comment]
Hi @piszkosfreddy Right, `pytest-html` is not found on conda channels, right now, you may do `pip install pytest-html` and continue as a temporary solution.

**Comment by yeganer** [comment]
@piszkosfreddy Do not use the version available with pip.
Please download the latest version of tardis from github and use that.
```
git clone git://github.com/tardis-sn/tardis tardis-code
cd tardis-code
python setup.py install
```

@karandesai-96 This has nothing to do with `pytest-html` as that's only required when running tests.
We could think about some way to remove the `pytest-html` requirement when running normal tests and only require it for the integration tests.

**Comment by karandesai-96** [comment]
@yeganer It exists in that file on `master` at the moment hence gives an error. Although one can even move on without installing it. I agree, it shouldn't create a problem further.

**Comment by piszkosfreddy** [comment]
@karandesai-96 @yeganer Thank you guys, the latest version works properly!

**Comment by yeganer** [comment]
The issue seems to be resolved. Closing this.
