### ISSUE TITLE
Dealing with incomplete atomic data

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#63]
Issue is how to deal with input data that doesn't contain all ions. RIght now, TARDIS wants complete information - that means ionization potentials (and statistical weights to calculate partition functions).

Ideally, it should be able to handle (consecutive) ions (e.g. Fe I, Fe II and Fe III) and just spit out a warning that it doesn't have data for higher ions.

If provided with non-consecutive ions (Fe I and Fe III but no Fe II) it should complain and exit, I think.

**Comment by unoebauer** [comment]
This is still very relevant - see #438 and quickfix (only for Be) PR #439.

**Comment by unoebauer** [comment]
We should still think about implementing this
