### ISSUE TITLE
Issue when copying/modifying atomic data files

### ISSUE THREAD

**Issue by aoifeboyle** [tardis-sn/tardis#639]
@mishinma, Wolfgang said you're great with this stuff. Your help would be really appreciated.

If I copy the standard kurucz_chianti dataset using pd.HDFStore.copy(), the output will not work with TARDIS. The only clear discrepancy between the original and the copy is that in the original the frame tables are of type ‘generic’ and in the copy they’re ‘appendable’. I get a variety of errors when trying to use the copy with TARDIS, and even when I fix one it just leads to another one. 

My main purpose for doing this is that I just need to modify the atomic data for one ion (He I). I actually did this before (a couple of years ago) but I don't remember exactly how.  Now I want to apply the same changes to a different dataset. 

So I would just like to know why copying the file as above causes changes, and how to copy/modify the atomic data files without causing this problem.

Thanks,

Aoife

**Comment by yeganer** [comment]
@aoifeboyle Funny enough I just did exactly that yesterdat: Patching a database.
Basically the procedure is the following:
```
import h5py
data = h5py.File('./database.h5', mode='r+')
dataset = data['macro_atom_references']
datavalues = dataset.value
datavalues[0] = 1
dataset[...] = datavalues
data.close()
```
The important thing is that the old database is using `h5py` so we have to use that. @mishinma Is currently rewriting tardis to use a pd.HDFStore style database.
I suggest making a copy of the data(with `cp -a data.h5 data_backup.h5`) and then compare those two.

**Comment by mishinma** [comment]
@aoifeboyle  @yeganer Yes, you can use `HDFStore` to read the dataframes:
```
with pd.HDFStore(old_path) as store:
    lines = store["lines_data"]
    levels = store["levels_data"]
```
 Then you can modify them and write them back to the file like this:
```
with h5py.File(fpath, "w") as f:
    f["lines_data"] = lines_cut.to_records(index=False)
    f["levels_data"] = levels_cut.to_records(index=False)
```
Then it would work with the `upstream/master` branch and if not please let me know. We are still investigating the issue with HDFStores and copies; it seems that it has to do with the C part of the code.

**Comment by aoifeboyle** [comment]
@yeganer @mishinma Thanks, those are both really helpful answers. Now that you mention it I think I did use h5py instead of the HDFStore the last time. I'll try both of your suggestions and let you know if I have any issues.

**Comment by aoifeboyle** [comment]
Problem solved! Both solutions seem to work. Thanks. Closing issue.
