### ISSUE TITLE
Simulation and MontecarloRunner should be one

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#647]
I know that the argument to this will be "MontecarloRunner is only an interface to the C code." but that's partially wrong.

We practically now have two such interfaces: `montecarlo/montecarlo.pyx` and `montecarlo/base.py`. The Cython code i.e. `montecarlo.pyx` **is** the interface to the C code, while the python module is a wrapper for `montecarlo.pyx`. In turn `montecarlo/base.py` is wrapped by `simulation/base.py`, which essentially is only there to update the model/plasma and check for convergence (which it shouldn't #646). 

Therefore, I make a proposal to merge `simulation/base.py` and `montecarlo/base.py` to one module, either `simulation/base.py` or `montecarlo/base.py`.

**Comment by yeganer** [comment]
Haven't red it yet, but I agree on the title.
