### ISSUE TITLE
Installation issue on OSX El Capital

### ISSUE THREAD

**Issue by manolis07gr** [tardis-sn/tardis#658]
Hi all,

I follow the recommended installation steps with anaconda (version 2.0) and save all required packages in conda-requirements. Then I type conda create -n tardis --file conda-requirements python=2.

I always get the same error for the pytest-html package:

Fetching package metadata .......
Solving package specifications: .
Error: Packages missing in current osx-64 channels: 
  - pytest-html ==1.10.0
  - pytest-html

Close matches found; did you mean one of these?

    pytest-html: pytest-timeout, pytest
    pytest-html: pytest-timeout, pytest

You can search for packages on anaconda.org with

    anaconda search -t conda pytest-html

I do the search command and I add some available external pytest-html packages by hand but the error persists. Same happens even if I remove the pytest-html package from the conda-requirements file. Won't let me install TARDIS...any suggestions?

Manos

**Comment by ftsamis** [comment]
The environment creation instructions are now a bit outdated. Please download [the environment definition file](https://raw.githubusercontent.com/tardis-sn/tardis/master/tardis_env27.yml) instead and run:

```
conda-env create -f tardis_env27.yml
```

Then follow the rest of the installation instructions as they are.

@wkerzendorf Feel free to close this issue whenever #659 is merged.

**Comment by manolis07gr** [comment]
Fotis,

Thanks for the help - the installation now worked but when I try to run the tardis_example.yml using tardis tardis_example.yml output_spec.dat as explain in the docs, I get this error:

tardis tardis_example.yml output_spec.dat
Traceback (most recent call last):
  File "/Users/macbro/anaconda3/envs/tardis/bin/tardis", line 62, in <module>
    tardis_config = config_reader.Configuration.from_yaml(args.config_fname)
  File "/Users/macbro/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_reader.py", line 784, in from_yaml
    return cls.from_config_dict(yaml_dict, test_parser=test_parser)
  File "/Users/macbro/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_reader.py", line 828, in from_config_dict
    config_dict).get_config()
  File "/Users/macbro/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1161, in __init__
    self.__parse_config(configuration_definition, input_configuration)
  File "/Users/macbro/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1337, in __parse_config
    self.__conf_o, self.__conf_v = recursive_parser(default_configuration, configuration, [])
  File "/Users/macbro/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1323, in recursive_parser
    tmp_conf_ob[k], tmp_conf_val[k] = recursive_parser(v, configuration, path + [k])
  File "/Users/macbro/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1323, in recursive_parser
    tmp_conf_ob[k], tmp_conf_val[k] = recursive_parser(v, configuration, path + [k])
  File "/Users/macbro/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_validator.py", line 1309, in recursive_parser
    ccontainer = Container(top_default, container_conf, container_path=path)
  File "/Users/macbro/anaconda3/envs/tardis/lib/python2.7/site-packages/tardis/io/config_validator.py", line 997, in __init__
    raise ValueError('Entry %s is missing in configuration. [%s]' % (str(nitem), self.__container_path))
ValueError: Entry hold-iterations is missing in configuration. [['montecarlo', 'convergence_strategy']]

What do I miss?
Thanks!
Manos

**Comment by ftsamis** [comment]
I forgot to mention that you should also work with the development versions of TARDIS, since the stable version is pretty outdated, especially after the changes introduced during GSoC16.

`pip install git+https://github.com/tardis-sn/tardis` and trying to run tardis again should do the trick.

**Comment by manolis07gr** [comment]
Yes! That worked! Thanks again Fotis.


On 9/19/16 2:53 PM, Fotis Tsamis wrote:
> |pip install git+https://github.com/tardis-sn/tardis|

-- 
Dr. Manos Chatzopoulos
Assistant Professor
Department of Physics & Astronomy
Louisiana State University
Nicholson #275
Office # 225-578-2907
Baton Rouge, LA 70808
United States of America
http://www.lsu.edu/physics/people/faculty/chatzopoulos.php

**Comment by ftsamis** [comment]
Glad I helped! In the meantime I also updated the installation instructions relevant to the environment creation, so I'm closing this issue.
