### ISSUE TITLE
undefined symbol: rpacket_get_energy

### ISSUE THREAD

**Issue by HeloiseS** [tardis-sn/tardis#661]
Hello,

I just downloaded TARDIS and tried to run tardis_example but I get the following error:

  File "/usr/local/bin/tardis", line 4, in <module>
    from tardis import simulation, model
  File "/usr/local/lib/python2.7/dist-packages/tardis/model.py", line 13, in <module>
    from tardis.montecarlo import montecarlo
ImportError: /usr/local/lib/python2.7/dist-packages/tardis/montecarlo/montecarlo.so: undefined symbol: rpacket_get_energy

I made sure to download all the packages required to run TARDIS. Do you know what could have caused this issue? 

Cheers,
H

**Comment by yeganer** [comment]
Hey HeloiseS,

looks like something went wrong during installation/compilation. It's difficult to debug this remotely.
Can you please answer the following questions:

- How did you download and install tardis (specifically which version did you download)
- How did you try to run the code?
- What's your OS and python version?

You can try to run `python setup.py install` in the git repository again and see if that fixes the problem.

**Comment by HeloiseS** [comment]
Hello yeganer,

Your solution worked, I managed to run tardis after uninstalling the pip version and installing the git version. 

Thank you!

**Comment by unoebauer** [comment]
Looks like this isssue is resolved. Closing
