### ISSUE TITLE
ImportError while creating environment using conda-env - cannot find args_func

### ISSUE THREAD

**Issue by xennygrimmato** [tardis-sn/tardis#675]
I am following the instructions specified [here](http://tardis.readthedocs.io/en/latest/installation.html).
Running `conda-env create -f tardis_env27.yml` gives me the following error traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/conda-env", line 3, in <module>
    from conda_env.cli.main import main
  File "/usr/local/lib/python2.7/site-packages/conda_env/cli/main.py", line 28, in <module>
    raise e
ImportError: cannot import name args_func
```
Is there something that's missing from the docs that I need to do?
Also, is there a reason why Anaconda is recommended as compared to `virtualenv`?

**Comment by yeganer** [comment]
To me this looks like a problem with conda, not with the instructions.

- Is your conda up to date?
-  Can you install software manually using anaconda? `conda install numpy` for example

**Comment by xennygrimmato** [comment]
- Yes, my conda is up to date.
- Yes, I can.

This is a problem with conda: https://github.com/conda/conda/issues/3148

**Comment by yeganer** [comment]
Having a brief look at the issue you linked I'd suggest to downgrade conda. From the issue it looks like conda 4.1 should work. On my machine I have conda 4.2.13 installed and no problems.

**Comment by xennygrimmato** [comment]
@yeganer I have created a `virtualenv` instead and `python setup.py build` ran successfully.
Can you suggest something that I can run to make sure that my `virtualenv` is properly working?

**Comment by unoebauer** [comment]
Looks like using the appropriate conda version solves this issue - closing.
