### ISSUE TITLE
Download button for configuration file doesn't refer to any external file

### ISSUE THREAD

**Issue by xennygrimmato** [tardis-sn/tardis#676]
I am following the Quickstart Guide and trying to run TARDIS. On the [Configuration File](http://tardis.readthedocs.io/en/latest/configuration/configuration_old.html#config-file) documentation page, the `img` for the download isn't linked to an external config file.

**Comment by unoebauer** [comment]
Yes, you are right. For the time being, just take it from ``docs/examples/tardis_example.yml`` in your tardis source directory.
