### ISSUE TITLE
Automatically convert and store ranges as linspaces

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#679]
Similar to what we do with quantities, which we now convert to `astropy.unit.Quantity` instances with a yaml resolver and constructor, should we also automatically convert ranges, currently expressed as `{'start': ..., 'stop': ..., 'num': ...}` dicts to `numpy.linspace`s? Most of the classes that take such ranges as parameters, eventually convert the dict to a linspace.

This could be easily done with a yaml constructor for the dict type, but it would require a few changes in other places of the code too.

The change would be seamless, since all values would be accessible:

- start would be linspace[0]
- stop would be linspace[-1]
- num would be range(linspace)

This is the base for #687. I have opened two separate issues for similar things because this one doesn't require us to bump the configuration version (no changes to the configuration file syntax required), while #687 does. 

This originated from #624.

**Example:**
`virtual_spectrum_range` is a range property (this can be verified by looking that in the configuration schema it is consisted from the properties `start`, `stop`, and `num`. 

The `YAMLLoader` should detect these properties and instead of returning a dict with the aforementioned keywords and their values it should return a `numpy.linspace` object with the correct values.

This way, when accessing `conf.montecarlo.virtual_spectrum_range` from a `tardis.io.config_reader.Configuration` object we would get a `np.linspace` directly without the need to create it every time in the various `from_config` classmethods.

**Comment by mangalutsav** [comment]
@ftsamis is anyone else doing this?

**Comment by ftsamis** [comment]
@mangalutsav This needs to be discussed with the TARDIS developers first in order to decide if it is something that we really want to do. For now it is just a proposal.

**Comment by yeganer** [comment]
I think it's worth doing and it shouldn't be a difficult change.

If we want to be really fancy, we can subclass `np.ndarray` and add `start`, `stop` and `num` during initialization.

@mangalutsav Feel free to show us a PR

**Comment by priyanka303** [comment]
@ftsamis is anybody else is doing this ??

**Comment by ftsamis** [comment]
I am not aware of any PR on this. Feel free to demonstrate your approach with a PR.

**Comment by yeganer** [comment]
@ftsamis Can you please edit the Issue description to more clearly reflect the changes required to implement this feature request and to differentiate it from #687.
I think there is some confusion going on between the goals of the issues.

Am I right in thinking the implementation of this will expect a dict with `start, stop, num, (unit)` keys and should return a `np.linspace`?
#687 on the other hand will capture a string of the form '1..10..50' and convert it into a `start, stop, num` dict? (with units optional)

**Comment by ftsamis** [comment]
@yeganer Added an example, hope that makes the goal a bit more clear. And yes, you are right about the purpose of the two issues.

**Comment by unoebauer** [comment]
Closing - reopen if necessary
