### ISSUE TITLE
Many docstrings are inconsistent with the numpydoc format

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#680]
Using the numpydoc format allows for type hinting in PyCharm and easy linking to other docstrings. However, in many places the docstrings violate this format, breaking the type hinting for PyCharm.

An example:
```python
def calculate_density_after_time(densities, time_0, time_explosion):
    """
    scale the density from an initial time of the model to the
    time of the explosion by ^-3

    Parameters:
    -----------

    densities: ~astropy.units.Quantity
        densities

    time_0: ~astropy.units.Quantity
        time of the model

    time_explosion: ~astropy.units.Quantity
        time to be scaled to

    Returns:
    --------

    scaled_density
    """
```

Here, the keyword "Parameters" is followed by a colon, immediately breaking type hinting, and furthermore the parameter types start with a "~", which is unnecessary and also breaks class resolving.

There are probably more kinds of docstring errors in other places too, so this needs some careful research.

Note: You can view the formatted documentation of an object with `ctrl + q` in PyCharm.

**Comment by nitinkgp23** [comment]
Hey, I am newcomer here and I would like to work on this issue. Can someone help me in going forward with this?

**Comment by yeganer** [comment]
What questions do you have?

**Comment by unoebauer** [comment]
We may think about making an aggregate issue, collection everything related to coding style.

**Comment by debajyotidasgupta** [comment]
hello,
i am new to this organisation and would like to take this as my first pr
It would be helpful if tell me what all changes should i make?

**Comment by ImmortalRabbit** [comment]
Is this issue still open? It's just something was merged already.

**Comment by arjunsavel** [comment]
@marxwillia should we close this, or did the relevant PR merge not completely fix this?
