### ISSUE TITLE
Unit assumptions in montecarlo.pyx

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#681]
In every level above montecarlo.pyx we work with `astropy.units.Quantity`s. This is a great way for users to provide quantities in their preferred unit or multiple of unit. That also means that in the transition between Python and C (Quantity objects to plain doubles) which is currently coded in the `montecarlo.pyx` module, extreme care should be taken to always convert quantities to the desired units. This is not done in many cases at the moment, and can lead to invalid results in (rare) cases where a user creates the `Radial1DModel` himself.

~~For example, if a `time_explosion` is passed to the `Radial1DModel` with a unit other than `seconds`, because the different unit propagates to other properties calculated from `time_explosion` too, the TARDIS run will produce invalid results.~~

Edit: The `time_explosion` example is not valid any more.

**Comment by ftsamis** [comment]
This can be solved in these steps:

1. Ensure that explicit unit conversions to the desired unit take place in every quantity access in montecarlo.pyx
1. Write tests to check if the montecarlo indeed works the same if we pass it a model with different units/multiples.
1. (Optional) Remove unit conversions in the rest of the code. (mainly `Radial1DModel`)

**Comment by Sidhhant** [comment]
Hey @ftsamis ,
Can I contribute to this issue ?  If then please guide me where to start from?

**Comment by ftsamis** [comment]
@Sidhhant Assuming you have [installed](http://tardis.readthedocs.io/en/latest/installation.html) TARDIS and successfully [ran the example](http://tardis.readthedocs.io/en/latest/running.html), you can have a look at the code and try to understand the problem as described in my comments above. If you have any questions feel free to ask in gitter.

**Comment by chinmay0301** [comment]
@ftsamis  , hello I have installed TARDIS and have executed the example also. I am new to cython and the tardis code base, if possible can I try contributing to this issue?

**Comment by ftsamis** [comment]
No need for permission to contribute. See how astropy quantities work, locate any instances where there is a quantity in montecarlo.pyx which is not explicitly converted to a specific unit, and present your findings here, or even better create a PR fixing them.

**Comment by chinmay0301** [comment]
storage.spectrum_virt_start_nu = runner.virtual_spectrum_range.stop.to('Hz', units.spectral()).value
    storage.spectrum_virt_end_nu = runner.virtual_spectrum_range.start.to('Hz', units.spectral()).value
    storage.spectrum_delta_nu = runner.spectrum_frequency.to('Hz').value[1] - runner.spectrum_frequency.to('Hz').

These are the instances I found.

**Comment by ftsamis** [comment]
@chinmay0301 I believe the `storage.spectrum_virt_start_nu` and `storage.spectrum_virt_end_nu` are already explicitly converted to `Hz`. `spectrum_frequency` indeed lacks conversion. Feel free to start a PR (pull request) which is the proper way to demonstrate changes in the code.

**Comment by ftsamis** [comment]
Closing this for now since #686 got merged, although it's not future-proof (no tests).

**Comment by wkerzendorf** [comment]
This is a broader issue and I'd like to keep it open.
