### ISSUE TITLE
Unused configuration properties in configuration

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#695]
Currently the following `convergence_strategy` properties are never used in the code:

When type is `specific`:

- `convergence_strategy.threshold`
- `convergence_strategy.fraction`

When type is either `damped` or `specific`:

- ` convergence_strategy.lock_t_inner_cycles`
- `convergence_strategy.damping_constant`

We should either remove them or use them (probably the first one for threshold and damping_constant since they don't make much sense).

**Comment by mohit9727** [comment]
@ftsamis  I would like to contribute to this, can you tell me where to begin?

**Comment by ftsamis** [comment]
It is not yet clear if we should remove those properties or try to use them, so this issue is currently under discussion. I'd suggest picking another issue to work on.

**Comment by unoebauer** [comment]
What should we do about this, @wkerzendorf, @yeganer? This seems to be an almost "cosmetic" change. Should we add this to 2.0 or abandon it?

**Comment by unoebauer** [comment]
When simplifying the convergence treatment to only one strategy, ``damped``, in PR #821 this issue has been addressed.
