### ISSUE TITLE
Replace MockRegexPattern with proper regular expressions

### ISSUE THREAD

**Issue by ftsamis** [tardis-sn/tardis#702]
[MockRegexPattern](https://github.com/ftsamis/tardis/blob/152c3f74714ae3515646122be2012ca3b12cd339/tardis/io/util.py#L35-L60) is a class introduced to easily find (match with) strings that represent astropy Quantities in the YAML configuration. 

The main problem with matching Quantities is units. We could either be too coarse, matching everything that looks like `<number><space(s)><string>` to a Quantity, or too strict and require that a string must be passed to a `string_to_quantity` function and throw no exceptions to be considered a valid Quantity.

We have chosen to go with the strict way with the tradeoff of making parsing extremely slower compared to if it used actual regular expressions, significantly affecting unit tests performance too (which load configuration files dozens of times).

Furthermore, since the default regular expression for floats in the pyyaml package didn't work very nicely, not recognizing some forms of floats, thus requiring `-.inf` instead of `-inf`, `5.e+5` instead of `5e5` or `5.e5` we chose to use `MockRegexPattern` for floats too, passing the strings to the python `float` constructor and seeing if it throws any exception.

After some thinking, I'm persuaded we should stick with regular expressions:

- For floats, write a proper regular expression that would match with all valid `float` types in Python. Examples include: `nan`, `inf`, `5e1`, with all their signed or decimal variants (`-inf`, `-nan`, `+5.0e+1`, and so on)
- For quantities create a regular expression that would use the regular expression for floats as mentioned above, in the form of `<float_regex>\s*[a-zA-Z/ ]*` and let the quantity yaml constructor complain if the units are invalid.

Keep in mind that with the current code and in the worst case, every single value in a YAML file could be checked against `MockRegexPattern` for Quantity, fail, then be checked against `MockRegexPattern` for float, fail, and then match against its actual type. That leads to quite some significant overhead, and the order of the resloving is not in our control.

**Comment by yeganer** [comment]
I'm not sure but how the `!object` syntax in yaml works but essentially we could require all quantities to be marked with `!quantity` for example. This would be explicit but it won't be backwards compatible.

**Comment by ftsamis** [comment]
This is actually possible now too. What the implicit resolver (and therefore the regex) does is understand that without the tag. I don't think we should make the tag a requirement and break compatibility since we don't currently have any other property type resolving of which would be ambiguous with the resolving of quantities. It would also take off from simplicity in the syntax.

**Comment by yeganer** [comment]
It is possible to do both, right? So we could add a tag and an implicit resolver?

**Comment by ftsamis** [comment]
We already have both. A tag: [`!quantity`](https://github.com/ftsamis/tardis/blob/152c3f74714ae3515646122be2012ca3b12cd339/tardis/io/util.py#L92) and [an implicit resolver](https://github.com/ftsamis/tardis/blob/152c3f74714ae3515646122be2012ca3b12cd339/tardis/io/util.py#L93) so that we don't **have to** provide the tag every time

**Comment by yeganer** [comment]
Got it, thanks. I only had a quick look at the YAML constructor stuff and didn't know this 'interaction'.

**Comment by ftsamis** [comment]
And some early metrics:
Pre #703, running `tardis/model/tests/test_base.py` took 18sec while with #703 it only took 8sec with cProfile showing that the millions of `MockRegexPattern.match` and `quantity_from_str` (mostly failed) calls were taking up about 60% of the total cpu time.

`MockRegexPattern.match` was called 10110060 times and `quantity_from_str` 5055609 times for just one unit test.

**Comment by chinmay0301** [comment]
Because of the MockRegex class, I was facing difficulty in solving the issue #687. As when I tried creating a constructor for specifying `spectrum` , as it was being shadowed by the MockRegex class

**Comment by yeganer** [comment]
@chinmay0301 The first step for solving #687 is #679. Were you successful with that?

**Comment by ftsamis** [comment]
@chinmay0301 I highly doubt that the `MockRegexPattern` class itself has the capability of shadowing anything at all, especially constructors, which are unrelated to this class. I have written a detailed review in your PR, pointing to you the actual problems with your approach. Have a look if you haven't yet.

**Comment by unoebauer** [comment]
I am closing this since there won't be anybody working on this in the foreseeable future.
