### ISSUE TITLE
[Documentation] Fix installation guidelines

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#707]
I just had a quick look at our documentation and noticed several issues:

- Some places still suggest `pip install tardis-sn` in some way or another. This should be fixed to point to the development version
- We have guides for installing the tardis requirements via `pip-requirements`. Do we want to support pip at all or anaconda all the way?

**Comment by unoebauer** [comment]
I lean towards only supporting anaconda.

**Comment by unoebauer** [comment]
Closing in favour aggregate issue
