### ISSUE TITLE
[TEP005][WIP] Full implementation of the formal integral approach

### ISSUE THREAD

**Issue by yeganer** [tardis-sn/tardis#731]
The full implementation of the formal integral approach consists of several sub-projects:

- [x] Basic Implementation (#726)
- [x] Refactor of spectrum class (#729)
- [x] Config Integration
- [x] Unittests
- [ ] Documentation (See #621)
- [ ] Verification
- [x] Electron scattering
- [x] Source function for macro atom

**Comment by unoebauer** [comment]
This will be fixed/concluded with #859.
