### ISSUE TITLE
Feature request: Add virtual packet diagnostics to hdf dump of runner

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#800]
With this issue I'd like to discuss whether it would make sense to add the virtual packet diagnostic arrays to the HDF5 write-out of the runner class whenever the ``--with-vpacket-logging`` flag is active. In particular, I'd like to add the following arrays:
* ``virt_packet_last_interaction_type``
* ``virt_packet_last_line_interaction_in_id``
* ``virt_packet_last_line_interaction_out_id``
* ``virt_packet_last_interaction_in_nu``
* ``virt_packet_nus``
* ``virt_packet_energies``

The main benefit of adding these arrays would be that I could use the native TARDIS ``to_hdf`` functionality for the tardisanalysis tools and could scrap the clunky interface which is currently used.

What do you think, @wkerzendorf?

**Comment by kaushik94** [comment]
@wkerzendorf @unoebauer I would like to take up this task if it is ok?

**Comment by ImmortalRabbit** [comment]
Is this issue still open? It's just something was merged already.
