### ISSUE TITLE
Problem with stratified models using Decay of isotopes branch #801

### ISSUE THREAD

**Issue by pfreddy** [tardis-sn/tardis#804]
I've tried to run TARDIS with the new decoy branch #801 according to the tardis_model_format (see tardis/io/tests/data/tardis_configv1_tardis_model_format.yml and tardis_model_format.csv).  The code stopped with the error  message: 

  File "/home/barna/Code/tardis/tardis/io/decay.py", line 27, in from_materials
    multi_index_tuples, names=['atomic_number', 'mass_number'])
  File "/home/barna/anaconda3/envs/tardis/lib/python2.7/site-packages/pandas/core/indexes/multi.py", line 1138, in from_tuples
    raise TypeError('Cannot infer number of levels from empty list')
TypeError: Cannot infer number of levels from empty list

However, using uniform abundances (tardis/io/tests/data/tardis_configv1_isotope_uniabund.yml) works fine.

**Comment by pfreddy** [comment]
It seems the problem is the half-empty list of 'materials'. It contains information about each of the velocity shells, but each element is the same:

pyne.material.Material({}, nan, -1.0, 0.0, {})

[issue_804.tar.gz](https://github.com/tardis-sn/tardis/files/1474092/issue_804.tar.gz)

**Comment by pfreddy** [comment]
The list 'material' always uses the isotope ratio of the last velocity shell. The root of this problem is in the function called 'to_materials(self)' in decay.py (line 47). Here, the abundance storing 'comp_dicts' is a dictionary, thus, the abundances are overwritten in ALL velocity shells whenever the code meets the same nuclear_symbol. As a result, the last abundances appear everywhere.

As a further issue, the code probably cannot handle if there are no isotopes in certain velocity shell (see the error message above).

**Comment by unoebauer** [comment]
Presumably fixed by #806. Closing - reopen if error persists
