### ISSUE TITLE
Fail to reproduce normal Ia spectra with configuration from Mazzali et al. 2018

### ISSUE THREAD

**Issue by wenxiongM51** [tardis-sn/tardis#823]
[Mazzali et al. - 2018 - Nebular spectra and abundance tomography of the type Ia supernova SN 2011fe a normal SN Ia with a stable Fe cor.pdf](https://github.com/tardis-sn/tardis/files/1905393/Mazzali.et.al.-.2018.-.Nebular.spectra.and.abundance.tomography.of.the.type.Ia.supernova.SN.2011fe.a.normal.SN.Ia.with.a.stable.Fe.cor.pdf)

[2011fe.zip](https://github.com/tardis-sn/tardis/files/1905396/2011fe.zip)
We try to reproduce spectra of SN 2011fe from configuration in Mazzali et al. 2018 (attached) but failed. We use a built-in branch85_w7 model. And we are working on a normal SN Ia which has similar spectral evolution of SN 2011fe. So we want to figure out how to reproduce it.

**Comment by wenxiongM51** [comment]
[Spectral Sequences of Type Ia Supernovae  Connecting Normal and Subluminous SN Ia and Carbon.pdf](https://github.com/tardis-sn/tardis/files/1905427/Spectral.Sequences.of.Type.Ia.Supernovae.Connecting.Normal.and.Subluminous.SN.Ia.and.Carbon.pdf)
Sorry the abundance profile we used is from this paper. Forgot to upload it.

**Comment by unoebauer** [comment]
Hi @wenxiongM51 - could you be more specific about your problem. Are there problems with
- installing Tardis
- running Tardis
or are you saying that the spectra obtained with Tardis do not look like the ones produced by Mazzali et al. 2018? In any case, we can't help you much without more detailed information about the actual problems.

**Comment by wenxiongM51** [comment]
Hi unoebauer,
I'm sorry about my unclear question. I have emailed Wolfgang about this issue he told me to open a question here. I have problem with Tardis running result (installation complete). I think we can focus on Heringer et al.(2017) which I uploaded first. Because I realized the Mazzali paper mainly focus on late phase but we want to reproduce the spectra of early phase now. I input the abundance displayed in Table 2 of Heringer et al. (2017) and choose a branch85_w7 model. But we failed to reproduce the spectra displayed in this paper (figure 1 and figure 2). So I don't know how to improve our result.
Thanks.

**Comment by unoebauer** [comment]
Hi, it's good to see that there is at least no installation error. However, I am still at a loss about the severity of problems in the spectra. Could you please share your spectra?

**Comment by wenxiongM51** [comment]
[12.1sun.txt](https://github.com/tardis-sn/tardis/files/1924912/12.1sun.txt)
I attach my latest simulated spectrum. The .yml and abundance file inside the .zip file I uploaded 6 days ago. Thanks!

**Comment by wkerzendorf** [comment]
Can you grab put it up as a png plot then we can quickly see what’s going on. You can drag it into github

**Comment by wenxiongM51** [comment]
![2011fe_12 1day](https://user-images.githubusercontent.com/38336485/38946504-804f449e-42ee-11e8-92cd-ebd3790242b2.png)
I put the plot here

**Comment by wenxiongM51** [comment]
![2011fe_-5day](https://user-images.githubusercontent.com/38336485/39203654-442d012a-47aa-11e8-99a7-3a243434539c.png)
I plot the spectrum I want to reproduce vs tardis fit here. The S II 5468/5612, Fe III 5129 and the absorption bluer than 5000A are not well matched.

**Comment by unoebauer** [comment]
I don't think that there is anything wrong with TARDIS. Instead, TARDIS was most likely not properly configured. You also have to remember, that Mazzali et al. used a different spectral synthesis code to fit 2011fe. I am, however, convinced that if you set up TARDIS such that it produces a plasma state during the spectral synthesis cycle that is comparable to that obtained by Mazzali et al., 2012fe should be fit to a similar accuracy. 

From the comparison you show I would conclude that the temperature in the ejecta and at the boundary is too low.

**Comment by unoebauer** [comment]
I am closing this issue. @wenxiongM51 , @wkerzendorf if necessary, please re-open.
