### ISSUE TITLE
Using Tardis CSV input for custom abundances and isotopes

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#830]
While working with the CSV input option for custom abundance and isotope profiles, I noticed that the relevant parser in ``model_reader.py``, 
```python 
def read_simple_isotope_abundances(fname, delimiter='\s+'):
```
expects that the custom composition file contains information about the ejecta state (velocity, temperature, electron density, ...) in the first four columns.

I assume that this was at some point implemented to work with CMFGEN setups (right @wkerzendorf?), but for most normal use cases these columns are irrelevant. Either the information is not used or specified in the model density profile setup process. In any case, the current documentation does not specify that when using CSV files, four additional columns are needed.

I would suggest that we split the CSV input option into two use cases

- CMFGEN setups, for which keep the current parser
- normal Tardis use cases: for this we should add an additional parser (based on the current one) which does not expect additional ejecta information in the first four columns

In any case, the documentation should be updated to reflect the behaviour of the CSV parser

**Comment by wkerzendorf** [comment]
I agree - I'm trying to figure out what is going on.
