### ISSUE TITLE
installation failed: needed older version of pyne module

### ISSUE THREAD

**Issue by saurabhwjha** [tardis-sn/tardis#834]
I've lost track of the details, but in trying to install tardis via conda, etc. we ran into an issue where the most recent version of the pyne module didn't work. Forcing conda to use an older one succeeded.

**Comment by Heringer-Epson** [comment]
Same happened to me.

**Comment by unoebauer** [comment]
That's interesting. Can you provide more information about the pyne version numbers?

**Comment by unoebauer** [comment]
@wkerzendorf - did we already fix this with the various updates to the tardis conda env file?

**Comment by unoebauer** [comment]
Apparently, also @chvogl encountered this issue (see #854). Updating conda (>4.5) resolved this problem. Closing for now.
