### ISSUE TITLE
Is delta_treatment being enforced?

### ISSUE THREAD

**Issue by Heringer-Epson** [tardis-sn/tardis#835]
Setting delta_treatment: 1 under plasma might not be properly enforcing it. This happened to me in version 3036. Tried to install the current version, but encountered installation problems involving Cython.

**Comment by wkerzendorf** [comment]
@Heringer-Epson can you detail these installation problems - maybe just adding this to the issue.

**Comment by Heringer-Epson** [comment]
Tested delta_treatment using the updated TARDIS (v1.5.dev3179). Problem seems to persist.
Below is a link to the input file used to run the simulation.

.yml file: http://128.100.88.57/lib/exe/fetch.php?media=2018_-_jul:seed-23111970.yml

And below I plot delta for the CII ion. Data is retrieved using:

delta = pd.read_hdf(_syn + '.hdf', '/simulation/plasma/delta')
y = delta.loc[6,1].values 

Fig: http://128.100.88.57/lib/exe/fetch.php?media=2018_-_jul:fig_delta_test.pdf

**Comment by wkerzendorf** [comment]
doesn't look like it's being enforced. hmm - will need to check in the code. I've just come back and am catching up - but ping me tomorrow.

**Comment by wkerzendorf** [comment]
it's not being enforced. I have made the first fix - need to check if things work now.
