### ISSUE TITLE
Problems with Cython - include working version back into env file

### ISSUE THREAD

**Issue by unoebauer** [tardis-sn/tardis#842]
Sparked by issue #810, problems with old and new versions of cython become obvious, both on the user side on the Travis testing environment. At least the problems on Travis seem to be under control after using the bleeding-edge cython version and compiling it with a specific flag. See

- [cython issue](https://github.com/cython/cython/issues/2199#issuecomment-405994151)
- PR #829 
- PR #838 

In the process of this Cython was removed from the current anaconda environment file ``tardis_env27.yml``.

We should include cython back into the env file. This may require establishing a working cython version first.

**Comment by wkerzendorf** [comment]
Cython  0.28.4 works - except for OSX

**Comment by unoebauer** [comment]
Any idea about the OSX problems? Is there another cython version that works on OSX? What is our current suggestion to TARDIS users? Self-compile?

**Comment by kaushik94** [comment]
I think I am facing this issue too on OSX:
<img width="1017" alt="screen shot 2018-09-26 at 8 05 47 pm" src="https://user-images.githubusercontent.com/6545467/46087282-98bd5e00-c1c7-11e8-8a3e-75c15f94b47b.png">

**Comment by unoebauer** [comment]
Hi @kaushik94 - yes this looks like your env does not include a cython version. Try to manually install cython within the env and rebuild Tardis.
