### ISSUE TITLE
simple sets of stratified abundances

### ISSUE THREAD

**Issue by ssim** [tardis-sn/tardis#85]
It would be good to have a version of the abundance section that can deal with simple sets of multi zone abundances - say a "type:stratified" or something. Basically one would set up a bunch of abundance zones, each of which is specified by a set of numbers like:

```
         start: 10000 km/s
         stop: 11000 km/s
         O: 0.19
         Mg: 0.03
         Si: 0.52
         S: 0.19
         Ar: 0.04
         Ca: 0.03
```

…so that the abundances are populated with those vales in that velocity range. The user can then set up a model with a handful of zones (perhaps up to a max of 10 or so) so that they can play with non-uniform abundances along one of the simple density profiles (i.e. a level of sophistication between our current "uniform" setting and the gory details of giving a fully tabulated set via an input file).

Can this be incorporated as part of the next version of the config file?

**Comment by unoebauer** [comment]
@ssim, @wkerzendorf: is this feature still requested? Would be a nice thing to have and could be a project for GSoC 16 (not completely trivial but also not terribly hard)...(?).
