### ISSUE TITLE
Facing issue with cython on OSX

### ISSUE THREAD

**Issue by kaushik94** [tardis-sn/tardis#870]
I am facing this issue on OSX:
<img width="1017" alt="screen shot 2018-09-26 at 8 05 47 pm" src="https://user-images.githubusercontent.com/6545467/46087282-98bd5e00-c1c7-11e8-8a3e-75c15f94b47b.png">
I have followed the instructions on tardis installation and cython installed via ` conda install -c anaconda cython`. `Cython version 0.28.1`

**Comment by unoebauer** [comment]
Intresting - not sure what's going on here. But when in doubt cleaning you tardis checkout before building with
``` 
git clean -dfx
```
has helped more often than not.

**Comment by wkerzendorf** [comment]
@kaushik94 did that help?

**Comment by kaushik94** [comment]
I tried `git clean -dfx`, still the same issue. Also I have installed cython 0.28.1 inside the env.

**Comment by unoebauer** [comment]
Which cython are you using, @wkerzendorf? After all, Tardis is running on your mac.

**Comment by wkerzendorf** [comment]
@unoebauer @kaushik94 around that version number is fine. I think cython is not installed in the env that you use to compile python. so when you do `python setup.py develop` are you sure cython is importable from the python?

**Comment by kaushik94** [comment]
Hi, I'm not sure but this could be an issue with python 3 being deleted from my system previously but the soft links still hanging on. I have not investigated the issue but I have set up a new user on my mac. I have downloaded anaconda and currently installing it. I will let you know once this setup is complete. @wkerzendorf may be you are right, I did install cython in my env but may be python is not able to import it for some reason. creating a new user might solve the issue.

**Comment by kaushik94** [comment]
Like you said it was the missing cython package. I installed it but the previous symlinks to cython were still not removed. So I created a new user and I think everything is working fine. Sorry for the confusion, closing this issue as resolved.
