### ISSUE TITLE
Trouble installing in Ubuntu 18.04

### ISSUE THREAD

**Issue by rohanp11** [tardis-sn/tardis#872]
I am trying to install TARDIS on my system (Ubuntu 18.04). After creating the virtual environment using Anaconda, I get the following error when I do `pip install git+https://github.com/tardis-sn/tardis`
![screenshot from 2018-10-05 18-06-38](https://user-images.githubusercontent.com/12735796/46535762-fe959e00-c8c9-11e8-80ac-221c3e51593f.png)

**Comment by unoebauer** [comment]
Hi, not sure what's going on here. Could you try the following and let us know what happens:

- clone the github repo:  ``git clone https://github.com/tardis-sn/tardis.git``
- activate the tardis env: ``source activate tardis``
- build tardis manually: ``cd tardis && python setup.py build install``

**Comment by rohanp11** [comment]
Now I am getting the following error message
![screenshot from 2018-10-05 19-38-34](https://user-images.githubusercontent.com/12735796/46540301-8681a500-c8d6-11e8-9d4c-4b9b1c79589a.png)

**Comment by unoebauer** [comment]
Cython may be missing. We had massive problems with cython in the recent past and thus it is currently not included in the env file for Tardis. Try to install cython manually
```
conda install cython
```
and retry to build tardis (do a ``git clean -dfx`` before, just to be safe).

**Comment by rohanp11** [comment]
So tardis seems to install without any errors after manually installing cython but when I try to run the quickstart example in python I get the following error:
![screenshot from 2018-10-08 10-12-17](https://user-images.githubusercontent.com/12735796/46592712-ffede300-cae2-11e8-872c-15cf0d620e4a.png)

**Comment by unoebauer** [comment]
Try to use the ipython ``%debug`` feature to see what exactly is going on. Also, which ``tardis_example.yml`` file are you using?

**Comment by rohanp11** [comment]
This is what I get when I do %debug
```
> /home/rohan/anaconda3/lib/python3.6/site-packages/yaml/scanner.py(576)fetch_value()
    574                     raise ScannerError(None, None,
    575                             "mapping values are not allowed here",
--> 576                             self.get_mark())
    577 
    578             # If this value starts a new block mapping, we need to add
```
And I am using the `tardis_example.yml` file from [here](https://github.com/tardis-sn/tardis-setups/blob/master/2014/2014_kerzendorf_sim/appendix_A1/tardis_example.yml)

**Comment by unoebauer** [comment]
ok, we need to go up a few frames. Maybe it is easiest if you head over to our slack channel

https://tardis-sn.slack.com/

I'll be available for the next 20min and we can try to figure this out together.

**Comment by rohanp11** [comment]
Could you send me an invitation for the workspace on my email? Thanks!

**Comment by wkerzendorf** [comment]
I invited you to slack just now

**Comment by unoebauer** [comment]
I've just realised that you switched to anaconda3/python3. Currently Tardis only runs on python2.7. Once you change back to python 2.7, everything should be fine.

**Comment by unoebauer** [comment]
Once the correct yml file was used

https://raw.githubusercontent.com/tardis-sn/tardis-setups/master/2014/2014_kerzendorf_sim/appendix_A1/tardis_example.yml

the problems were resolved.
