### ISSUE TITLE
link in quick start wrong

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#875]
should be https://raw.githubusercontent.com/tardis-sn/tardis-setups/master/2014/2014_kerzendorf_sim/appendix_A1/tardis_example.yml

**Comment by unoebauer** [comment]
I thought I fixed that in PR #873. The link in the code block on  https://tardis.readthedocs.io/en/latest/quickstart.html
does seem to work, though...

**Comment by nileshpatra** [comment]
can I take up this issue?
