### ISSUE TITLE
integrated spectrum different to virtual one

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#878]
I think this is unusual @chvogl . I remember that we talked about models that have low opacity - maybe that is the problem
![virt_vs_integrated](https://user-images.githubusercontent.com/506116/51957264-f2a18f00-2418-11e9-8bc6-8bd931b24caa.png)

**Comment by chvogl** [comment]
I don't think that low opacity is the problem. One possible explanation would be that the number of lines in the model is too low. This can lead to problems when electron scattering is included. It might also be related to the interpolation of the quantities needed in the integration (e.g., J_Blues). If you send me the yaml file, I will investigate this further.

**Comment by wkerzendorf** [comment]
low lines likely as it's a pure O model.

**Comment by wkerzendorf** [comment]
low line count likely - has to be looked at.

**Comment by wkerzendorf** [comment]
@chvogl what is going on with this?

**Comment by smithis7** [comment]
@Rodot- @wkerzendorf is this still an issue?
