### ISSUE TITLE
Move tests for `tardis.util` from io/tests/test_config_reader to tests/test_util.py

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#88]
The tests are located in the wrong place. 
Also add tests for 'si2' and other species without space. 

There are functions in test_config_reader (like `test_species_string_to_species()` that test functions that are located in util. These functions should be moved to `test_util.py`.

**Comment by unoebauer** [comment]
FYI @wkerzendorf: Move has been performed - no longer an issue - closing...
