### ISSUE TITLE
TARDIS installation issue via pip and error while building with setup.py

### ISSUE THREAD

**Issue by nileshpatra** [tardis-sn/tardis#880]
when I set up a virtual environment using anaconda and ran the command : 
```
pip install git+https://github.com/tardis-sn/tardis
```
I get an error saying : 
```
in __subclasscheck__
        if issubclass(subclass, scls):
      File "/home/nilesh/anaconda3/envs/tardis/lib/python2.7/site-packages/typing.py", line 1250, in __subclasscheck__
        return super(GenericMeta, self).__subclasscheck__(cls)
    TypeError: super() argument 1 must be type, not None
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-wPB39p/
```
I get the exact same error when I downloaded the repository and tried building it using python .The command I used is :  
```
python setup.py build install
```

**Comment by wkerzendorf** [comment]
I think running it twice makes it work.

**Comment by nileshpatra** [comment]
installing sphinx 1.5.6 resolved the issue :+1:

**Comment by wkerzendorf** [comment]
@nileshpatra That's great - that means you found a fix - can you add this to the documentation?

**Comment by nileshpatra** [comment]
@wkerzendorf , sure 😄 . But I don't have rights/access to adding this to the documentation at https://tardis.readthedocs.io/en/latest/installation.html . 
Should I make a PR to add it in the readme itself?

**Comment by wkerzendorf** [comment]
the documentation lives in this repository under `docs`

**Comment by nileshpatra** [comment]
@wkerzendorf . I'm sorry , I'll for sure add this .

**Comment by nileshpatra** [comment]
@wkerzendorf , added #884
