### ISSUE TITLE
test data for continuum comparison not working with python3

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#882]
Unfortunately, the porting the code to python 3 has trouble with the format that `z2rkstate` is stored in the HDFStore. I think there are probably better ways - but I would need your expertise @chvogl 

The problems when reading the hdfstore are 

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 1: ordinal not in range(128)`
and trying to writing it to `utf8` results in `TypeError: lookup() argument must be str, not numpy.bytes_`

**Comment by chvogl** [comment]
Fixed in #879 with merge of wkerzendorf/tardis#24.
