### ISSUE TITLE
KeyError: 'Level atomic_number not found' 

### ISSUE THREAD

**Issue by cquark7** [tardis-sn/tardis#898]
I get this error when I try to generate `output_spectrum.dat` by running this command:
`tardis tardis_example.yml output_spectrum.dat`

I installed Tardis in Python 3 by following the instructions present here:
https://tardis.readthedocs.io/en/latest/installation.html#installing-tardis-with-anaconda
(replaced `tardis_env27.yml` with new `tardis_env3.yml` for Python 3)

I fixed this issue by studying the traceback message and found that my conda environment was using a dependency (Pandas) which was installed in my python3 system interpreter.

**FIX:**
I checked the version of Pandas used in my environment, it was `0.23.4` I then compared it with version mentioned in tardis_env3.yml, they were different! 
Just upgrade Pandas using `pip install pandas==0.24` if you face this error.

**Comment by wkerzendorf** [comment]
So why did it install the old version of pandas?

**Comment by cquark7** [comment]
It didn't install an old version, it was using a previously installed version of pandas present in `~/.local`.
conda inherited pandas from that directory (I guess that's how it's configured). This is an open issue:   https://github.com/conda/conda/issues/7173
