### ISSUE TITLE
Atomic database seems to contain float level indices

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#93]
That is strange, but seems to work in production code. I recall that somehow that was okay - maybe even desired. This should be fixed/explored.

**Comment by kaushik94** [comment]
Thats probably because numpy allows to do so http://stackoverflow.com/questions/8514547/why-ndarray-allow-floating-point-index

**Comment by unoebauer** [comment]
@wkerzendorf, @ssim, @chvogl: has this been explored? is this still relevant?

**Comment by chvogl** [comment]
INFO:
The following level indices are floats:
* lines: level_number_lower, level_number_upper
* macro_atom_data: source_level_number, destination_level_number
