### ISSUE TITLE
link to environment definition file broken

### ISSUE THREAD

**Issue by HeloiseS** [tardis-sn/tardis#941]
The link under "environment definition file" leads to a 404 error. 
It is first found here:
 
> Requirements
> You can see a list of all the requirements of TARDIS in the environment definition file.

but also in other places in the docs. 

The link given for the conda environment file:
`https://raw.githubusercontent.com/tardis-sn/tardis/master/tardis_env27.yml`

is also broken (is it supposed to be the same link??)

**Comment by wkerzendorf** [comment]
@HeloiseS we now use TARDIS with python 3. are you still stuck there?

**Comment by wkerzendorf** [comment]
sorry about the late response.

**Comment by HeloiseS** [comment]
No probs. I stalkes your github and found the python 3 install files and I got it working ;)

You should probably update the docs though when you have time

**Comment by wkerzendorf** [comment]
see #948  😉
