### ISSUE TITLE
TARDIS documentation restructure (I of many)

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#948]
TARDIS is not only compatible with Python 2.7
typo in recommend on installation
update the link to tardis_env3. yml

change the running tardis to tardis configuration file
move formal integral to configuration

move stella to helper scripts

**Comment by VGZELDA** [comment]
hello @wkerzendorf . Can you please elaborate the issue, I would love to work on it.
Thanks

**Comment by wkerzendorf** [comment]
@VGZELDA it's a closed issue.

**Comment by wkerzendorf** [comment]
I wrote on gitter - have a look there.

**Comment by VGZELDA** [comment]
Sorry, I failed to notice it. I am trying to get familiarized with Tardis. Hope to make a PR soon.
