### ISSUE TITLE
difference between code and description

### ISSUE THREAD

**Issue by wkerzendorf** [tardis-sn/tardis#95]
excitation: nebular (I don't think it's an option, but I don't know which are. It's not clear)
radiative_rates_type: detailed (log file in attachment, also, the comment says that lte, nebular and detailed are supported but the error message says only dilute-blackbody and detailed) 

https://www.dropbox.com/s/cvjclktxdyhffg5/sofiatti-Mar11-2014-tardis_rad_detailed.log

**Comment by unoebauer** [comment]
@wkerzendorf: A quick check using tardis_example reveals the following behaviour:

 * wrong/unknown excitation option: error message:
```ConfigValueError: Given value (bla) not allowed in constraint (set(['dilute-lte', 'lte'])). [['plasma', 'excitation']]```
 * wrong/unknown ionisation option: error message: ```ConfigValueError: Given value (bla) not allowed in constraint (set(['nebular', 'lte'])). [['plasma', 'ionization']]```
 * wrong/unknown radiative_rates_type: error message: ```Given value (bla) not allowed in constraint (set(['detailed', 'blackbody', 'dilute-blackbody'])). [['plasma', 'radiative_rates_type']]```

To me this is exactly the correct behaviour - must have been fixed along the way ;)

**Comment by unoebauer** [comment]
FYI: @wkerzendorf, @ssim: closing this issue (see comment above)
