### ISSUE TITLE
test_plasma_vboundary

### ISSUE THREAD

**Issue by marxwillia** [tardis-sn/tardis#963]
Why does test_plasma_vboundary need to run assemble_plasma?  It takes a long time to run all the tests.

**Comment by chvogl** [comment]
Do we know what the purpose of this test is? It seems like it does not test anything particularly useful. It was introduced relatively recently in 87c9b39. The origin is also quite peculiar since it was seemingly authored by @Youssef15015 and committed by @marxwillia .

**Comment by marxwillia** [comment]
@chvogl It was definitely a test that I wrote, but I think I had to rebase my branch onto master after youssef's PR was merged.  The purpose of the test was to make sure that there were no edge case errors when the plasma is assembled pertaining to the v_outer/inner boundary velocities.
