### ISSUE TITLE
Running custom (STELLA code) density/abund profile

### ISSUE THREAD

**Issue by manolis07gr** [tardis-sn/tardis#979]
Hi all,

I am now attempting to post-process an 1D rad-hydro SN ejecta profile from the STELLA code at a certain phase (50 days after explosion) using TARDIS, and I have found this reference on parsing STELLA data to csv from @wkerzendorf:

https://github.com/tardis-sn/tardis/blob/master/docs/running/converters/stella_to_tardis.ipynb

I was able to run this without problems, and I got a density_parse.csv and an abund_parse.csv files.
However, when using external profiles within TARDIS I see that I basically have two options: either to use the (original) approach:

model:
  structure:
    type: file
    filename: density.dat
    filetype: simple_ascii
    v_inner_boundary: 11000 km/s
    v_outer_boundary: 20000 km/s

  abundances:
    type: file
    filename: abund.dat
    filetype: simple_ascii

Or to use the new csvy file approach. I am assuming this is slightly different from a regular .csv, so I was wondering if you have any example python code of computing virtual/integrated TARDIS spectra using a density/abund csv input file - perhaps even for STELLA - and where I may find such reference.

Thank you again!

**Comment by marxwillia** [comment]
Hi Manos,

There is a documentation page explaining the csvy format for TARDIS:
https://tardis-sn.github.io/tardis/models/index.html?highlight=csvy

and a link to the official csvy format definition:
https://csvy.org

There are example csvy model files used in the tests:
tardis/model/tests/data/csvy_full_rad_abundance_test.csvy

Let me know if you have other questions!
