### ISSUE TITLE
Trivial question on reference timescales

### ISSUE THREAD

**Issue by manolis07gr** [tardis-sn/tardis#981]
Hi all,

So I am now loading my custom density.dat and abund.csv files through my yaml files and post-processing with TARDIS. The profile is taken by a STELLA code model at 50 days after explosion (it's a snapshot of the profile at 50 days after explosion).

The question is, what is the right value that one should input into the .yml input file and into the density.dat header in order to run the spectrum for the current snapshot since it's already at day 50? If I put:

time_explosion: 50 day

and

50.0 day on the header of my density.dat

I am afraid it will evolve, homologously, my profile forward another 50 days. Things do not work if I put "zero" for reference time of course. 

What is the best way to handle it? And should those two values be the same?

Also, is the "luminosity_requested" value what I expect the total output bolometric luminosity at that phase to be (i.e. from the STELLA simulation)?

Thank you!

**Comment by marxwillia** [comment]
Hi Manos,

In general, you should look in tardis/io/schemas/ where you can find descriptions of the model input parameters.  In this case, take a look at the schema for the csvy_model:  https://github.com/tardis-sn/tardis/blob/master/tardis/io/schemas/csvy_model.yml

You should set time_explosion = 50 day as well as the model_density_time_0 = 50 day.  This will tell TARDIS that your model's density profile is defined at 50days, and when the homologous expansion is done, the density will be evolved forward (50 - 50) days.

**Comment by wkerzendorf** [comment]
@manolis07gr can this issue be closed.

**Comment by manolis07gr** [comment]
@wkerzendorf yes. Working on some new models and will be reaching back to the community for help, thank you!
