### ISSUE TITLE
install error with .pyx

### ISSUE THREAD

**Issue by xiangyun19** [tardis-sn/tardis#987]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
python setup.py install

```
#### Problem description
Firstly, I cloned the repository from https://github.com/tardis-sn/tardis.git. Then I installed the anaconda env with the tardis_env3.yml and activated tardis. Then I try to install the tardis with python setup.py install, but I got the following error:

building 'tardis.plasma.properties.util.macro_atom' extension
error: unknown file type '.pyx' (from 'tardis/plasma/properties/util/macro_atom.pyx')

I have tried to 'pip install pyrex', but there is no suitable pyrex for python3.x. I have no idea about this. Please help me. Thank you.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Expected Output

**Comment by wkerzendorf** [comment]
@xiangyun19 can you post the full output. TARDIS is also only supported on linux and macos

**Comment by xiangyun19** [comment]
(tardis) xiangyun@xiangyun-5675:~/software/tardis20191119$ python setup.py install
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
/home/xiangyun/software/tardis20191119/astropy_helpers/git_helpers.py:114: UserWarning: Error running git: [Errno 2] No such file or directory: 'git': 'git'
  warnings.warn('Error running git: ' + str(e))
/home/xiangyun/software/tardis20191119/astropy_helpers/setup_helpers.py:163: AstropyDeprecationWarning: The package argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/setup_helpers.py:168: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/setup_helpers.py:174: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/setup_helpers.py:188: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/version_helpers.py:241: AstropyDeprecationWarning: The packagename argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/version_helpers.py:246: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/version_helpers.py:252: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/version_helpers.py:266: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/git_helpers.py:114: UserWarning: Error running git: [Errno 2] No such file or directory: 'git': 'git'
  warnings.warn('Error running git: ' + str(e))
/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '3.0.dev' to '3.0.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing tardis_sn.egg-info/PKG-INFO
writing dependency_links to tardis_sn.egg-info/dependency_links.txt
writing entry points to tardis_sn.egg-info/entry_points.txt
writing requirements to tardis_sn.egg-info/requires.txt
writing top-level names to tardis_sn.egg-info/top_level.txt
reading manifest file 'tardis_sn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGES.rst'
warning: no files found matching '*.c' under directory '*.pyx'
warning: no files found matching '*.pxd' under directory '*.pyx'
warning: no files found matching '*.h' under directory '*.pyx'
warning: no files found matching '*' under directory 'licenses'
warning: no files found matching '*' under directory 'cextern'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no files found matching '*' under directory 'astropy_helpers/astropy_helpers.egg-info'
warning: no previously-included files found matching 'astropy_helpers/.git'
warning: no previously-included files found matching 'astropy_helpers/.gitignore'
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'tardis_sn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying tardis/version.py -> build/lib.linux-x86_64-3.6/tardis
copying tardis/_compiler.c -> build/lib.linux-x86_64-3.6/tardis
copying tardis/plasma/properties/util/macro_atom.c -> build/lib.linux-x86_64-3.6/tardis/plasma/properties/util
running build_ext
building 'tardis.compiler_version' extension
gcc -pthread -B /home/xiangyun/anaconda3/envs/tardis/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xiangyun/anaconda3/envs/tardis/include/python3.6m -c tardis/_compiler.c -o build/temp.linux-x86_64-3.6/tardis/_compiler.o
gcc -pthread -shared -B /home/xiangyun/anaconda3/envs/tardis/compiler_compat -L/home/xiangyun/anaconda3/envs/tardis/lib -Wl,-rpath=/home/xiangyun/anaconda3/envs/tardis/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/tardis/_compiler.o -o build/lib.linux-x86_64-3.6/tardis/compiler_version.cpython-36m-x86_64-linux-gnu.so
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/lib/x86_64-linux-gnu" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/lib/../lib" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/x86_64-linux-gnu" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/../lib" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../.." is unsafe for cross-compilation
building 'tardis.plasma.properties.util.macro_atom' extension
error: unknown file type '.pyx' (from 'tardis/plasma/properties/util/macro_atom.pyx')

I install tardis in a Ubuntu system. The attached are the full output.

**Comment by xiangyun19** [comment]
**I noticed that there is no git in my system, so I installed it and ran 'python setup.py install' again, it still gave me the following errors.**

By the way, the git can not work well for the net constraint. I have download the tardis using other way.

(tardis) xiangyun@xiangyun-5675:~/software/tardis20191119$ python setup.py install
git submodule command failed unexpectedly:
error: pathspec 'astropy_helpers' did not match any file(s) known to git.
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
/home/xiangyun/software/tardis20191119/astropy_helpers/git_helpers.py:120: UserWarning: No git repository present at '/home/xiangyun/software/tardis20191119'! Using default dev version.
  'default dev version.'.format(path))
/home/xiangyun/software/tardis20191119/astropy_helpers/setup_helpers.py:163: AstropyDeprecationWarning: The package argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/setup_helpers.py:168: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/setup_helpers.py:174: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/setup_helpers.py:188: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/version_helpers.py:241: AstropyDeprecationWarning: The packagename argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/version_helpers.py:246: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/version_helpers.py:252: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/version_helpers.py:266: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
/home/xiangyun/software/tardis20191119/astropy_helpers/git_helpers.py:120: UserWarning: No git repository present at '/home/xiangyun/software/tardis20191119'! Using default dev version.
  'default dev version.'.format(path))
Freezing version number to ./tardis/version.py
running install
running bdist_egg
running egg_info
writing tardis_sn.egg-info/PKG-INFO
writing dependency_links to tardis_sn.egg-info/dependency_links.txt
writing entry points to tardis_sn.egg-info/entry_points.txt
writing requirements to tardis_sn.egg-info/requires.txt
writing top-level names to tardis_sn.egg-info/top_level.txt
reading manifest file 'tardis_sn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGES.rst'
warning: no files found matching '*.c' under directory '*.pyx'
warning: no files found matching '*.pxd' under directory '*.pyx'
warning: no files found matching '*.h' under directory '*.pyx'
warning: no files found matching '*' under directory 'licenses'
warning: no files found matching '*' under directory 'cextern'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no files found matching '*' under directory 'astropy_helpers/astropy_helpers.egg-info'
warning: no previously-included files found matching 'astropy_helpers/.git'
warning: no previously-included files found matching 'astropy_helpers/.gitignore'
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'tardis_sn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying tardis/version.py -> build/lib.linux-x86_64-3.6/tardis
copying tardis/_compiler.c -> build/lib.linux-x86_64-3.6/tardis
running build_ext
building 'tardis.compiler_version' extension
gcc -pthread -B /home/xiangyun/anaconda3/envs/tardis/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xiangyun/anaconda3/envs/tardis/include/python3.6m -c tardis/_compiler.c -o build/temp.linux-x86_64-3.6/tardis/_compiler.o
gcc -pthread -shared -B /home/xiangyun/anaconda3/envs/tardis/compiler_compat -L/home/xiangyun/anaconda3/envs/tardis/lib -Wl,-rpath=/home/xiangyun/anaconda3/envs/tardis/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/tardis/_compiler.o -o build/lib.linux-x86_64-3.6/tardis/compiler_version.cpython-36m-x86_64-linux-gnu.so
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/lib/x86_64-linux-gnu" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/lib/../lib" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/x86_64-linux-gnu" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/../lib" is unsafe for cross-compilation
/home/xiangyun/anaconda3/envs/tardis/compiler_compat/ld: warning: library search path "/usr/lib/gcc/x86_64-linux-gnu/5/../../.." is unsafe for cross-compilation
building 'tardis.plasma.properties.util.macro_atom' extension
error: unknown file type '.pyx' (from 'tardis/plasma/properties/util/macro_atom.pyx')

**Comment by xiangyun19** [comment]
I have solved this problem. I just download the astropy_helpers and put it in the root directory, and then run 'python setup.py install'.

Thanks for the author's kind help.

**Comment by wkerzendorf** [comment]
Dear all,

Thank you very for you kind help.
However, I still can not sovle my problem.

Since I can not use the 'git clone' for internet constraints, so I installed tardis from source in a --offline mode, and then I downloaded the tardis refdata from https://github.com/tardis-sn/tardis-refdata manually. But I do not know where to put these ref-data. When I ran tardis in the Anaconda envs, I just put the 'tardis_example.yml' and 'kurucz_cd23_chianti_H_He.h5' in the same directory. And I just ran the command

tardis tardis_example.yml outfile.dat

However, I got the following errors:

File "H5F.c", line 586, in H5Fopen
      unable to open file
File "H5Fint.c", line 1384, in H5F_open
      unable to read superblock
File "H5Fsuper.c", line 360, in H5F__super_read
      file signature not found

Unable to open/create file "kurucz_cd23_chianti_H_He.h5"

And then, I have quickstart.ipynb, and I found another method to run tardis_example.yml:

from tardis.io.atom_data.util import download_atom_data
download_atom_data('kurucz_cd23_chianti_H_He.h5')

However, I got another error:

Downloading atomic data from https://media.githubusercontent.com/media/tardis-sn/tardis-refdata/master/atom_data/kurucz_cd23_chianti_H_He.h5 to home
OpenSSL.SSL.SysCallError:(104, 'ECONNRESET')

I have tried to open the given url with the browser, but failed. I can not visit the website.

I think, the refdata from https://github.com/tardis-sn/tardis-refdata may not the up to date files, and they are not suit for the current tardis any more. But I can not download the latest ref-data on line. I wonder if you can send me a copy of the latest ref-data, so that I can figure out what the problem is.
Thank you. I am looking forward to your reply.

Cheers,
Xiangyun Zeng


13207224039@163.com

From: jreichenbach-msu
Date: 2019-11-25 08:55
To: tardis-sn/tardis
CC: Subscribed
Subject: [tardis-sn/tardis] Add physical_quantities jupyter notebook (#990)


You can view, comment on, or merge this pull request online at:
  #990
Commit Summary
Add initial notebook
Add physical_quantities jupyter notebook
File Changes
A docs/physics/physical_quantities.ipynb (414)
Patch Links:
https://github.com/tardis-sn/tardis/pull/990.patch
https://github.com/tardis-sn/tardis/pull/990.diff

**Comment by wkerzendorf** [comment]
@xiangyun19 please do not post on other issues.
