### ISSUE TITLE
Tardis GUI does not work with PySide2 and PyQt5

### ISSUE THREAD

**Issue by manolis07gr** [tardis-sn/tardis#988]
Hi all,

My (latest) version of Anaconda does not allow me to revert back to PySide and PyQt4, so I have to use PySide2 and PyQt5 which are the final versions. As a results, the GUI for TARDIS does not run. A lot of the issues can be fixed if I, by hand, change many "QtGui" method references to "QtWidgets" but other problems still persist.

Does anyone else have the same problem? Are there plans to update the TARDIS GUI so that it's compatible with PySide2 and PyQt5?

Thank you

**Comment by wkerzendorf** [comment]
This should work now @manolis07gr
