### ISSUE TITLE
HDF5 file read error

### ISSUE THREAD

**Issue by xiangyun19** [tardis-sn/tardis#989]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
tardis tardis_example.yml test_out.dat


#### Problem description
**I have installed tardis and downloaded the atom_data. To test the tardis, I just try the command line 'tardis tardis_example.yml test_out.dat', but I got the following errors:**

(tardis) xiangyun@xiangyun-5675:~/software/tardis_build_20191120/docs/quickstart$ tardis tardis_example.yml test_out.dat
[py.warnings         ][WARNING]  /home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev0-py3.6-linux-x86_64.egg/tardis/montecarlo/base.py:40: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  vpacket_logging_config = yaml.load(open(vpacket_config_file_path))
 (warnings.py:99)
[py.warnings         ][WARNING]  /home/xiangyun/anaconda3/envs/tardis/lib/python3.6/importlib/_bootstrap.py:219: QAWarning: pyne.data is not yet QA compliant.
  return f(*args, **kwds)
 (warnings.py:99)
[py.warnings         ][WARNING]  /home/xiangyun/anaconda3/envs/tardis/lib/python3.6/importlib/_bootstrap.py:219: QAWarning: pyne.material is not yet QA compliant.
  return f(*args, **kwds)
 (warnings.py:99)
[py.warnings         ][WARNING]  /home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/astropy/units/quantity.py:1070: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError.
  AstropyDeprecationWarning)
 (warnings.py:99)
[tardis.plasma.standard_plasmas][INFO   ]  Reading Atomic Data from kurucz_cd23_chianti_H_He.h5 (standard_plasmas.py:74)
Traceback (most recent call last):
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py", line 603, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 489, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 586, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1384, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 360, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file 'kurucz_cd23_chianti_H_He.h5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiangyun/anaconda3/envs/tardis/bin/tardis", line 4, in <module>
    __import__('pkg_resources').run_script('tardis-sn==3.0.dev0', 'tardis')
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/tardis", line 67, in <module>
    simulation = Simulation.from_config(tardis_config)
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev0-py3.6-linux-x86_64.egg/tardis/simulation/base.py", line 440, in from_config
    atom_data=kwargs.get('atom_data', None))
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev0-py3.6-linux-x86_64.egg/tardis/plasma/standard_plasmas.py", line 77, in assemble_plasma
    atom_data = AtomData.from_hdf(atom_data_fname)
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/tardis_sn-3.0.dev0-py3.6-linux-x86_64.egg/tardis/io/atom_data/base.py", line 156, in from_hdf
    with pd.HDFStore(fname, 'r') as store:
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py", line 488, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py", line 636, in open
    raise IOError(str(e))
OSError: HDF5 error back trace

  File "H5F.c", line 586, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1384, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 360, in H5F__super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file 'kurucz_cd23_chianti_H_He.h5'

I have no idea about this, please help me. Thank you very much.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Expected Output

**Comment by xiangyun19** [comment]
Hi, 
These days I was trying to figure out what the problem is as posed above.
I tried to update the reference data followed the guides from https://github.com/kowal180/tardis/blob/docs/update_refdata/docs/development/update_refdata.rst . I tried to generate a new copy of new ref-data via the following command:

python setup.py test --args="--tardis-refdata=/home/software/tardiss/tardis_build_20191120/tardis-refdata-master --generate-reference"

however, this end with fail, the following are the errors:

************************************
>   ???
E   tables.exceptions.HDF5ExtError: HDF5 error back trace
E   
E     File "H5F.c", line 586, in H5Fopen
E       unable to open file
E     File "H5Fint.c", line 1384, in H5F_open
E       unable to read superblock
E     File "H5Fsuper.c", line 360, in H5F__super_read
E       file signature not found
E   
E   End of HDF5 error back trace
E   
E   Unable to open/create file '/home/xiangyun/software/tardiss/tardis_build_20191120/tardis-refdata-master/atom_data/kurucz_cd23_chianti_H_He.h5'

tables/hdf5extension.pyx:489: HDF5ExtError

During handling of the above exception, another exception occurred:

config_init_trad_fname = '/tmp/tardis-test-1f1m6q8d/lib/python3.6/site-packages/tardis/plasma/tests/data/config_init_trad.yml'
v_inner_boundary = 3150, v_outer_boundary = 3900
atomic_data_fname = '/home/xiangyun/software/tardiss/tardis_build_20191120/tardis-refdata-master/atom_data/kurucz_cd23_chianti_H_He.h5'

    @pytest.mark.parametrize("v_inner_boundary, v_outer_boundary",
                             [(3350, 3650),
                              (2900, 3750),
                              (2900, 3850),
                              (2900, 3900),
                              (2950, 3750),
                              (2950, 3850),
                              (2950, 3900),
                              (3050, 3750),
                              (3050, 3850),
                              (3050, 3900),
                              (3150, 3750),
                              (3150, 3850),
                              (3150, 3900)])
    def test_plasma_vboundary(config_init_trad_fname, v_inner_boundary, v_outer_boundary, atomic_data_fname):
        tardis_config = Configuration.from_yaml(config_init_trad_fname)
        tardis_config.atom_data = atomic_data_fname
        tardis_config.model.structure.v_inner_boundary = v_inner_boundary * u.km / u.s
        tardis_config.model.structure.v_outer_boundary = v_outer_boundary * u.km / u.s
>       simulation = Simulation.from_config(tardis_config)

tardis/plasma/tests/test_plasma_vboundary.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tardis/simulation/base.py:440: in from_config
    atom_data=kwargs.get('atom_data', None))
tardis/plasma/standard_plasmas.py:77: in assemble_plasma
    atom_data = AtomData.from_hdf(atom_data_fname)
tardis/io/atom_data/base.py:156: in from_hdf
    with pd.HDFStore(fname, 'r') as store:
/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py:488: in __init__
    self.open(mode=mode, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <class 'pandas.io.pytables.HDFStore'>
File path: /home/xiangyun/software/tardiss/tardis_build_20191120/tardis-refdata-master/atom_data/kurucz_cd23_chianti_H_He.h5

mode = 'r', kwargs = {}
tables = <module 'tables' from '/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/tables/__init__.py'>

    def open(self, mode='a', **kwargs):
        """
        Open the file in the specified mode
    
        Parameters
        ----------
        mode : {'a', 'w', 'r', 'r+'}, default 'a'
            See HDFStore docstring or tables.open_file for info about modes
        """
        tables = _tables()
    
        if self._mode != mode:
    
            # if we are changing a write mode to read, ok
            if self._mode in ['a', 'w'] and mode in ['r', 'r+']:
                pass
            elif mode in ['w']:
    
                # this would truncate, raise here
                if self.is_open:
                    raise PossibleDataLossError(
                        "Re-opening the file [{0}] with mode [{1}] "
                        "will delete the current file!"
                        .format(self._path, self._mode)
                    )
    
            self._mode = mode
    
        # close and reopen the handle
        if self.is_open:
            self.close()
    
        if self._complevel and self._complevel > 0:
            self._filters = _tables().Filters(self._complevel, self._complib,
                                              fletcher32=self._fletcher32)
    
        try:
            self._handle = tables.open_file(self._path, self._mode, **kwargs)
        except (IOError) as e:  # pragma: no cover
            if 'can not be written' in str(e):
                print(
                    'Opening {path} in read-only mode'.format(path=self._path))
                self._handle = tables.open_file(self._path, 'r', **kwargs)
            else:
                raise
    
        except (ValueError) as e:
    
            # trap PyTables >= 3.1 FILE_OPEN_POLICY exception
            # to provide an updated message
            if 'FILE_OPEN_POLICY' in str(e):
                e = ValueError(
                    "PyTables [{version}] no longer supports opening multiple "
                    "files\n"
                    "even in read-only mode on this HDF5 version "
                    "[{hdf_version}]. You can accept this\n"
                    "and not open the same file multiple times at once,\n"
                    "upgrade the HDF5 version, or downgrade to PyTables 3.0.0 "
                    "which allows\n"
                    "files to be opened multiple times at once\n"
                    .format(version=tables.__version__,
                            hdf_version=tables.get_hdf5_version()))
    
            raise e
    
        except (Exception) as e:
    
            # trying to read from a non-existent file causes an error which
            # is not part of IOError, make it one
            if self._mode == 'r' and 'Unable to open/create file' in str(e):
>               raise IOError(str(e))
E               OSError: HDF5 error back trace
E               
E                 File "H5F.c", line 586, in H5Fopen
E                   unable to open file
E                 File "H5Fint.c", line 1384, in H5F_open
E                   unable to read superblock
E                 File "H5Fsuper.c", line 360, in H5F__super_read
E                   file signature not found
E               
E               End of HDF5 error back trace
E               
E               Unable to open/create file '/home/xiangyun/software/tardiss/tardis_build_20191120/tardis-refdata-master/atom_data/kurucz_cd23_chianti_H_He.h5'

/home/xiangyun/anaconda3/envs/tardis/lib/python3.6/site-packages/pandas/io/pytables.py:636: OSError
------------------------------------- Captured stdout call -------------------------------------
[tardis.model.base   ][WARNING]  Abundances have not been normalized to 1. - normalizing (base.py:469)
[tardis.plasma.standard_plasmas][INFO   ]  Reading Atomic Data from /home/xiangyun/software/tardiss/tardis_build_20191120/tardis-refdata-master/atom_data/kurucz_cd23_chianti_H_He.h5 (standard_plasmas.py:74)
-------------------------------------- Captured log call ---------------------------------------
WARNING  tardis.model.base:base.py:469 Abundances have not been normalized to 1. - normalizing
INFO     tardis.plasma.standard_plasmas:standard_plasmas.py:74 Reading Atomic Data from /home/xiangyun/software/tardiss/tardis_build_20191120/tardis-refdata-master/atom_data/kurucz_cd23_chianti_H_He.h5
========== 13 failed, 263 passed, 128 skipped, 1 xfailed, 976 error in 383.86 seconds ==========
************************************

I think the current ref-data are not suit for the new tardis any more. Since I can not use git to download the up to date model online, so I wonder if the author could update the tardis-refdata repository, and I can download the new ref-data and use them offline. Thank you.

**Comment by kaushik94** [comment]
Hey @xiangyun19 I got the same error a few days ago. I think we should download the big files using git lfs. The files from git clone are just pointers to the large file. Unfortunately I can't point you to the exact resource on how to do it since I don't remember myself. But you can find out about git lfs online and it should work fine. I hope this helps.
