### ISSUE TITLE
Remove TRAVIS from documentation pages

### ISSUE THREAD

**Issue by marxwillia** [tardis-sn/tardis#993]
I think TRAVIS is outdated, and pages like the reference data update doc page should be updated:

https://tardis-sn.github.io/tardis/development/update_refdata.html

**Comment by wkerzendorf** [comment]
okay - maybe that will come with our tests update @kaushik94

**Comment by kaushik94** [comment]
@wkerzendorf I missed this comment, sorry for late reply. Yes sure, we need to write documentation on Azure pipelines. And possibly github hooks in the future.
