### ISSUE TITLE
Integrated Spectrum Spike

### ISSUE THREAD

**Issue by marxwillia** [tardis-sn/tardis#996]
Sometimes the integrated spectrum for a TARDIS model exhibits a spike to positive infinity.  This spike is not present in the virtual spectrum.  The spike usually appears around 5000 Angstroms.  In the past, rerunning the model with more photon packets solved the problem, although the spike did sometimes occur.  Currently (post interpolation fix by @chvogl, see #971) the spike persists on rerunning with the same or larger numbers of photons (I have tried up to 3e5).  The plot below is produced from the attached csvy and config files:

I have checked the jblues, Edotlu, and tau_sobolevs before making the integrated spectrum, and there were no negative values.

![spec_spike](https://user-images.githubusercontent.com/1607464/70649027-54767c00-1c1a-11ea-82d9-cb2fc837202a.png)

[spike.zip](https://github.com/tardis-sn/tardis/files/3952017/spike.zip)

**Comment by chvogl** [comment]
It might be worth a try to run the simulation again with electron scattering disabled.

**Comment by marxwillia** [comment]
I tried this, but the problem persists.

**Comment by marxwillia** [comment]
Seems like the problem might be solved by clipping to 1e-20 instead of 0.0 after the interpolation.  Will need to do some more tests.

**Comment by wkerzendorf** [comment]
What needs to happen to this?
