### ISSUE TITLE
ValidationError: Running test_integration.py results in error

### ISSUE THREAD

**Issue by kaushik94** [tardis-sn/tardis#997]
#### Code Sample, a copy-pastable example if possible

```python
python setup.py test --args="--integration-tests=/Users/ghost/Desktop/tardis/docs/development/integration.yml -m integration --generate-reference --less-packets"

```
#### Problem description

This results in the following error:
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('black_body_sampling' was unexpected)

#### Expected Output

**Comment by not4win** [comment]
The schema file 'montecarlo' does not match the config files present in the integration_tests directory.
Therfore gives an error while validating one with the other.
