### ISSUE TITLE
Help needed with plasma nLTE schema

### ISSUE THREAD

**Issue by manolis07gr** [tardis-sn/tardis#999]
Hi all,

I run a TARDIS model where my input file (velocity, density, trad and composition) is read-in from a csvy file. Then I ask for some key species to be treated in nLTE by using the plasma nLTE schema options as described and are available in examples in the TARDIS distribution. Yet I get the following error when I request for ['H I','He II'] species to be treated in nLTE:

File "/anaconda3/envs/tardis/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 696, in _check_bounds
    raise ValueError("A value in x_new is above the interpolation "
ValueError: A value in x_new is above the interpolation range.

Below is the .yml file I use:

# Example YAML configuration for TARDIS
tardis_config_version: v1.0

supernova:
  luminosity_requested: 9.44 log_lsun
  time_explosion: 10 day

atom_data: kurucz_cd23_chianti_H_He.h5

csvy_model: model_IIP_day2.csvy

plasma:
    ionization: nebular
    excitation: dilute-lte
    radiative_rates_type: dilute-blackbody
    line_interaction_type: macroatom
    nlte:
        species: ['H I','He II']
        
montecarlo:
  seed: 23111963
  no_of_packets: 5.0e+4
  iterations: 30
  nthreads: 8

  last_no_of_packets: 2.e+5

  convergence_strategy:
    type: damped
    damping_constant: 0.5
    threshold: 0.05
    fraction: 0.8
    
    t_inner:
      damping_constant: 0.0

spectrum:
  start: 500 angstrom
  stop: 20000 angstrom
  num: 10000
  integrated:
    interpolate_shells: 80
  
--------
And here is the header of the input .csvy file:

---
name: csvy_full
model_density_time_0: 2.0 d
model_isotope_time_0: 2.0 d
description: Full csvy config file for TARDIS.
tardis_model_config_version: v1.0
datatype:
  fields:
    -  name: velocity
       unit: km/s
       desc: velocities of shell outer bounderies.
    -  name: density
       unit: g/cm^3
       desc: density of shell.
    -  name: t_rad
       unit: K
       desc: radiative temperature.
    -  name: H
       desc: fractional H abundance.
    -  name: He3
       desc: fractional He3 abundance
    -  name: He
       desc: fractional He abundance
    -  name: C
       desc: fractional C abundance
    -  name: N
       desc: fractional N abundance
    -  name: O
       desc: fractional O abundance
    -  name: Ne
       desc: fractional Ne abundance
    -  name: Na
       desc: fractional Na abundance
    -  name: Mg
       desc: fractional Mg abundance
    -  name: Si
       desc: fractional Si abundance
    -  name: S
       desc: fractional S abundance
    -  name: Ar
       desc: fractional Ar abundance
    -  name: Ca
       desc: fractional Ca abundance
    -  name: Ti
       desc: fractional Ti abundance
    -  name: Cr48
       desc: fractional Cr48 abundance
    -  name: Cr56
       desc: fractional Cr56 abundance
    -  name: Fe52
       desc: fractional Fe52 abundance
    -  name: Fe54
       desc: fractional Fe54 abundance
    -  name: Fe56
       desc: fractional Fe56 abundance
    -  name: Co56
       desc: fractional Co56 abundance
    -  name: Ni56
       desc: fractional Ni56 abundance
                                      
v_inner_boundary: 1850 km/s
v_outer_boundary: 2600 km/s
---
velocity,density,t_rad,H,He3,He,C,N,O,Ne,Na,Mg,Si,S,Ar,Ca,Ti,Cr48,Cr56,Fe52,Fe54,Fe56,Co56,Ni56

[DATA]

I will really appreciate your help,

manolis07gr

**Comment by wkerzendorf** [comment]
@manolis07gr TARDIS currently is missing substantial microphysics for hydrogen-rich atmospheres (e.g. bound-free processes) and we do not recommend using it for this. However, @chvogl (member of the TARDIS core team) is working on this aspect and it will be in the main version of TARDIS in the next few months.

**Comment by manolis07gr** [comment]
Hi @wkerzendorf that is certainly good to know. @marxwillia mentioned that as well and said that, for H-poor SN ejecta, however, TARDIS assumptions may still be valid. If I switch to looking at Type Ib/Ic SN ejecta from MESA, would you think that I can get accurate spectra? Or am I still missing something?

Thank you both!

Manos

**Comment by wkerzendorf** [comment]
@marxwillia did you guys talk? Can we close this?
